/**
 * Agriculture Industry Templates
 * 3 templates for farm and agricultural inspections
 */

import { TemplateDefinition, SAFETY_CHECKLIST_ITEMS } from './types';

export const AGRICULTURE_TEMPLATES: TemplateDefinition[] = [
  // ============================================
  // 1. FARM SAFETY INSPECTION
  // ============================================
  {
    id: 'agriculture-farm-safety',
    name: 'Farm Safety Inspection',
    description: 'Comprehensive farm safety inspection covering buildings, equipment, and operations',
    record_type_id: 'agriculture',
    sections: [
      {
        name: 'Farm Information',
        items: [
          { label: 'Farm Name', item_type: 'text', is_required: true },
          { label: 'Farm Address', item_type: 'text', is_required: true },
          { label: 'Farm Type', item_type: 'multi_select', is_required: true, options: ['Arable', 'Dairy', 'Beef', 'Sheep', 'Pigs', 'Poultry', 'Mixed', 'Horticulture', 'Other'] },
          { label: 'Farm Size (Hectares)', item_type: 'number' },
          { label: 'Number of Workers', item_type: 'number' },
          { label: 'Farm Owner/Manager', item_type: 'text', is_required: true },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
        ],
      },
      {
        name: 'Machinery and Equipment',
        items: [
          { label: 'Machinery Photo', item_type: 'photo' },
          { label: 'Tractors in Good Condition', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'PTO Guards in Place', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Roll-Over Protection (ROPS)', item_type: 'pass_fail', is_required: true },
          { label: 'Seatbelts Fitted and Used', item_type: 'pass_fail' },
          { label: 'Machinery Guards in Place', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Emergency Stops Working', item_type: 'pass_fail' },
          { label: 'Operators Trained', item_type: 'pass_fail', is_required: true },
          { label: 'Maintenance Records Current', item_type: 'pass_fail' },
          { label: 'Keys Removed When Not in Use', item_type: 'pass_fail' },
          { label: 'Hydraulic Hoses Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Machinery Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Farm Vehicles and Transport',
        items: [
          { label: 'ATVs/Quad Bikes Present', item_type: 'yes_no' },
          { label: 'ATV Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Helmets Provided for ATVs', item_type: 'pass_fail' },
          { label: 'ATV Training Provided', item_type: 'pass_fail' },
          { label: 'No Children on ATVs', item_type: 'pass_fail' },
          { label: 'Farm Vehicles MOT/Tested', item_type: 'pass_fail' },
          { label: 'Trailers in Good Condition', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Load Securing Equipment', item_type: 'pass_fail' },
          { label: 'Vehicle Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Livestock Handling',
        items: [
          { label: 'Livestock Handling Facilities', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Handling Facility Photo', item_type: 'photo' },
          { label: 'Crush/Race Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Non-Slip Flooring', item_type: 'pass_fail' },
          { label: 'Gates and Latches Working', item_type: 'pass_fail' },
          { label: 'Escape Routes for Handlers', item_type: 'pass_fail', is_required: true },
          { label: 'Bull Handling Facilities', item_type: 'pass_fail' },
          { label: 'Warning Signs for Bulls', item_type: 'pass_fail' },
          { label: 'Livestock Handling Training', item_type: 'pass_fail' },
          { label: 'Livestock Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Farm Buildings',
        items: [
          { label: 'Building Photo', item_type: 'photo' },
          { label: 'Structural Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Roof Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Asbestos Present', item_type: 'yes_no' },
          { label: 'Asbestos Managed', item_type: 'pass_fail' },
          { label: 'Floors in Good Condition', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Ladders/Access Safe', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Lighting Adequate', item_type: 'pass_fail' },
          { label: 'Ventilation Adequate', item_type: 'pass_fail' },
          { label: 'Building Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Storage and Hazardous Substances',
        items: [
          { label: 'Chemical Store Photo', item_type: 'photo' },
          { label: 'Chemical Store Secure', item_type: 'pass_fail', is_required: true },
          { label: 'Chemicals Properly Stored', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'COSHH Assessments', item_type: 'pass_fail' },
          { label: 'SDS Sheets Available', item_type: 'pass_fail' },
          { label: 'Pesticide Store Compliant', item_type: 'pass_fail' },
          { label: 'Fuel Storage Safe', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Bunded Areas Adequate', item_type: 'pass_fail' },
          { label: 'Grain Store Condition', item_type: 'condition' },
          { label: 'Silage Clamps Safe', item_type: 'pass_fail' },
          { label: 'Storage Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Slurry and Manure',
        items: [
          { label: 'Slurry Storage Present', item_type: 'yes_no' },
          { label: 'Slurry Store Photo', item_type: 'photo' },
          { label: 'Slurry Store Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Fencing/Barriers Adequate', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Warning Signs Posted', item_type: 'pass_fail' },
          { label: 'Slurry Mixing Procedures', item_type: 'pass_fail' },
          { label: 'Gas Awareness Training', item_type: 'pass_fail' },
          { label: 'Rescue Equipment Available', item_type: 'pass_fail' },
          { label: 'Slurry Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Electrical Safety',
        items: [
          { label: 'Electrical Installation Tested', item_type: 'pass_fail', is_required: true },
          { label: 'Test Certificate Current', item_type: 'pass_fail' },
          { label: 'Overhead Lines Identified', item_type: 'pass_fail' },
          { label: 'Safe Working Near Lines', item_type: 'pass_fail' },
          { label: 'No Damaged Cables', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'RCDs Fitted', item_type: 'pass_fail' },
          { label: 'Portable Appliances Tested', item_type: 'pass_fail' },
          { label: 'Electrical Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Emergency Preparedness',
        items: [
          { label: 'First Aid Kit Available', item_type: 'pass_fail', is_required: true },
          { label: 'First Aid Training', item_type: 'pass_fail' },
          { label: 'Emergency Contacts Posted', item_type: 'pass_fail' },
          { label: 'Fire Extinguishers', item_type: 'pass_fail' },
          { label: 'Mobile Phone Coverage', item_type: 'pass_fail' },
          { label: 'Lone Working Procedures', item_type: 'pass_fail' },
          { label: 'Emergency Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Total Issues Found', item_type: 'number', is_required: true },
          { label: 'High Priority Issues', item_type: 'number' },
          { label: 'Issue Details', item_type: 'textarea' },
          { label: 'Corrective Actions Required', item_type: 'textarea' },
          { label: 'Overall Farm Safety', item_type: 'dropdown', is_required: true, options: ['Satisfactory', 'Needs Improvement', 'Significant Issues', 'Serious Concerns'] },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Farm Owner/Manager Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 2. LIVESTOCK WELFARE INSPECTION
  // ============================================
  {
    id: 'agriculture-livestock-welfare',
    name: 'Livestock Welfare Inspection',
    description: 'Animal welfare inspection for farms with livestock',
    record_type_id: 'agriculture',
    sections: [
      {
        name: 'Farm Details',
        items: [
          { label: 'Farm Name', item_type: 'text', is_required: true },
          { label: 'Farm Address', item_type: 'text', is_required: true },
          { label: 'Holding Number (CPH)', item_type: 'text' },
          { label: 'Livestock Type', item_type: 'multi_select', is_required: true, options: ['Cattle', 'Sheep', 'Pigs', 'Poultry', 'Goats', 'Horses', 'Other'] },
          { label: 'Total Animal Numbers', item_type: 'number' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Herd/Flock Health Plan', item_type: 'pass_fail' },
          { label: 'Veterinarian Name', item_type: 'text' },
        ],
      },
      {
        name: 'Freedom from Hunger and Thirst',
        items: [
          { label: 'Water Supply Photo', item_type: 'photo' },
          { label: 'Fresh Water Available', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Water Points Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Water Quality Acceptable', item_type: 'pass_fail' },
          { label: 'Drinkers Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Drinkers Working', item_type: 'pass_fail' },
          { label: 'Feed Available', item_type: 'pass_fail', is_required: true },
          { label: 'Feed Quality Acceptable', item_type: 'pass_fail' },
          { label: 'Feed Appropriate for Age/Type', item_type: 'pass_fail' },
          { label: 'Body Condition Score Acceptable', item_type: 'pass_fail', is_required: true },
          { label: 'Feeding Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Freedom from Discomfort',
        items: [
          { label: 'Housing Photo', item_type: 'photo' },
          { label: 'Housing Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Adequate Space per Animal', item_type: 'pass_fail', is_required: true },
          { label: 'Bedding Adequate', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Bedding Clean and Dry', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Ventilation Adequate', item_type: 'pass_fail' },
          { label: 'No Draughts on Animals', item_type: 'pass_fail' },
          { label: 'Temperature Appropriate', item_type: 'pass_fail' },
          { label: 'Lighting Adequate', item_type: 'pass_fail' },
          { label: 'Shelter Available (Outdoor)', item_type: 'pass_fail' },
          { label: 'Flooring Safe/Non-Slip', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Environment Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Freedom from Pain, Injury, Disease',
        items: [
          { label: 'General Health Observed', item_type: 'condition', is_required: true },
          { label: 'Sick/Injured Animal Photo', item_type: 'photo' },
          { label: 'No Signs of Injury', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Signs of Disease', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Lameness Issues', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Foot Care/Trimming', item_type: 'pass_fail' },
          { label: 'Sick Animals Separated', item_type: 'pass_fail' },
          { label: 'Veterinary Care Available', item_type: 'pass_fail', is_required: true },
          { label: 'Medicine Records Maintained', item_type: 'pass_fail' },
          { label: 'Withdrawal Periods Observed', item_type: 'pass_fail' },
          { label: 'Vaccination Records', item_type: 'pass_fail' },
          { label: 'Parasite Control', item_type: 'pass_fail' },
          { label: 'Health Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Freedom to Express Normal Behaviour',
        items: [
          { label: 'Animals Can Move Freely', item_type: 'pass_fail', is_required: true },
          { label: 'Social Grouping Appropriate', item_type: 'pass_fail' },
          { label: 'No Signs of Aggression', item_type: 'pass_fail' },
          { label: 'Environmental Enrichment', item_type: 'pass_fail' },
          { label: 'Outdoor Access (if applicable)', item_type: 'pass_fail' },
          { label: 'Behaviour Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Freedom from Fear and Distress',
        items: [
          { label: 'Animals Calm When Approached', item_type: 'pass_fail' },
          { label: 'No Signs of Stress', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Humane Handling Observed', item_type: 'pass_fail', is_required: true },
          { label: 'Handling Facilities Adequate', item_type: 'pass_fail' },
          { label: 'Fear/Distress Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Record Keeping',
        items: [
          { label: 'Animal Movement Records', item_type: 'pass_fail', is_required: true },
          { label: 'Identification (Tags/Marks)', item_type: 'pass_fail', is_required: true },
          { label: 'Medicine Records', item_type: 'pass_fail', is_required: true },
          { label: 'Mortality Records', item_type: 'pass_fail' },
          { label: 'Feed Records', item_type: 'pass_fail' },
          { label: 'Record Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Overall Welfare Standard', item_type: 'dropdown', is_required: true, options: ['Excellent', 'Good', 'Acceptable', 'Needs Improvement', 'Unacceptable'] },
          { label: 'Non-Compliances Found', item_type: 'number' },
          { label: 'Non-Compliance Details', item_type: 'textarea' },
          { label: 'Recommendations', item_type: 'textarea' },
          { label: 'Follow-up Required', item_type: 'yes_no' },
          { label: 'Follow-up Date', item_type: 'date' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Farmer Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 3. CROP PRODUCTION INSPECTION
  // ============================================
  {
    id: 'agriculture-crop-production',
    name: 'Crop Production Inspection',
    description: 'Field inspection for arable and horticultural crop production',
    record_type_id: 'agriculture',
    sections: [
      {
        name: 'Farm and Field Information',
        items: [
          { label: 'Farm Name', item_type: 'text', is_required: true },
          { label: 'Farm Address', item_type: 'text', is_required: true },
          { label: 'Field Name/Number', item_type: 'text', is_required: true },
          { label: 'Field Size (Hectares)', item_type: 'number' },
          { label: 'Crop Type', item_type: 'dropdown', is_required: true, options: ['Wheat', 'Barley', 'Oats', 'Oilseed Rape', 'Maize', 'Potatoes', 'Sugar Beet', 'Vegetables', 'Fruit', 'Other'] },
          { label: 'Variety', item_type: 'text' },
          { label: 'Planting Date', item_type: 'date' },
          { label: 'Expected Harvest Date', item_type: 'date' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Weather Conditions', item_type: 'dropdown', options: ['Sunny', 'Cloudy', 'Rainy', 'Windy', 'Frosty'] },
        ],
      },
      {
        name: 'Crop Condition',
        items: [
          { label: 'Field Overview Photo', item_type: 'photo', is_required: true },
          { label: 'Crop Establishment', item_type: 'condition', is_required: true },
          { label: 'Plant Population Adequate', item_type: 'pass_fail' },
          { label: 'Crop Uniformity', item_type: 'condition' },
          { label: 'Growth Stage', item_type: 'text' },
          { label: 'Crop Height (cm)', item_type: 'number' },
          { label: 'Crop Colour Normal', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Crop Detail Photo', item_type: 'photo' },
          { label: 'Estimated Yield', item_type: 'text' },
          { label: 'Crop Condition Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Pest and Disease Assessment',
        items: [
          { label: 'Pest Damage Observed', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Pest Type Identified', item_type: 'text' },
          { label: 'Pest Damage Level', item_type: 'dropdown', options: ['None', 'Low', 'Moderate', 'High', 'Severe'] },
          { label: 'Disease Symptoms Observed', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Disease Photo', item_type: 'photo' },
          { label: 'Disease Type Suspected', item_type: 'text' },
          { label: 'Disease Severity', item_type: 'dropdown', options: ['None', 'Low', 'Moderate', 'High', 'Severe'] },
          { label: 'Treatment Recommended', item_type: 'yes_no' },
          { label: 'Treatment Details', item_type: 'textarea' },
          { label: 'Pest/Disease Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Weed Assessment',
        items: [
          { label: 'Weed Pressure Photo', item_type: 'photo' },
          { label: 'Weed Pressure Level', item_type: 'dropdown', is_required: true, options: ['None', 'Low', 'Moderate', 'High'] },
          { label: 'Predominant Weed Species', item_type: 'text' },
          { label: 'Herbicide Resistant Weeds', item_type: 'yes_no' },
          { label: 'Weed Control Required', item_type: 'yes_no' },
          { label: 'Weed Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Soil and Nutrition',
        items: [
          { label: 'Soil Condition Photo', item_type: 'photo' },
          { label: 'Soil Moisture Level', item_type: 'dropdown', options: ['Dry', 'Adequate', 'Wet', 'Waterlogged'] },
          { label: 'Soil Compaction Issues', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Drainage Adequate', item_type: 'pass_fail' },
          { label: 'Nutrient Deficiency Signs', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Deficiency Type', item_type: 'dropdown', options: ['None', 'Nitrogen', 'Phosphorus', 'Potassium', 'Magnesium', 'Manganese', 'Other'] },
          { label: 'Soil Test Results Available', item_type: 'yes_no' },
          { label: 'Fertiliser Application Recommended', item_type: 'yes_no' },
          { label: 'Soil Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Irrigation (if applicable)',
        items: [
          { label: 'Irrigation System Present', item_type: 'yes_no' },
          { label: 'Irrigation Type', item_type: 'dropdown', options: ['Drip', 'Sprinkler', 'Center Pivot', 'Flood', 'None'] },
          { label: 'Irrigation System Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Coverage Adequate', item_type: 'pass_fail' },
          { label: 'Water Abstraction Licensed', item_type: 'pass_fail' },
          { label: 'Irrigation Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Spray Records Review',
        items: [
          { label: 'Spray Records Available', item_type: 'pass_fail', is_required: true },
          { label: 'Records Up to Date', item_type: 'pass_fail' },
          { label: 'Products Approved for Crop', item_type: 'pass_fail' },
          { label: 'Buffer Zones Observed', item_type: 'pass_fail' },
          { label: 'Operator Qualified', item_type: 'pass_fail' },
          { label: 'Harvest Interval Observed', item_type: 'pass_fail' },
          { label: 'Spray Records Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Overall Crop Condition', item_type: 'dropdown', is_required: true, options: ['Excellent', 'Good', 'Average', 'Poor', 'Failed'] },
          { label: 'Recommended Actions', item_type: 'textarea' },
          { label: 'Priority Treatments', item_type: 'textarea' },
          { label: 'Next Inspection Date', item_type: 'date' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Grower/Manager Signature', item_type: 'signature' },
        ],
      },
    ],
  },
];
