/**
 * US Regulatory Compliance Templates
 * 6 templates for US-specific regulatory inspections (OSHA, FDA, ADA)
 */

import { TemplateDefinition, SAFETY_CHECKLIST_ITEMS } from './types';

export const COMPLIANCE_US_TEMPLATES: TemplateDefinition[] = [
  // ============================================
  // 1. OSHA GENERAL INDUSTRY SAFETY INSPECTION (29 CFR 1910)
  // ============================================
  {
    id: 'compliance-us-osha-general',
    name: 'OSHA General Industry Safety Inspection',
    description: 'Workplace safety inspection per OSHA 29 CFR 1910 General Industry Standards',
    record_type_id: 'compliance-us',
    sections: [
      {
        name: 'Facility Information',
        items: [
          { label: 'Company Name', item_type: 'text', is_required: true },
          { label: 'Facility Address', item_type: 'text', is_required: true },
          { label: 'City', item_type: 'text', is_required: true },
          { label: 'State', item_type: 'dropdown', is_required: true, options: ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'] },
          { label: 'ZIP Code', item_type: 'text', is_required: true },
          { label: 'NAICS Code', item_type: 'text' },
          { label: 'Number of Employees', item_type: 'number' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Areas Inspected', item_type: 'textarea', is_required: true },
        ],
      },
      {
        name: 'Walking/Working Surfaces (1910 Subpart D)',
        items: [
          { label: 'Floors Clean and Dry', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Floor Openings Guarded', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Aisles Clear (28" minimum)', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Guardrails on Platforms (42")', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Fixed Ladders in Good Condition', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Stairways with Handrails', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Slip/Trip Hazards', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Walking Surface Photo', item_type: 'photo' },
          { label: 'Walking Surface Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Means of Egress (1910 Subpart E)',
        items: [
          { label: 'Exit Routes Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Exit Routes Unobstructed', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Exit Signs Illuminated', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Emergency Lighting Working', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Exits Open Outward', item_type: 'pass_fail' },
          { label: 'Exit Doors Unlocked During Work', item_type: 'pass_fail', is_required: true },
          { label: 'Fire Exit Diagram Posted', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Emergency Action Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Egress Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Electrical (1910 Subpart S)',
        items: [
          { label: 'Electrical Panels Accessible (36" clearance)', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Panels Properly Labeled', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Missing Knockouts', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'GFCI Where Required', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Damaged Cords/Plugs', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'No Improper Extension Cord Use', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Electrical Equipment Grounded', item_type: 'pass_fail' },
          { label: 'Lockout/Tagout Program', item_type: 'pass_fail', is_required: true },
          { label: 'Electrical Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Fire Protection (1910 Subpart L)',
        items: [
          { label: 'Fire Extinguishers Present', item_type: 'pass_fail', is_required: true },
          { label: 'Extinguishers Accessible', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Extinguishers Inspected Monthly', item_type: 'pass_fail' },
          { label: 'Extinguishers Serviced Annually', item_type: 'pass_fail' },
          { label: 'Sprinkler System (if required)', item_type: 'pass_fail' },
          { label: 'Sprinkler Heads Unobstructed (18")', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Fire Alarm System Working', item_type: 'pass_fail' },
          { label: 'Fire Drill Conducted Annually', item_type: 'pass_fail' },
          { label: 'Fire Protection Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Personal Protective Equipment (1910 Subpart I)',
        items: [
          { label: 'Hazard Assessment Completed', item_type: 'pass_fail', is_required: true },
          { label: 'PPE Provided at No Cost', item_type: 'pass_fail', is_required: true },
          { label: 'Eye/Face Protection', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Head Protection', item_type: 'pass_fail' },
          { label: 'Foot Protection', item_type: 'pass_fail' },
          { label: 'Hand Protection', item_type: 'pass_fail' },
          { label: 'Respiratory Protection Program', item_type: 'pass_fail' },
          { label: 'Hearing Protection', item_type: 'pass_fail' },
          { label: 'PPE Training Documented', item_type: 'pass_fail', is_required: true },
          { label: 'PPE Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Hazard Communication (1910.1200)',
        items: [
          { label: 'Written HazCom Program', item_type: 'pass_fail', is_required: true },
          { label: 'SDS Readily Accessible', item_type: 'pass_fail', is_required: true },
          { label: 'Containers Properly Labeled', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'GHS Labels on Containers', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Secondary Container Labels', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Employee Training Documented', item_type: 'pass_fail', is_required: true },
          { label: 'HazCom Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Machine Guarding (1910 Subpart O)',
        items: [
          { label: 'Point of Operation Guards', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Nip Point Guards', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Rotating Part Guards', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Flying Chip/Spark Guards', item_type: 'pass_fail' },
          { label: 'Emergency Stops Accessible', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Anchoring Secure', item_type: 'pass_fail' },
          { label: 'Machine Guarding Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Medical/First Aid (1910.151)',
        items: [
          { label: 'First Aid Kit Available', item_type: 'pass_fail', is_required: true },
          { label: 'First Aid Kit Stocked', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'AED Available (if required)', item_type: 'pass_fail' },
          { label: 'Eye Wash Station (if required)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Eye Wash Flushed Weekly', item_type: 'pass_fail' },
          { label: 'Emergency Shower (if required)', item_type: 'pass_fail' },
          { label: 'Trained First Aid Personnel', item_type: 'pass_fail' },
          { label: 'Medical Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Recordkeeping (1904)',
        items: [
          { label: 'OSHA 300 Log Maintained', item_type: 'pass_fail', is_required: true },
          { label: 'OSHA 300A Posted (Feb-Apr)', item_type: 'pass_fail' },
          { label: 'OSHA Poster Displayed', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Incident Reports Completed', item_type: 'pass_fail' },
          { label: 'Recordkeeping Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Total Violations Found', item_type: 'number', is_required: true },
          { label: 'Serious Violations', item_type: 'number' },
          { label: 'Other-Than-Serious Violations', item_type: 'number' },
          { label: 'Repeat Violations', item_type: 'number' },
          { label: 'Willful Violations', item_type: 'number' },
          { label: 'Corrective Actions Required', item_type: 'textarea' },
          { label: 'Abatement Deadline', item_type: 'date' },
          { label: 'Overall Compliance Status', item_type: 'dropdown', is_required: true, options: ['Compliant', 'Minor Issues', 'Significant Issues', 'Non-Compliant'] },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Facility Representative Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 2. OSHA CONSTRUCTION SAFETY (29 CFR 1926)
  // ============================================
  {
    id: 'compliance-us-osha-construction',
    name: 'OSHA Construction Site Safety Inspection',
    description: 'Construction site safety inspection per OSHA 29 CFR 1926 Construction Standards',
    record_type_id: 'compliance-us',
    sections: [
      {
        name: 'Project Information',
        items: [
          { label: 'Project Name', item_type: 'text', is_required: true },
          { label: 'Project Address', item_type: 'text', is_required: true },
          { label: 'City, State, ZIP', item_type: 'text', is_required: true },
          { label: 'General Contractor', item_type: 'text', is_required: true },
          { label: 'Competent Person On Site', item_type: 'text', is_required: true },
          { label: 'Number of Workers', item_type: 'number' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Weather Conditions', item_type: 'dropdown', options: ['Clear', 'Cloudy', 'Rain', 'Snow', 'High Wind'] },
          { label: 'Site Photo', item_type: 'photo', is_required: true },
        ],
      },
      {
        name: 'General Safety and Health (1926.20-35)',
        items: [
          { label: 'Site-Specific Safety Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Safety Meetings Documented', item_type: 'pass_fail' },
          { label: 'First Aid Kit On Site', item_type: 'pass_fail', is_required: true },
          { label: 'Emergency Contact Numbers Posted', item_type: 'pass_fail' },
          { label: 'Fire Extinguisher Available', item_type: 'pass_fail', is_required: true },
          { label: 'Housekeeping Adequate', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Sanitation Facilities', item_type: 'pass_fail', is_required: true },
          { label: 'Drinking Water Available', item_type: 'pass_fail', is_required: true },
          { label: 'General Safety Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Personal Protective Equipment (1926 Subpart E)',
        items: [
          { label: 'Hard Hats Worn', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Safety Glasses/Goggles', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'High-Visibility Vests', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Safety Footwear', item_type: 'pass_fail' },
          { label: 'Gloves (as needed)', item_type: 'pass_fail' },
          { label: 'Fall Protection (6ft+)', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Hearing Protection (85dB+)', item_type: 'pass_fail' },
          { label: 'Respiratory Protection', item_type: 'pass_fail' },
          { label: 'PPE Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Fall Protection (1926 Subpart M)',
        items: [
          { label: 'Fall Protection Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Guardrails Installed (6ft+)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Guardrail Height (42")', item_type: 'pass_fail' },
          { label: 'Toe Boards Where Required', item_type: 'pass_fail' },
          { label: 'Safety Nets (if used)', item_type: 'pass_fail' },
          { label: 'Personal Fall Arrest Systems', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Harness/Lanyard Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Anchor Points Adequate', item_type: 'pass_fail' },
          { label: 'Hole Covers Secure', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Leading Edge Protection', item_type: 'pass_fail' },
          { label: 'Fall Protection Training', item_type: 'pass_fail', is_required: true },
          { label: 'Fall Protection Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Scaffolding (1926 Subpart L)',
        items: [
          { label: 'Scaffolding Present', item_type: 'yes_no' },
          { label: 'Scaffold Photo', item_type: 'photo' },
          { label: 'Competent Person Inspected', item_type: 'pass_fail' },
          { label: 'Base Plates/Mudsills', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Guardrails Complete', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Planking Condition', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Full Width Planks', item_type: 'pass_fail' },
          { label: 'Access Ladder/Stair', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Cross Bracing', item_type: 'pass_fail' },
          { label: 'Load Capacity Displayed', item_type: 'pass_fail' },
          { label: 'Scaffolding Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Ladders (1926 Subpart X)',
        items: [
          { label: 'Ladders in Use', item_type: 'yes_no' },
          { label: 'Ladder Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Proper Angle (4:1)', item_type: 'pass_fail' },
          { label: 'Extends 3ft Above Landing', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Secured at Top or Bottom', item_type: 'pass_fail' },
          { label: 'Non-Slip Feet', item_type: 'pass_fail' },
          { label: 'Metal Ladder Near Electric', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Ladder Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Excavations (1926 Subpart P)',
        items: [
          { label: 'Excavation Present', item_type: 'yes_no' },
          { label: 'Excavation Photo', item_type: 'photo' },
          { label: 'Competent Person Inspection', item_type: 'pass_fail' },
          { label: 'Soil Classification Done', item_type: 'pass_fail' },
          { label: 'Protective System (5ft+)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Sloping/Benching Adequate', item_type: 'pass_fail' },
          { label: 'Shoring/Shielding', item_type: 'pass_fail' },
          { label: 'Spoil Pile 2ft from Edge', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Access/Egress (25ft)', item_type: 'pass_fail' },
          { label: 'Water Accumulation Control', item_type: 'pass_fail' },
          { label: 'Excavation Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Electrical (1926 Subpart K)',
        items: [
          { label: 'GFCI Protection', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Assured Grounding Program', item_type: 'pass_fail' },
          { label: 'Temporary Wiring Safe', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Power Lines Identified', item_type: 'pass_fail' },
          { label: '10ft Clearance from Lines', item_type: 'pass_fail' },
          { label: 'Lockout/Tagout Followed', item_type: 'pass_fail' },
          { label: 'Electrical Panel Clearance', item_type: 'pass_fail' },
          { label: 'Electrical Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Stop Work Order Issued', item_type: 'yes_no' },
          { label: 'Imminent Danger Found', item_type: 'yes_no' },
          { label: 'Total Violations', item_type: 'number', is_required: true },
          { label: 'Corrective Actions', item_type: 'textarea' },
          { label: 'Follow-up Required', item_type: 'yes_no' },
          { label: 'Follow-up Date', item_type: 'date' },
          { label: 'Overall Rating', item_type: 'dropdown', is_required: true, options: ['Compliant', 'Minor Issues', 'Major Issues', 'Stop Work'] },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Site Supervisor Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 3. FDA FOOD FACILITY INSPECTION (21 CFR 117)
  // ============================================
  {
    id: 'compliance-us-fda-food',
    name: 'FDA Food Facility Inspection',
    description: 'Food facility inspection per FDA 21 CFR 117 Current Good Manufacturing Practice',
    record_type_id: 'compliance-us',
    sections: [
      {
        name: 'Facility Information',
        items: [
          { label: 'Facility Name', item_type: 'text', is_required: true },
          { label: 'FDA Registration Number', item_type: 'text', is_required: true },
          { label: 'Facility Address', item_type: 'text', is_required: true },
          { label: 'City, State, ZIP', item_type: 'text', is_required: true },
          { label: 'Facility Type', item_type: 'dropdown', is_required: true, options: ['Manufacturer', 'Processor', 'Packer', 'Warehouse', 'Distribution Center'] },
          { label: 'Products Manufactured', item_type: 'textarea' },
          { label: 'Preventive Controls Qualified Individual', item_type: 'text', is_required: true },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
        ],
      },
      {
        name: 'Personnel (21 CFR 117.10)',
        items: [
          { label: 'Employees Free of Illness', item_type: 'pass_fail', is_required: true },
          { label: 'Clean Outer Garments', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Hair Restraints Used', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Jewelry Removed/Covered', item_type: 'pass_fail' },
          { label: 'Handwashing Practiced', item_type: 'pass_fail', is_required: true },
          { label: 'Gloves Changed Appropriately', item_type: 'pass_fail' },
          { label: 'Training Records Available', item_type: 'pass_fail', is_required: true },
          { label: 'Personnel Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Plant and Grounds (21 CFR 117.20)',
        items: [
          { label: 'Grounds Maintained', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Standing Water', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Pest Harborage Controlled', item_type: 'pass_fail' },
          { label: 'Building Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Adequate Space for Operations', item_type: 'pass_fail' },
          { label: 'Separation of Operations', item_type: 'pass_fail' },
          { label: 'Floors Cleanable', item_type: 'pass_fail' },
          { label: 'Walls and Ceilings Cleanable', item_type: 'pass_fail' },
          { label: 'Adequate Lighting', item_type: 'pass_fail' },
          { label: 'Light Shields/Covers', item_type: 'pass_fail' },
          { label: 'Adequate Ventilation', item_type: 'pass_fail' },
          { label: 'Plant Photo', item_type: 'photo' },
          { label: 'Plant Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Sanitary Operations (21 CFR 117.35)',
        items: [
          { label: 'Cleaning Chemicals Properly Stored', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Cleaning Chemicals Labeled', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Master Sanitation Schedule', item_type: 'pass_fail', is_required: true },
          { label: 'Sanitation Records Maintained', item_type: 'pass_fail' },
          { label: 'Pest Control Program', item_type: 'pass_fail', is_required: true },
          { label: 'No Evidence of Pests', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Sanitation Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Sanitary Facilities (21 CFR 117.37)',
        items: [
          { label: 'Potable Water Supply', item_type: 'pass_fail', is_required: true },
          { label: 'Water Testing Records', item_type: 'pass_fail' },
          { label: 'Adequate Plumbing', item_type: 'pass_fail' },
          { label: 'No Cross-Connections', item_type: 'pass_fail' },
          { label: 'Sewage Disposal Adequate', item_type: 'pass_fail' },
          { label: 'Toilet Facilities Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Handwashing Stations', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Hot/Cold Running Water', item_type: 'pass_fail' },
          { label: 'Soap and Sanitizer', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Single-Use Towels/Dryers', item_type: 'pass_fail' },
          { label: 'Sanitary Facilities Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Equipment and Utensils (21 CFR 117.40)',
        items: [
          { label: 'Food Contact Surfaces Clean', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Equipment in Good Repair', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Equipment Properly Maintained', item_type: 'pass_fail' },
          { label: 'Seams Smoothly Bonded', item_type: 'pass_fail' },
          { label: 'No Accumulation in Equipment', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Holding/Conveying Equipment', item_type: 'pass_fail' },
          { label: 'Compressed Air Clean', item_type: 'pass_fail' },
          { label: 'Equipment Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Process Controls (21 CFR 117.80)',
        items: [
          { label: 'Raw Materials Inspected', item_type: 'pass_fail', is_required: true },
          { label: 'Raw Materials Properly Stored', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Temperature Controls Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Refrigeration (≤40°F)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Refrigerator Temperature (°F)', item_type: 'temperature' },
          { label: 'Freezer Temperature (°F)', item_type: 'temperature' },
          { label: 'Time/Temperature Records', item_type: 'pass_fail' },
          { label: 'Allergen Controls', item_type: 'pass_fail', is_required: true },
          { label: 'Allergen Labeling Correct', item_type: 'pass_fail', is_required: true },
          { label: 'Process Controls Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Food Safety Plan (21 CFR 117 Subpart C)',
        items: [
          { label: 'Written Food Safety Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Hazard Analysis Completed', item_type: 'pass_fail', is_required: true },
          { label: 'Preventive Controls Identified', item_type: 'pass_fail', is_required: true },
          { label: 'Monitoring Procedures', item_type: 'pass_fail', is_required: true },
          { label: 'Corrective Action Procedures', item_type: 'pass_fail', is_required: true },
          { label: 'Verification Procedures', item_type: 'pass_fail', is_required: true },
          { label: 'Recall Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Records Maintained', item_type: 'pass_fail', is_required: true },
          { label: 'Food Safety Plan Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Form FDA 483 Issued', item_type: 'yes_no' },
          { label: 'Number of Observations', item_type: 'number' },
          { label: 'Critical Observations', item_type: 'number' },
          { label: 'Observations Details', item_type: 'textarea' },
          { label: 'Corrective Actions Required', item_type: 'textarea' },
          { label: 'Follow-up Inspection Required', item_type: 'yes_no' },
          { label: 'Overall Assessment', item_type: 'dropdown', is_required: true, options: ['No Action Indicated', 'Voluntary Action Indicated', 'Official Action Indicated'] },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Facility Representative Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 4. ADA ACCESSIBILITY INSPECTION
  // ============================================
  {
    id: 'compliance-us-ada',
    name: 'ADA Accessibility Compliance Inspection',
    description: 'Americans with Disabilities Act accessibility compliance inspection',
    record_type_id: 'compliance-us',
    sections: [
      {
        name: 'Facility Information',
        items: [
          { label: 'Facility Name', item_type: 'text', is_required: true },
          { label: 'Facility Address', item_type: 'text', is_required: true },
          { label: 'City, State, ZIP', item_type: 'text', is_required: true },
          { label: 'Facility Type', item_type: 'dropdown', is_required: true, options: ['Commercial', 'Retail', 'Restaurant', 'Hotel', 'Medical', 'Office', 'Educational', 'Government', 'Other'] },
          { label: 'Year Built', item_type: 'number' },
          { label: 'Last Renovation', item_type: 'number' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
        ],
      },
      {
        name: 'Parking',
        items: [
          { label: 'Accessible Parking Provided', item_type: 'pass_fail', is_required: true },
          { label: 'Number of Accessible Spaces', item_type: 'number' },
          { label: 'Accessible Space Photo', item_type: 'photo' },
          { label: 'Van Accessible Space', item_type: 'pass_fail' },
          { label: 'Space Width (96" min)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Access Aisle Width (60" min)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'ISA Signage (60" high)', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Surface Slope (≤2%)', item_type: 'pass_fail' },
          { label: 'Accessible Route from Parking', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Parking Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Accessible Route',
        items: [
          { label: 'Route Minimum Width (36")', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Route Photo', item_type: 'photo' },
          { label: 'Surface Firm and Stable', item_type: 'pass_fail' },
          { label: 'Running Slope (≤5%)', item_type: 'pass_fail' },
          { label: 'Cross Slope (≤2%)', item_type: 'pass_fail' },
          { label: 'No Protruding Objects', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Changes in Level (≤1/4")', item_type: 'pass_fail' },
          { label: 'Grating Openings (≤1/2")', item_type: 'pass_fail' },
          { label: 'Route Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Ramps',
        items: [
          { label: 'Ramps Present', item_type: 'yes_no' },
          { label: 'Ramp Photo', item_type: 'photo' },
          { label: 'Ramp Slope (≤8.33%)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Ramp Width (36" min)', item_type: 'pass_fail' },
          { label: 'Handrails Both Sides', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Handrail Height (34-38")', item_type: 'pass_fail' },
          { label: 'Handrail Extensions (12")', item_type: 'pass_fail' },
          { label: 'Level Landings', item_type: 'pass_fail' },
          { label: 'Edge Protection', item_type: 'pass_fail' },
          { label: 'Ramp Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Entrances and Doors',
        items: [
          { label: 'Accessible Entrance Provided', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Entrance Photo', item_type: 'photo' },
          { label: 'ISA Signage at Entrance', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Door Clear Width (32" min)', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Door Hardware Operable', item_type: 'pass_fail' },
          { label: 'Lever/Loop Handle (no twist)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Closing Speed (5 sec min)', item_type: 'pass_fail' },
          { label: 'Opening Force (≤5 lbs)', item_type: 'pass_fail' },
          { label: 'Maneuvering Clearance', item_type: 'pass_fail' },
          { label: 'Threshold Height (≤1/2")', item_type: 'pass_fail' },
          { label: 'Door Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Elevators',
        items: [
          { label: 'Elevator Present', item_type: 'yes_no' },
          { label: 'Elevator Photo', item_type: 'photo' },
          { label: 'Car Size (54"x36" min)', item_type: 'pass_fail' },
          { label: 'Door Width (32" min)', item_type: 'pass_fail' },
          { label: 'Call Buttons (42" high max)', item_type: 'pass_fail' },
          { label: 'Control Panel Height (48" max)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Braille/Raised Characters', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Audible Signals', item_type: 'pass_fail' },
          { label: 'Emergency Communication', item_type: 'pass_fail' },
          { label: 'Elevator Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Restrooms',
        items: [
          { label: 'Accessible Restroom Provided', item_type: 'pass_fail', is_required: true },
          { label: 'Restroom Photo', item_type: 'photo' },
          { label: 'ISA Signage', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Door Width (32" min)', item_type: 'pass_fail' },
          { label: 'Clear Floor Space (60" turn)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Toilet Height (17-19")', item_type: 'pass_fail' },
          { label: 'Grab Bars Installed', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Side Grab Bar (42")', item_type: 'pass_fail' },
          { label: 'Rear Grab Bar (36")', item_type: 'pass_fail' },
          { label: 'Lavatory Knee Clearance', item_type: 'pass_fail' },
          { label: 'Faucet Operable (no twist)', item_type: 'pass_fail' },
          { label: 'Mirror Height (40" max)', item_type: 'pass_fail' },
          { label: 'Accessories Reach Range', item_type: 'pass_fail' },
          { label: 'Restroom Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Service Areas',
        items: [
          { label: 'Service Counter Height (36" max)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Service Counter Photo', item_type: 'photo' },
          { label: 'Accessible Queue Space', item_type: 'pass_fail' },
          { label: 'Point of Sale Accessible', item_type: 'pass_fail' },
          { label: 'Dining Surfaces (28-34")', item_type: 'pass_fail' },
          { label: 'Knee Clearance (27" min)', item_type: 'pass_fail' },
          { label: '5% Accessible Tables', item_type: 'pass_fail' },
          { label: 'Service Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Total Barriers Identified', item_type: 'number', is_required: true },
          { label: 'High Priority Barriers', item_type: 'number' },
          { label: 'Barrier Details', item_type: 'textarea' },
          { label: 'Recommended Modifications', item_type: 'textarea' },
          { label: 'Overall Compliance', item_type: 'dropdown', is_required: true, options: ['Compliant', 'Substantially Compliant', 'Partial Compliance', 'Non-Compliant'] },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Owner/Manager Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 5. EPA HAZARDOUS WASTE INSPECTION (40 CFR 262-265)
  // ============================================
  {
    id: 'compliance-us-epa-hazwaste',
    name: 'EPA Hazardous Waste Compliance Inspection',
    description: 'Hazardous waste management inspection per EPA RCRA regulations',
    record_type_id: 'compliance-us',
    sections: [
      {
        name: 'Facility Information',
        items: [
          { label: 'Facility Name', item_type: 'text', is_required: true },
          { label: 'EPA ID Number', item_type: 'text', is_required: true },
          { label: 'Facility Address', item_type: 'text', is_required: true },
          { label: 'City, State, ZIP', item_type: 'text', is_required: true },
          { label: 'Generator Status', item_type: 'dropdown', is_required: true, options: ['Large Quantity Generator (LQG)', 'Small Quantity Generator (SQG)', 'Very Small Quantity Generator (VSQG)'] },
          { label: 'Waste Types Generated', item_type: 'multi_select', options: ['Ignitable (D001)', 'Corrosive (D002)', 'Reactive (D003)', 'Toxic (D004-D043)', 'Listed (F, K, P, U)', 'Universal Waste'] },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
        ],
      },
      {
        name: 'Waste Identification (40 CFR 262.11)',
        items: [
          { label: 'Hazardous Waste Determination Made', item_type: 'pass_fail', is_required: true },
          { label: 'Determination Records Maintained', item_type: 'pass_fail', is_required: true },
          { label: 'Waste Characterization Complete', item_type: 'pass_fail' },
          { label: 'EPA Waste Codes Assigned', item_type: 'pass_fail', is_required: true },
          { label: 'SDS Available for Waste', item_type: 'pass_fail' },
          { label: 'Waste ID Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Container Management (40 CFR 262.16/265.173)',
        items: [
          { label: 'Containers in Good Condition', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Container Storage Area Photo', item_type: 'photo', is_required: true },
          { label: 'Containers Closed', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Compatible with Contents', item_type: 'pass_fail' },
          { label: 'Proper Labeling "Hazardous Waste"', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Accumulation Start Date Marked', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'EPA Waste Code on Label', item_type: 'pass_fail' },
          { label: 'Generator Info on Label', item_type: 'pass_fail' },
          { label: 'Container Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Satellite Accumulation (40 CFR 262.15)',
        items: [
          { label: 'Satellite Accumulation Areas', item_type: 'yes_no' },
          { label: 'SAA Photo', item_type: 'photo' },
          { label: 'At Point of Generation', item_type: 'pass_fail' },
          { label: 'Under Control of Operator', item_type: 'pass_fail' },
          { label: '55-Gallon Limit (HW)', item_type: 'pass_fail' },
          { label: '1-Quart Limit (Acute HW)', item_type: 'pass_fail' },
          { label: 'Containers Marked "Hazardous Waste"', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Moved Within 3 Days of Exceeding', item_type: 'pass_fail' },
          { label: 'SAA Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Storage Area Requirements',
        items: [
          { label: 'Secondary Containment', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Containment Capacity Adequate', item_type: 'pass_fail' },
          { label: 'Aisle Space (≥2 ft)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Incompatible Waste Separated', item_type: 'pass_fail' },
          { label: 'Fire Protection Equipment', item_type: 'pass_fail' },
          { label: 'Spill Control Equipment', item_type: 'pass_fail' },
          { label: 'Communication Equipment', item_type: 'pass_fail' },
          { label: 'Weekly Inspections Documented', item_type: 'pass_fail', is_required: true },
          { label: 'Storage Area Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Time Limits',
        items: [
          { label: 'Accumulation Time Tracked', item_type: 'pass_fail', is_required: true },
          { label: 'Within Time Limits (LQG: 90 days)', item_type: 'pass_fail', is_required: true },
          { label: 'Within Time Limits (SQG: 180/270 days)', item_type: 'pass_fail' },
          { label: 'Extension Documentation (if any)', item_type: 'pass_fail' },
          { label: 'Time Limit Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Manifests and Records (40 CFR 262.20-23)',
        items: [
          { label: 'Uniform Hazardous Waste Manifest', item_type: 'pass_fail', is_required: true },
          { label: 'Manifest Completed Correctly', item_type: 'pass_fail' },
          { label: 'EPA ID on Manifest', item_type: 'pass_fail' },
          { label: 'Manifest Copies Received Back', item_type: 'pass_fail' },
          { label: 'Exception Reports Filed (if needed)', item_type: 'pass_fail' },
          { label: 'Biennial Report Submitted', item_type: 'pass_fail' },
          { label: 'Records Retained (3 years)', item_type: 'pass_fail', is_required: true },
          { label: 'Land Disposal Restrictions Met', item_type: 'pass_fail' },
          { label: 'Records Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Training and Preparedness',
        items: [
          { label: 'Personnel Trained', item_type: 'pass_fail', is_required: true },
          { label: 'Training Records Maintained', item_type: 'pass_fail', is_required: true },
          { label: 'Annual Refresher Training', item_type: 'pass_fail' },
          { label: 'Contingency Plan (LQG)', item_type: 'pass_fail' },
          { label: 'Emergency Coordinator Designated', item_type: 'pass_fail' },
          { label: 'Emergency Equipment Available', item_type: 'pass_fail' },
          { label: 'Arrangements with Local Authorities', item_type: 'pass_fail' },
          { label: 'Training Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Violations Found', item_type: 'number', is_required: true },
          { label: 'Class I Violations', item_type: 'number' },
          { label: 'Class II Violations', item_type: 'number' },
          { label: 'Violation Details', item_type: 'textarea' },
          { label: 'Corrective Actions Required', item_type: 'textarea' },
          { label: 'Compliance Deadline', item_type: 'date' },
          { label: 'Follow-up Inspection', item_type: 'yes_no' },
          { label: 'Overall Status', item_type: 'dropdown', is_required: true, options: ['In Compliance', 'Minor Violations', 'Significant Violations', 'Non-Compliant'] },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Facility Representative Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 6. NFPA LIFE SAFETY CODE INSPECTION (NFPA 101)
  // ============================================
  {
    id: 'compliance-us-nfpa-lifesafety',
    name: 'NFPA 101 Life Safety Code Inspection',
    description: 'Life safety code compliance inspection per NFPA 101',
    record_type_id: 'compliance-us',
    sections: [
      {
        name: 'Building Information',
        items: [
          { label: 'Building Name', item_type: 'text', is_required: true },
          { label: 'Building Address', item_type: 'text', is_required: true },
          { label: 'City, State, ZIP', item_type: 'text', is_required: true },
          { label: 'Occupancy Classification', item_type: 'dropdown', is_required: true, options: ['Assembly', 'Educational', 'Healthcare', 'Ambulatory Healthcare', 'Detention/Correctional', 'Residential', 'Mercantile', 'Business', 'Industrial', 'Storage'] },
          { label: 'Construction Type', item_type: 'dropdown', options: ['Type I', 'Type II', 'Type III', 'Type IV', 'Type V'] },
          { label: 'Number of Stories', item_type: 'number' },
          { label: 'Sprinkler Protected', item_type: 'yes_no' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'AHJ', item_type: 'text' },
        ],
      },
      {
        name: 'Means of Egress - General',
        items: [
          { label: 'Building Photo', item_type: 'photo' },
          { label: 'Number of Exits', item_type: 'number', is_required: true },
          { label: 'Exits Adequate for Occupant Load', item_type: 'pass_fail', is_required: true },
          { label: 'Exit Access Travel Distance', item_type: 'pass_fail', is_required: true },
          { label: 'Common Path of Travel', item_type: 'pass_fail' },
          { label: 'Dead-End Corridors', item_type: 'pass_fail' },
          { label: 'Exit Separation (1/2 diagonal)', item_type: 'pass_fail' },
          { label: 'Egress Width Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Egress Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Exit Access',
        items: [
          { label: 'Corridors Clear', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Corridor Width (44" min)', item_type: 'pass_fail' },
          { label: 'Corridor Walls Rated', item_type: 'pass_fail' },
          { label: 'Doors Swing in Direction of Travel', item_type: 'pass_fail' },
          { label: 'Door Hardware Compliant', item_type: 'pass_fail' },
          { label: 'Self-Closing Devices Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Door Obstructions', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Exit Access Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Exits',
        items: [
          { label: 'Exit Doors Open Freely', item_type: 'pass_fail', is_required: true },
          { label: 'Exit Photo', item_type: 'photo' },
          { label: 'Panic Hardware Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Special Knowledge to Exit', item_type: 'pass_fail' },
          { label: 'No Key Required to Exit', item_type: 'pass_fail', is_required: true },
          { label: 'Delayed Egress Locks Compliant', item_type: 'pass_fail' },
          { label: 'Exit Stair Enclosures Rated', item_type: 'pass_fail' },
          { label: 'Stair Width Adequate', item_type: 'pass_fail' },
          { label: 'Handrails Both Sides', item_type: 'pass_fail' },
          { label: 'Stair Landings Adequate', item_type: 'pass_fail' },
          { label: 'Exit Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Exit Discharge',
        items: [
          { label: 'Exits Discharge Outside', item_type: 'pass_fail', is_required: true },
          { label: 'Exit Discharge Clear', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Level of Discharge Clear', item_type: 'pass_fail' },
          { label: 'Path to Public Way', item_type: 'pass_fail' },
          { label: 'Exit Discharge Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Illumination and Marking',
        items: [
          { label: 'Exit Signs Visible', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Exit Sign Photo', item_type: 'photo' },
          { label: 'Exit Signs Illuminated', item_type: 'pass_fail', is_required: true },
          { label: 'Directional Signs Where Needed', item_type: 'pass_fail' },
          { label: 'Egress Path Illumination (1 fc)', item_type: 'pass_fail', is_required: true },
          { label: 'Emergency Lighting Working', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Emergency Power (90 min)', item_type: 'pass_fail' },
          { label: 'Monthly Testing Documented', item_type: 'pass_fail' },
          { label: 'Annual Testing Documented', item_type: 'pass_fail' },
          { label: 'Illumination Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Fire Alarm and Detection',
        items: [
          { label: 'Fire Alarm System Installed', item_type: 'pass_fail', is_required: true },
          { label: 'Fire Alarm Panel Photo', item_type: 'photo' },
          { label: 'Manual Pull Stations', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Audible Notification', item_type: 'pass_fail', is_required: true },
          { label: 'Visual Notification (ADA)', item_type: 'pass_fail' },
          { label: 'Smoke Detectors Working', item_type: 'pass_fail' },
          { label: 'Annual Inspection Current', item_type: 'pass_fail' },
          { label: 'System Monitored', item_type: 'pass_fail' },
          { label: 'Fire Alarm Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Fire Suppression',
        items: [
          { label: 'Sprinkler System Installed', item_type: 'yes_no' },
          { label: 'Sprinkler Photo', item_type: 'photo' },
          { label: 'Sprinkler Coverage Complete', item_type: 'pass_fail' },
          { label: 'Sprinkler Clearance (18")', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Sprinkler Inspection Current', item_type: 'pass_fail' },
          { label: 'Fire Extinguishers Provided', item_type: 'pass_fail', is_required: true },
          { label: 'Extinguisher Placement Correct', item_type: 'pass_fail' },
          { label: 'Extinguisher Inspections Current', item_type: 'pass_fail' },
          { label: 'Suppression Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Total Deficiencies', item_type: 'number', is_required: true },
          { label: 'Life Safety Deficiencies', item_type: 'number' },
          { label: 'Deficiency Details', item_type: 'textarea' },
          { label: 'Corrective Actions', item_type: 'textarea' },
          { label: 'Re-inspection Required', item_type: 'yes_no' },
          { label: 'Re-inspection Date', item_type: 'date' },
          { label: 'Overall Status', item_type: 'dropdown', is_required: true, options: ['Approved', 'Approved with Conditions', 'Disapproved', 'Pending'] },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Building Owner/Manager Signature', item_type: 'signature' },
        ],
      },
    ],
  },
];
