/**
 * Australian Regulatory Compliance Templates
 * 4 templates for Australian-specific regulatory inspections
 */

import { TemplateDefinition } from './types';

export const COMPLIANCE_AU_TEMPLATES: TemplateDefinition[] = [
  // ============================================
  // 1. WHS WORKPLACE INSPECTION (Model WHS Act)
  // ============================================
  {
    id: 'compliance-au-whs',
    name: 'Australian WHS Workplace Inspection',
    description: 'Work Health and Safety inspection per Model WHS Act and Regulations',
    record_type_id: 'compliance-au',
    sections: [
      {
        name: 'Workplace Information',
        items: [
          { label: 'PCBU Name', item_type: 'text', is_required: true, help_text: 'Person Conducting Business or Undertaking' },
          { label: 'Workplace Address', item_type: 'text', is_required: true },
          { label: 'State/Territory', item_type: 'select', is_required: true, options: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'ACT', 'NT'] },
          { label: 'Industry', item_type: 'select', options: ['Construction', 'Manufacturing', 'Mining', 'Agriculture', 'Healthcare', 'Retail', 'Office', 'Transport', 'Other'] },
          { label: 'Number of Workers', item_type: 'number' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'HSR Present', item_type: 'yes_no', help_text: 'Health and Safety Representative' },
          { label: 'HSR Name', item_type: 'text' },
        ],
      },
      {
        name: 'Duties and Consultation',
        items: [
          { label: 'Primary Duty of Care Understood', item_type: 'pass_fail', is_required: true },
          { label: 'Health and Safety Policy', item_type: 'pass_fail' },
          { label: 'Policy Displayed', item_type: 'pass_fail' },
          { label: 'Worker Consultation Occurring', item_type: 'pass_fail', is_required: true },
          { label: 'HSR Elected (if requested)', item_type: 'pass_fail' },
          { label: 'HSC Established (if applicable)', item_type: 'pass_fail', help_text: 'Health and Safety Committee' },
          { label: 'Consultation Records', item_type: 'pass_fail' },
          { label: 'Issue Resolution Procedure', item_type: 'pass_fail' },
          { label: 'Duties Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Risk Management',
        items: [
          { label: 'Hazards Identified', item_type: 'pass_fail', is_required: true },
          { label: 'Risk Assessments Conducted', item_type: 'pass_fail', is_required: true },
          { label: 'Risk Assessments Documented', item_type: 'pass_fail' },
          { label: 'Hierarchy of Controls Applied', item_type: 'pass_fail', is_required: true },
          { label: 'Control Measures Implemented', item_type: 'pass_fail', is_required: true },
          { label: 'Controls Reviewed Regularly', item_type: 'pass_fail' },
          { label: 'High Risk Work Licensed', item_type: 'pass_fail' },
          { label: 'SWMS for High Risk Construction', item_type: 'pass_fail', help_text: 'Safe Work Method Statements' },
          { label: 'Risk Management Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Work Environment',
        items: [
          { label: 'Workplace Photo', item_type: 'photo' },
          { label: 'Housekeeping Adequate', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Floors Safe (no slips/trips)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Lighting Adequate', item_type: 'pass_fail' },
          { label: 'Ventilation Adequate', item_type: 'pass_fail' },
          { label: 'Temperature Reasonable', item_type: 'pass_fail' },
          { label: 'Noise Levels Acceptable', item_type: 'pass_fail' },
          { label: 'Amenities Provided', item_type: 'pass_fail', is_required: true },
          { label: 'Toilets Clean and Adequate', item_type: 'pass_fail' },
          { label: 'Drinking Water Available', item_type: 'pass_fail', is_required: true },
          { label: 'Eating Facilities', item_type: 'pass_fail' },
          { label: 'Environment Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Plant and Equipment',
        items: [
          { label: 'Plant Risk Assessments', item_type: 'pass_fail' },
          { label: 'Guards in Place', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Emergency Stops Working', item_type: 'pass_fail', is_required: true },
          { label: 'Maintenance Records', item_type: 'pass_fail' },
          { label: 'Plant Registered (if required)', item_type: 'pass_fail' },
          { label: 'Operators Licensed/Competent', item_type: 'pass_fail' },
          { label: 'Electrical Equipment Tested', item_type: 'pass_fail' },
          { label: 'Test Tags Current', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'RCDs Installed', item_type: 'pass_fail' },
          { label: 'Plant Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Hazardous Chemicals',
        items: [
          { label: 'Chemical Register Maintained', item_type: 'pass_fail' },
          { label: 'SDS Available (5 years)', item_type: 'pass_fail' },
          { label: 'SDS Accessible to Workers', item_type: 'pass_fail' },
          { label: 'Chemicals Labelled (GHS)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Chemicals Stored Safely', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Incompatible Chemicals Separated', item_type: 'pass_fail' },
          { label: 'Health Monitoring (if required)', item_type: 'pass_fail' },
          { label: 'Spill Kits Available', item_type: 'pass_fail' },
          { label: 'Chemical Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Emergency Preparedness',
        items: [
          { label: 'Emergency Plan Developed', item_type: 'pass_fail', is_required: true },
          { label: 'Emergency Procedures Displayed', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Emergency Warden Appointed', item_type: 'pass_fail' },
          { label: 'Evacuation Drills Conducted', item_type: 'pass_fail' },
          { label: 'Assembly Areas Identified', item_type: 'pass_fail' },
          { label: 'First Aid Kit Stocked', item_type: 'pass_fail', is_required: true },
          { label: 'First Aider Available', item_type: 'pass_fail', is_required: true },
          { label: 'Fire Extinguishers Tested', item_type: 'pass_fail' },
          { label: 'Exit Signs Illuminated', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Emergency Lighting Working', item_type: 'pass_fail' },
          { label: 'Emergency Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Training and Information',
        items: [
          { label: 'Induction Training Provided', item_type: 'pass_fail', is_required: true },
          { label: 'Job-Specific Training', item_type: 'pass_fail' },
          { label: 'Training Records Maintained', item_type: 'pass_fail' },
          { label: 'Supervision Adequate', item_type: 'pass_fail' },
          { label: 'Information Provided to Workers', item_type: 'pass_fail' },
          { label: 'Training Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Incident Management',
        items: [
          { label: 'Incident Reporting Procedure', item_type: 'pass_fail', is_required: true },
          { label: 'Notifiable Incidents Reported', item_type: 'pass_fail' },
          { label: 'Incident Register Maintained', item_type: 'pass_fail' },
          { label: 'Incidents Investigated', item_type: 'pass_fail' },
          { label: 'Corrective Actions Implemented', item_type: 'pass_fail' },
          { label: 'Records Kept (5 years)', item_type: 'pass_fail' },
          { label: 'Incident Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Total Issues Identified', item_type: 'number', is_required: true },
          { label: 'High Risk Issues', item_type: 'number' },
          { label: 'Medium Risk Issues', item_type: 'number' },
          { label: 'Low Risk Issues', item_type: 'number' },
          { label: 'Issue Details', item_type: 'text' },
          { label: 'Corrective Actions Required', item_type: 'text' },
          { label: 'Target Completion Date', item_type: 'date' },
          { label: 'Overall WHS Compliance', item_type: 'select', is_required: true, options: ['Compliant', 'Minor Non-Compliance', 'Significant Non-Compliance', 'Serious Non-Compliance'] },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'PCBU Representative Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 2. AUSTRALIAN FOOD SAFETY (Food Standards Code)
  // ============================================
  {
    id: 'compliance-au-food-safety',
    name: 'Australian Food Safety Inspection',
    description: 'Food safety inspection per Food Standards Australia New Zealand (FSANZ) Code',
    record_type_id: 'compliance-au',
    sections: [
      {
        name: 'Business Information',
        items: [
          { label: 'Business Name', item_type: 'text', is_required: true },
          { label: 'Trading Name', item_type: 'text' },
          { label: 'Business Address', item_type: 'text', is_required: true },
          { label: 'State/Territory', item_type: 'select', is_required: true, options: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'ACT', 'NT'] },
          { label: 'Business Type', item_type: 'select', is_required: true, options: ['Restaurant', 'Cafe', 'Takeaway', 'Caterer', 'Supermarket', 'Manufacturer', 'Warehouse', 'Mobile Food Van'] },
          { label: 'Food Safety Supervisor', item_type: 'text', is_required: true },
          { label: 'FSS Certificate Number', item_type: 'text' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
        ],
      },
      {
        name: 'Food Safety Program',
        items: [
          { label: 'Food Safety Program in Place', item_type: 'pass_fail', is_required: true },
          { label: 'Program Based on HACCP', item_type: 'pass_fail' },
          { label: 'Hazards Identified', item_type: 'pass_fail' },
          { label: 'Critical Control Points Identified', item_type: 'pass_fail' },
          { label: 'Monitoring Procedures', item_type: 'pass_fail' },
          { label: 'Corrective Actions Documented', item_type: 'pass_fail' },
          { label: 'Records Maintained', item_type: 'pass_fail', is_required: true },
          { label: 'Program Reviewed Annually', item_type: 'pass_fail' },
          { label: 'FSP Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Food Handling',
        items: [
          { label: 'Food Handling Photo', item_type: 'photo' },
          { label: 'Food Handlers Trained', item_type: 'pass_fail', is_required: true },
          { label: 'Clean Protective Clothing', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Hair Restraints Used', item_type: 'pass_fail' },
          { label: 'No Illness Handling Food', item_type: 'pass_fail', is_required: true },
          { label: 'Hand Washing Practiced', item_type: 'pass_fail', is_required: true },
          { label: 'No Bare Hand Contact with RTE Food', item_type: 'pass_fail' },
          { label: 'Gloves Changed Appropriately', item_type: 'pass_fail' },
          { label: 'Food Handling Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Temperature Control',
        items: [
          { label: 'Cold Food Storage (<5°C)', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Fridge 1 Temperature (°C)', item_type: 'temperature' },
          { label: 'Fridge 2 Temperature (°C)', item_type: 'temperature' },
          { label: 'Freezer Temperature (<-15°C)', item_type: 'pass_fail' },
          { label: 'Freezer Temperature (°C)', item_type: 'temperature' },
          { label: 'Hot Holding (>60°C)', item_type: 'pass_fail', is_required: true },
          { label: 'Hot Holding Temperature (°C)', item_type: 'temperature' },
          { label: 'Cooking Temperatures Adequate', item_type: 'pass_fail' },
          { label: 'Cooling within 2hr/4hr Rule', item_type: 'pass_fail' },
          { label: 'Temperature Records Kept', item_type: 'pass_fail', is_required: true },
          { label: 'Probe Thermometer Available', item_type: 'pass_fail' },
          { label: 'Thermometer Calibrated', item_type: 'pass_fail' },
          { label: 'Temperature Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Cross-Contamination Control',
        items: [
          { label: 'Raw/Cooked Separation', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Separate Storage Areas', item_type: 'pass_fail' },
          { label: 'Separate Utensils/Equipment', item_type: 'pass_fail' },
          { label: 'Colour-Coded Boards', item_type: 'pass_fail' },
          { label: 'Allergen Controls', item_type: 'pass_fail' },
          { label: 'Allergen Information Available', item_type: 'pass_fail' },
          { label: 'Cross-Contamination Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Premises and Equipment',
        items: [
          { label: 'Premises Clean', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Kitchen Photo', item_type: 'photo' },
          { label: 'Floors Clean and in Good Repair', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Walls Clean and in Good Repair', item_type: 'pass_fail' },
          { label: 'Ceilings Clean', item_type: 'pass_fail' },
          { label: 'Equipment Clean', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Equipment in Good Repair', item_type: 'pass_fail' },
          { label: 'Hand Wash Basin Available', item_type: 'pass_fail', is_required: true },
          { label: 'Soap and Paper Towels', item_type: 'pass_fail', is_required: true },
          { label: 'Sanitiser Available', item_type: 'pass_fail' },
          { label: 'Cleaning Schedule', item_type: 'pass_fail' },
          { label: 'Premises Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Pest Control',
        items: [
          { label: 'No Evidence of Pests', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Pest Control Program', item_type: 'pass_fail' },
          { label: 'Pest Control Records', item_type: 'pass_fail' },
          { label: 'Doors/Windows Screened', item_type: 'pass_fail' },
          { label: 'Self-Closing Doors', item_type: 'pass_fail' },
          { label: 'No Harbourage Points', item_type: 'pass_fail' },
          { label: 'Pest Control Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Food Receipt and Storage',
        items: [
          { label: 'Supplier Approved', item_type: 'pass_fail' },
          { label: 'Delivery Temperature Checked', item_type: 'pass_fail' },
          { label: 'Food Dated on Receipt', item_type: 'pass_fail' },
          { label: 'FIFO Rotation', item_type: 'pass_fail', is_required: true },
          { label: 'Food Off Floor (15cm)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Expired Products', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Chemicals Stored Separately', item_type: 'pass_fail' },
          { label: 'Storage Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Critical Non-Conformances', item_type: 'number', is_required: true },
          { label: 'Major Non-Conformances', item_type: 'number' },
          { label: 'Minor Non-Conformances', item_type: 'number' },
          { label: 'Non-Conformance Details', item_type: 'text' },
          { label: 'Corrective Actions Required', item_type: 'text' },
          { label: 'Scores and Eat Safe Rating', item_type: 'select', options: ['5 Stars', '4 Stars', '3 Stars', '2 Stars', '1 Star', 'Not Rated'] },
          { label: 'Follow-up Required', item_type: 'yes_no' },
          { label: 'Follow-up Date', item_type: 'date' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Business Representative Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 3. AUSTRALIAN ELECTRICAL SAFETY (AS/NZS 3000)
  // ============================================
  {
    id: 'compliance-au-electrical',
    name: 'Australian Electrical Safety Inspection',
    description: 'Electrical safety inspection per AS/NZS 3000 Wiring Rules',
    record_type_id: 'compliance-au',
    sections: [
      {
        name: 'Inspection Details',
        items: [
          { label: 'Property Address', item_type: 'text', is_required: true },
          { label: 'State/Territory', item_type: 'select', is_required: true, options: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'ACT', 'NT'] },
          { label: 'Property Type', item_type: 'select', is_required: true, options: ['Residential', 'Commercial', 'Industrial', 'Rental Property'] },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Licensed Electrician Name', item_type: 'text', is_required: true },
          { label: 'Licence Number', item_type: 'text', is_required: true },
          { label: 'Contractor Licence Number', item_type: 'text' },
          { label: 'Installation Age (Years)', item_type: 'number' },
        ],
      },
      {
        name: 'Switchboard',
        items: [
          { label: 'Switchboard Accessible', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Switchboard Photo', item_type: 'photo', is_required: true },
          { label: 'Switchboard Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Main Switch Present', item_type: 'pass_fail', is_required: true },
          { label: 'Circuit Breakers Used', item_type: 'pass_fail' },
          { label: 'Rewireable Fuses Present', item_type: 'yes_no' },
          { label: 'Circuits Labelled', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'RCDs Installed', item_type: 'pass_fail', is_required: true },
          { label: 'RCDs Protecting Required Circuits', item_type: 'pass_fail', is_required: true },
          { label: 'RCD Test Button Working', item_type: 'pass_fail', is_required: true },
          { label: 'RCD Trip Time (<300ms)', item_type: 'pass_fail' },
          { label: 'No Asbestos Backing Board', item_type: 'pass_fail' },
          { label: 'Switchboard Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Smoke Alarms (AS 3786)',
        items: [
          { label: 'Smoke Alarms Installed', item_type: 'pass_fail', is_required: true },
          { label: 'Smoke Alarm Photo', item_type: 'photo' },
          { label: 'Compliant Model (AS 3786)', item_type: 'pass_fail' },
          { label: 'Interconnected (if required)', item_type: 'pass_fail' },
          { label: 'Hardwired with Battery Backup', item_type: 'pass_fail' },
          { label: 'Test Button Working', item_type: 'pass_fail', is_required: true },
          { label: 'Within Expiry Date (10 years)', item_type: 'pass_fail' },
          { label: 'Correct Locations', item_type: 'pass_fail' },
          { label: 'Smoke Alarm Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Power Points and Switches',
        items: [
          { label: 'Power Points Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Power Point Photo', item_type: 'photo' },
          { label: 'Switches Working', item_type: 'pass_fail' },
          { label: 'No Damaged Faceplates', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Burn Marks', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Secure Mounting', item_type: 'pass_fail' },
          { label: 'No Exposed Wiring', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Outdoor Points Weatherproof', item_type: 'pass_fail' },
          { label: 'Power Points Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Lighting',
        items: [
          { label: 'Light Fittings Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Light Switches Working', item_type: 'pass_fail' },
          { label: 'No Damaged Fittings', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Bathroom Lights Appropriate', item_type: 'pass_fail' },
          { label: 'Outdoor Lights Weatherproof', item_type: 'pass_fail' },
          { label: 'Downlights Clearance Adequate', item_type: 'pass_fail' },
          { label: 'Lighting Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Fixed Appliances',
        items: [
          { label: 'Hot Water System Safe', item_type: 'pass_fail' },
          { label: 'Air Conditioning Installation', item_type: 'pass_fail' },
          { label: 'Oven/Cooktop Installation', item_type: 'pass_fail' },
          { label: 'Pool/Spa Equipment (if present)', item_type: 'pass_fail' },
          { label: 'RCD Protection for Pool', item_type: 'pass_fail' },
          { label: 'Solar System (if present)', item_type: 'pass_fail' },
          { label: 'Fixed Appliances Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Test Results',
        items: [
          { label: 'Visual Inspection Complete', item_type: 'pass_fail', is_required: true },
          { label: 'Insulation Resistance Test', item_type: 'pass_fail' },
          { label: 'Insulation Resistance (MΩ)', item_type: 'number' },
          { label: 'Earth Continuity Test', item_type: 'pass_fail' },
          { label: 'Polarity Test', item_type: 'pass_fail' },
          { label: 'RCD Performance Test', item_type: 'pass_fail', is_required: true },
          { label: 'Loop Impedance Test', item_type: 'pass_fail' },
          { label: 'Test Results Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Overall Electrical Safety', item_type: 'select', is_required: true, options: ['Safe', 'Satisfactory with Recommendations', 'Unsatisfactory - Repairs Required', 'Unsafe - Immediate Action Required'] },
          { label: 'Defects Found', item_type: 'number' },
          { label: 'Defect Details', item_type: 'text' },
          { label: 'Urgent Works Required', item_type: 'text' },
          { label: 'Recommended Works', item_type: 'text' },
          { label: 'Certificate of Electrical Safety Issued', item_type: 'yes_no' },
          { label: 'Certificate Number', item_type: 'text' },
          { label: 'Electrician Signature', item_type: 'signature', is_required: true },
          { label: 'Next Inspection Recommended', item_type: 'date' },
        ],
      },
    ],
  },

  // ============================================
  // 4. AUSTRALIAN FIRE SAFETY (AS 1851)
  // ============================================
  {
    id: 'compliance-au-fire-safety',
    name: 'Australian Essential Fire Safety Inspection',
    description: 'Fire safety inspection per AS 1851 and Building Code of Australia requirements',
    record_type_id: 'compliance-au',
    sections: [
      {
        name: 'Building Information',
        items: [
          { label: 'Building Name', item_type: 'text', is_required: true },
          { label: 'Building Address', item_type: 'text', is_required: true },
          { label: 'State/Territory', item_type: 'select', is_required: true, options: ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'ACT', 'NT'] },
          { label: 'Building Class (BCA)', item_type: 'select', is_required: true, options: ['Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5', 'Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10'] },
          { label: 'Building Owner/Manager', item_type: 'text', is_required: true },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Accreditation Number', item_type: 'text' },
          { label: 'Annual Fire Safety Statement Due', item_type: 'date' },
        ],
      },
      {
        name: 'Fire Detection and Alarm (AS 1670)',
        items: [
          { label: 'Fire Alarm System Type', item_type: 'select', options: ['Smoke Detection', 'Heat Detection', 'Combined', 'Aspirating', 'None Required'] },
          { label: 'Fire Indicator Panel Photo', item_type: 'photo' },
          { label: 'FIP Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'System Operational', item_type: 'pass_fail', is_required: true },
          { label: 'No Faults Displayed', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Manual Call Points Working', item_type: 'pass_fail' },
          { label: 'Detectors Clean', item_type: 'pass_fail' },
          { label: 'Sounders/Bells Working', item_type: 'pass_fail' },
          { label: 'Monitoring Connection', item_type: 'pass_fail' },
          { label: 'Zone Plan Displayed', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Last Service Date', item_type: 'date' },
          { label: 'Detection Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Fire Hydrants and Hose Reels (AS 2419)',
        items: [
          { label: 'Fire Hydrant System Present', item_type: 'yes_no' },
          { label: 'Hydrant Booster Photo', item_type: 'photo' },
          { label: 'Booster Assembly Accessible', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Hydrants Accessible', item_type: 'pass_fail' },
          { label: 'Landing Valves Working', item_type: 'pass_fail' },
          { label: 'Block Plan Displayed', item_type: 'pass_fail' },
          { label: 'Hose Reels Present', item_type: 'yes_no' },
          { label: 'Hose Reels Accessible', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Hose Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Nozzle Working', item_type: 'pass_fail' },
          { label: 'Water Flow Adequate', item_type: 'pass_fail' },
          { label: 'Hydrant/Hose Reel Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Portable Fire Extinguishers (AS 2444)',
        items: [
          { label: 'Extinguishers Provided', item_type: 'pass_fail', is_required: true },
          { label: 'Extinguisher Photo', item_type: 'photo' },
          { label: 'Correct Types for Hazards', item_type: 'pass_fail' },
          { label: 'Accessible (Travel Distance)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Mounting Height Correct', item_type: 'pass_fail' },
          { label: 'Service Tags Current', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Pressure Gauge OK', item_type: 'pass_fail' },
          { label: 'No Damage or Corrosion', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Location Signs', item_type: 'pass_fail' },
          { label: 'Extinguisher Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Sprinkler System (AS 2118)',
        items: [
          { label: 'Sprinkler System Present', item_type: 'yes_no' },
          { label: 'Sprinkler Valve Room Photo', item_type: 'photo' },
          { label: 'Main Stop Valve Open', item_type: 'pass_fail' },
          { label: 'System Pressure OK', item_type: 'pass_fail' },
          { label: 'Sprinkler Heads Unobstructed (500mm)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Damaged Heads', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Spare Heads Available', item_type: 'pass_fail' },
          { label: 'Flow Switch Working', item_type: 'pass_fail' },
          { label: 'Sprinkler Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Emergency Lighting and Exit Signs (AS 2293)',
        items: [
          { label: 'Emergency Lighting Installed', item_type: 'pass_fail', is_required: true },
          { label: 'Exit Sign Photo', item_type: 'photo' },
          { label: 'Exit Signs Illuminated', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Exit Signs Visible', item_type: 'pass_fail' },
          { label: 'Emergency Lights Working', item_type: 'pass_fail', is_required: true },
          { label: 'Battery Backup (90 min)', item_type: 'pass_fail' },
          { label: 'Discharge Test Passed', item_type: 'pass_fail' },
          { label: 'Test Log Maintained', item_type: 'pass_fail' },
          { label: 'Emergency Lighting Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Fire Doors and Exits',
        items: [
          { label: 'Fire Doors Present', item_type: 'yes_no' },
          { label: 'Fire Door Photo', item_type: 'photo' },
          { label: 'Self-Closing Mechanism Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Door Seals Intact', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Doors Not Propped Open', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Magnetic Hold-Open Devices', item_type: 'pass_fail' },
          { label: 'Fire Rating Labels Present', item_type: 'pass_fail' },
          { label: 'Exit Paths Clear', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Final Exit Operational', item_type: 'pass_fail', is_required: true },
          { label: 'Fire Door Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Passive Fire Protection',
        items: [
          { label: 'Fire Compartmentation Intact', item_type: 'pass_fail' },
          { label: 'Penetration Seals Intact', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Fire Collars Present', item_type: 'pass_fail' },
          { label: 'Dampers Operational', item_type: 'pass_fail' },
          { label: 'No Breaches in Fire Walls', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Passive Fire Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Total Essential Measures', item_type: 'number' },
          { label: 'Measures Satisfactory', item_type: 'number' },
          { label: 'Measures Unsatisfactory', item_type: 'number' },
          { label: 'Critical Deficiencies', item_type: 'number' },
          { label: 'Deficiency Details', item_type: 'text' },
          { label: 'Corrective Actions Required', item_type: 'text' },
          { label: 'AFSS Can Be Issued', item_type: 'yes_no', help_text: 'Annual Fire Safety Statement' },
          { label: 'Overall Assessment', item_type: 'select', is_required: true, options: ['Satisfactory - AFSS Ready', 'Satisfactory with Minor Works', 'Unsatisfactory - Significant Works Required', 'Critical Non-Compliance'] },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Building Manager Signature', item_type: 'signature' },
        ],
      },
    ],
  },
];
