/**
 * UK Regulatory Compliance Templates
 * 11 templates for UK-specific regulatory inspections
 */

import { TemplateDefinition, SAFETY_CHECKLIST_ITEMS, SIGN_OFF_ITEMS } from './types';

export const COMPLIANCE_UK_TEMPLATES: TemplateDefinition[] = [
  // ============================================
  // 1. FIRE SAFETY (Regulatory Reform Fire Safety Order 2005)
  // ============================================
  {
    id: 'compliance-uk-fire-safety',
    name: 'UK Fire Risk Assessment',
    description: 'Fire risk assessment compliant with Regulatory Reform (Fire Safety) Order 2005',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Premises Information',
        items: [
          { label: 'Premises Name', item_type: 'text', is_required: true },
          { label: 'Premises Address', item_type: 'composite_address_uk', is_required: true },
          { label: 'Premises Type', item_type: 'dropdown', is_required: true, options: ['Office', 'Retail', 'Industrial', 'Residential (HMO)', 'Hotel/B&B', 'Restaurant/Pub', 'School', 'Care Home', 'Hospital', 'Warehouse', 'Mixed Use', 'Other'] },
          { label: 'Number of Floors', item_type: 'number' },
          { label: 'Approximate Floor Area (sq m)', item_type: 'number' },
          { label: 'Maximum Occupancy', item_type: 'number' },
          { label: 'Responsible Person', item_type: 'text', is_required: true },
          { label: 'Assessment Date', item_type: 'date', is_required: true },
          { label: 'Assessor Name', item_type: 'text', is_required: true },
          { label: 'Assessor Qualifications', item_type: 'text' },
          { label: 'Previous Assessment Date', item_type: 'date' },
        ],
      },
      {
        name: 'Fire Hazards Identification',
        items: [
          { label: 'Sources of Ignition Identified', item_type: 'multi_select', options: ['Electrical Equipment', 'Heating Systems', 'Cooking Equipment', 'Smoking Materials', 'Hot Work', 'Lighting', 'Arson Risk', 'Other'] },
          { label: 'Ignition Sources Photo', item_type: 'photo' },
          { label: 'Sources of Fuel Identified', item_type: 'multi_select', options: ['Paper/Cardboard', 'Textiles/Fabrics', 'Flammable Liquids', 'Flammable Gases', 'Plastics', 'Wood/Furniture', 'Packaging Materials', 'Waste/Rubbish', 'Other'] },
          { label: 'Fuel Sources Photo', item_type: 'photo' },
          { label: 'Sources of Oxygen', item_type: 'multi_select', options: ['Natural Ventilation', 'Mechanical Ventilation', 'Air Conditioning', 'Oxygen Cylinders', 'Oxidising Chemicals'] },
          { label: 'Hazardous Materials Stored', item_type: 'yes_no' },
          { label: 'Hazardous Materials Details', item_type: 'textarea' },
          { label: 'Fire Hazards Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'People at Risk',
        items: [
          { label: 'Typical Number of Occupants', item_type: 'number' },
          { label: 'Visitors/Public Access', item_type: 'yes_no' },
          { label: 'Night Occupancy', item_type: 'yes_no' },
          { label: 'Lone Workers Present', item_type: 'yes_no' },
          { label: 'People with Disabilities', item_type: 'yes_no' },
          { label: 'PEEPs in Place', item_type: 'yes_no', help_text: 'Personal Emergency Evacuation Plans' },
          { label: 'Children Present', item_type: 'yes_no' },
          { label: 'Elderly Residents', item_type: 'yes_no' },
          { label: 'Sleeping Risk', item_type: 'yes_no' },
          { label: 'At-Risk Groups Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Means of Escape',
        items: [
          { label: 'Number of Fire Exits', item_type: 'number', is_required: true },
          { label: 'Fire Exits Adequate for Occupancy', item_type: 'pass_fail', is_required: true },
          { label: 'Fire Exit Photo', item_type: 'photo', is_required: true },
          { label: 'Escape Routes Clear', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Exit Doors Open Outward', item_type: 'pass_fail' },
          { label: 'Exit Doors Easily Opened', item_type: 'pass_fail', is_required: true },
          { label: 'Travel Distances Acceptable', item_type: 'pass_fail' },
          { label: 'Protected Stairways Present', item_type: 'yes_no' },
          { label: 'Stairways Free from Storage', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Emergency Lighting Adequate', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Fire Exit Signs Adequate', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Assembly Point Designated', item_type: 'yes_no' },
          { label: 'Escape Routes Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Fire Detection and Warning',
        items: [
          { label: 'Fire Detection System Type', item_type: 'dropdown', is_required: true, options: ['None', 'Smoke Detectors Only', 'Heat Detectors Only', 'L1 (Full Coverage)', 'L2 (Common Areas)', 'L3 (Escape Routes)', 'L4 (Specific Rooms)', 'P1 (Full Property)', 'P2 (Defined Areas)'] },
          { label: 'Detection System Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Fire Alarm Panel Photo', item_type: 'photo' },
          { label: 'Manual Call Points Adequate', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Audible Warning Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Visual Alarms Where Required', item_type: 'pass_fail' },
          { label: 'Alarm Monitoring', item_type: 'dropdown', options: ['None', 'Manned 24/7', 'Remote Monitoring', 'ARC Connection'] },
          { label: 'Last System Test Date', item_type: 'date' },
          { label: 'Weekly Test Record Available', item_type: 'yes_no' },
          { label: 'Detection Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Fire Fighting Equipment',
        items: [
          { label: 'Fire Extinguishers Present', item_type: 'yes_no', is_required: true },
          { label: 'Extinguisher Types Present', item_type: 'multi_select', options: ['Water', 'Foam', 'CO2', 'Dry Powder', 'Wet Chemical'] },
          { label: 'Extinguishers Adequate and Correct', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Extinguishers Accessible', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Last Extinguisher Service Date', item_type: 'date' },
          { label: 'Fire Blankets Where Required', item_type: 'pass_fail' },
          { label: 'Hose Reels Present', item_type: 'yes_no' },
          { label: 'Sprinkler System Present', item_type: 'yes_no' },
          { label: 'Sprinkler System Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Fire Fighting Equipment Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Fire Safety Management',
        items: [
          { label: 'Fire Safety Policy in Place', item_type: 'yes_no', is_required: true },
          { label: 'Emergency Plan in Place', item_type: 'yes_no', is_required: true },
          { label: 'Staff Fire Training Provided', item_type: 'yes_no', is_required: true },
          { label: 'Training Records Available', item_type: 'yes_no' },
          { label: 'Fire Drills Conducted', item_type: 'yes_no', is_required: true },
          { label: 'Last Fire Drill Date', item_type: 'date' },
          { label: 'Fire Marshals Appointed', item_type: 'yes_no' },
          { label: 'Number of Fire Marshals', item_type: 'number' },
          { label: 'Maintenance Records Available', item_type: 'yes_no' },
          { label: 'Contractors Procedures', item_type: 'pass_fail' },
          { label: 'Management Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Fire Compartmentation',
        items: [
          { label: 'Fire Doors Present', item_type: 'yes_no' },
          { label: 'Fire Doors Self-Closing', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Fire Doors in Good Condition', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Door Seals/Strips Intact', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Fire Doors Held Open Correctly', item_type: 'pass_fail' },
          { label: 'Fire Stopping Adequate', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Penetrations Sealed', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Ceiling Void Compartmentation', item_type: 'pass_fail' },
          { label: 'Compartmentation Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Risk Rating',
        items: [
          { label: 'Likelihood of Fire', item_type: 'dropdown', is_required: true, options: ['Low', 'Medium', 'High'] },
          { label: 'Consequence of Fire', item_type: 'dropdown', is_required: true, options: ['Slight Harm', 'Moderate Harm', 'Extreme Harm'] },
          { label: 'Overall Risk Rating', item_type: 'dropdown', is_required: true, options: ['Trivial', 'Tolerable', 'Moderate', 'Substantial', 'Intolerable'] },
          { label: 'Risk Rating Justification', item_type: 'textarea', is_required: true },
        ],
      },
      {
        name: 'Action Plan',
        items: [
          { label: 'Immediate Actions Required', item_type: 'yes_no' },
          { label: 'Immediate Action Details', item_type: 'textarea' },
          { label: 'Short-term Recommendations', item_type: 'textarea' },
          { label: 'Medium-term Recommendations', item_type: 'textarea' },
          { label: 'Long-term Recommendations', item_type: 'textarea' },
          { label: 'Review Date', item_type: 'date', is_required: true },
          { label: 'Assessor Signature', item_type: 'signature', is_required: true },
          { label: 'Responsible Person Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 2. GAS SAFETY (Gas Safety Installation & Use Regulations 1998)
  // ============================================
  {
    id: 'compliance-uk-gas-safety',
    name: 'UK Gas Safety Record (CP12)',
    description: 'Landlord Gas Safety Record compliant with Gas Safety (Installation and Use) Regulations 1998',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Property Details',
        items: [
          { label: 'Property Address', item_type: 'composite_address_uk', is_required: true },
          { label: 'Landlord/Agent Name', item_type: 'text', is_required: true },
          { label: 'Landlord/Agent Address', item_type: 'composite_address_uk' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Next Inspection Due', item_type: 'date', is_required: true },
        ],
      },
      {
        name: 'Engineer Details',
        items: [
          { label: 'Engineer Name', item_type: 'text', is_required: true },
          { label: 'Gas Safe Registration Number', item_type: 'text', is_required: true },
          { label: 'Gas Safe ID Card Photo', item_type: 'photo' },
          { label: 'Company Name', item_type: 'text' },
          { label: 'Company Address', item_type: 'text' },
          { label: 'Company Gas Safe Number', item_type: 'text' },
        ],
      },
      {
        name: 'Appliance 1',
        items: [
          { label: 'Appliance Location', item_type: 'text', is_required: true },
          { label: 'Appliance Type', item_type: 'dropdown', is_required: true, options: ['Boiler', 'Fire', 'Cooker', 'Hob', 'Water Heater', 'Warm Air Unit', 'Other'] },
          { label: 'Appliance Make', item_type: 'text' },
          { label: 'Appliance Model', item_type: 'text' },
          { label: 'Appliance Photo', item_type: 'photo' },
          { label: 'Flue Type', item_type: 'dropdown', options: ['Open Flue', 'Room Sealed', 'Flueless', 'N/A'] },
          { label: 'Operating Pressure (mbar)', item_type: 'number' },
          { label: 'Safety Device Correct Operation', item_type: 'pass_fail', is_required: true },
          { label: 'Ventilation Satisfactory', item_type: 'pass_fail', is_required: true },
          { label: 'Visual Condition of Flue', item_type: 'pass_fail' },
          { label: 'Flue Flow/Spillage Test', item_type: 'pass_fail' },
          { label: 'Appliance Serviced', item_type: 'yes_no' },
          { label: 'Appliance Safe to Use', item_type: 'pass_fail', is_required: true },
          { label: 'Defects Identified', item_type: 'textarea' },
        ],
      },
      {
        name: 'Appliance 2',
        items: [
          { label: 'Appliance 2 Present', item_type: 'yes_no' },
          { label: 'Appliance Location', item_type: 'text' },
          { label: 'Appliance Type', item_type: 'dropdown', options: ['Boiler', 'Fire', 'Cooker', 'Hob', 'Water Heater', 'Warm Air Unit', 'Other'] },
          { label: 'Appliance Make', item_type: 'text' },
          { label: 'Appliance Model', item_type: 'text' },
          { label: 'Appliance Photo', item_type: 'photo' },
          { label: 'Flue Type', item_type: 'dropdown', options: ['Open Flue', 'Room Sealed', 'Flueless', 'N/A'] },
          { label: 'Operating Pressure (mbar)', item_type: 'number' },
          { label: 'Safety Device Correct Operation', item_type: 'pass_fail' },
          { label: 'Ventilation Satisfactory', item_type: 'pass_fail' },
          { label: 'Visual Condition of Flue', item_type: 'pass_fail' },
          { label: 'Flue Flow/Spillage Test', item_type: 'pass_fail' },
          { label: 'Appliance Serviced', item_type: 'yes_no' },
          { label: 'Appliance Safe to Use', item_type: 'pass_fail' },
          { label: 'Defects Identified', item_type: 'textarea' },
        ],
      },
      {
        name: 'Appliance 3',
        items: [
          { label: 'Appliance 3 Present', item_type: 'yes_no' },
          { label: 'Appliance Location', item_type: 'text' },
          { label: 'Appliance Type', item_type: 'dropdown', options: ['Boiler', 'Fire', 'Cooker', 'Hob', 'Water Heater', 'Warm Air Unit', 'Other'] },
          { label: 'Appliance Make', item_type: 'text' },
          { label: 'Appliance Model', item_type: 'text' },
          { label: 'Flue Type', item_type: 'dropdown', options: ['Open Flue', 'Room Sealed', 'Flueless', 'N/A'] },
          { label: 'Operating Pressure (mbar)', item_type: 'number' },
          { label: 'Safety Device Correct Operation', item_type: 'pass_fail' },
          { label: 'Ventilation Satisfactory', item_type: 'pass_fail' },
          { label: 'Visual Condition of Flue', item_type: 'pass_fail' },
          { label: 'Flue Flow/Spillage Test', item_type: 'pass_fail' },
          { label: 'Appliance Serviced', item_type: 'yes_no' },
          { label: 'Appliance Safe to Use', item_type: 'pass_fail' },
          { label: 'Defects Identified', item_type: 'textarea' },
        ],
      },
      {
        name: 'Installation Pipework',
        items: [
          { label: 'Visual Inspection of Pipework', item_type: 'pass_fail', is_required: true },
          { label: 'Emergency Control Accessible', item_type: 'pass_fail', is_required: true },
          { label: 'Tightness Test Performed', item_type: 'pass_fail', is_required: true },
          { label: 'Tightness Test Result', item_type: 'dropdown', options: ['Pass', 'Fail - Leak Found', 'Not Tested'] },
          { label: 'Installation Pipework Satisfactory', item_type: 'pass_fail', is_required: true },
          { label: 'Pipework Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Carbon Monoxide Alarm',
        items: [
          { label: 'CO Alarm Present', item_type: 'yes_no', is_required: true },
          { label: 'CO Alarm Photo', item_type: 'photo' },
          { label: 'CO Alarm Location', item_type: 'text' },
          { label: 'CO Alarm Tested', item_type: 'pass_fail' },
          { label: 'CO Alarm Expiry Date', item_type: 'date' },
        ],
      },
      {
        name: 'Summary and Declaration',
        items: [
          { label: 'Remedial Work Required', item_type: 'yes_no' },
          { label: 'Remedial Work Description', item_type: 'textarea' },
          { label: 'Warning Labels Attached', item_type: 'yes_no' },
          { label: 'Overall Result', item_type: 'dropdown', is_required: true, options: ['Pass - All Appliances Safe', 'Fail - Immediate Action Required', 'At Risk - Remedial Work Needed'] },
          { label: 'Comments', item_type: 'textarea' },
          { label: 'Engineer Signature', item_type: 'signature', is_required: true },
          { label: 'Tenant/Occupier Name', item_type: 'text' },
          { label: 'Record Issued Date', item_type: 'date', is_required: true },
        ],
      },
    ],
  },

  // ============================================
  // 3. ELECTRICAL SAFETY (Electrical Safety Standards Regulations 2020)
  // ============================================
  {
    id: 'compliance-uk-eicr',
    name: 'UK EICR (Electrical Installation Condition Report)',
    description: 'Electrical safety inspection compliant with 18th Edition IET Wiring Regulations',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Report Details',
        items: [
          { label: 'Client/Landlord Name', item_type: 'text', is_required: true },
          { label: 'Client Address', item_type: 'composite_address_uk' },
          { label: 'Installation Address', item_type: 'composite_address_uk', is_required: true },
          { label: 'Description of Premises', item_type: 'dropdown', is_required: true, options: ['Domestic Dwelling', 'HMO', 'Commercial', 'Industrial', 'Mixed Use'] },
          { label: 'Estimated Age of Installation', item_type: 'text' },
          { label: 'Date of Last Inspection', item_type: 'date' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
        ],
      },
      {
        name: 'Contractor Details',
        items: [
          { label: 'Contractor Name', item_type: 'text', is_required: true },
          { label: 'Contractor Address', item_type: 'text' },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Registration/Scheme', item_type: 'dropdown', is_required: true, options: ['NICEIC', 'NAPIT', 'ELECSA', 'Stroma', 'Other'] },
          { label: 'Registration Number', item_type: 'text', is_required: true },
        ],
      },
      {
        name: 'Supply Details',
        items: [
          { label: 'System Type (TN-S, TN-C-S, TT)', item_type: 'dropdown', is_required: true, options: ['TN-S', 'TN-C-S', 'TT', 'IT', 'Unknown'] },
          { label: 'Number of Phases', item_type: 'dropdown', options: ['Single Phase', 'Three Phase'] },
          { label: 'Nominal Voltage (V)', item_type: 'number' },
          { label: 'Nominal Frequency (Hz)', item_type: 'number' },
          { label: 'Supplier Cut-Out (Amps)', item_type: 'number' },
          { label: 'Main Switch Rating (Amps)', item_type: 'number' },
          { label: 'Supply Photo', item_type: 'photo' },
        ],
      },
      {
        name: 'Consumer Unit',
        items: [
          { label: 'Consumer Unit Location', item_type: 'text', is_required: true },
          { label: 'Consumer Unit Make', item_type: 'text' },
          { label: 'Consumer Unit Type', item_type: 'dropdown', options: ['Dual RCD', 'High Integrity', 'RCBO', 'Rewireable Fuse', 'Mixed'] },
          { label: 'Consumer Unit Photo', item_type: 'photo', is_required: true },
          { label: 'Consumer Unit Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Main Switch Present', item_type: 'pass_fail' },
          { label: 'RCD Protection Present', item_type: 'pass_fail', is_required: true },
          { label: 'Circuits Correctly Labelled', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Number of Circuits', item_type: 'number' },
          { label: 'Consumer Unit Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Test Results Summary',
        items: [
          { label: 'External Loop Impedance Ze (Ω)', item_type: 'number', is_required: true },
          { label: 'PFC at Origin (kA)', item_type: 'number' },
          { label: 'RCD Test Results Satisfactory', item_type: 'pass_fail', is_required: true },
          { label: 'Insulation Resistance Satisfactory', item_type: 'pass_fail', is_required: true },
          { label: 'Ring Final Circuit Continuity', item_type: 'pass_fail' },
          { label: 'Earthing Arrangement Satisfactory', item_type: 'pass_fail', is_required: true },
          { label: 'Main Bonding Present', item_type: 'pass_fail', is_required: true },
          { label: 'Supplementary Bonding Satisfactory', item_type: 'pass_fail' },
          { label: 'Test Results Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Observations',
        items: [
          { label: 'C1 Observations (Danger Present)', item_type: 'number', is_required: true },
          { label: 'C1 Details', item_type: 'textarea' },
          { label: 'C2 Observations (Potentially Dangerous)', item_type: 'number', is_required: true },
          { label: 'C2 Details', item_type: 'textarea' },
          { label: 'C3 Observations (Improvement Recommended)', item_type: 'number' },
          { label: 'C3 Details', item_type: 'textarea' },
          { label: 'FI Observations (Further Investigation)', item_type: 'number' },
          { label: 'FI Details', item_type: 'textarea' },
          { label: 'Observation Photos', item_type: 'photo', photo_rule: 'always' },
        ],
      },
      {
        name: 'Overall Assessment',
        items: [
          { label: 'Overall Condition', item_type: 'dropdown', is_required: true, options: ['Satisfactory', 'Unsatisfactory'] },
          { label: 'Recommended Interval (Years)', item_type: 'dropdown', is_required: true, options: ['1 Year', '2 Years', '3 Years', '5 Years', '10 Years'] },
          { label: 'Limitations to Inspection', item_type: 'textarea' },
          { label: 'General Remarks', item_type: 'textarea' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Report Issue Date', item_type: 'date', is_required: true },
        ],
      },
    ],
  },

  // ============================================
  // 4. LEGIONELLA RISK ASSESSMENT (HSE L8/ACOP)
  // ============================================
  {
    id: 'compliance-uk-legionella',
    name: 'UK Legionella Risk Assessment',
    description: 'Legionella risk assessment compliant with HSE L8 Approved Code of Practice',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Site Information',
        items: [
          { label: 'Site Name', item_type: 'text', is_required: true },
          { label: 'Site Address', item_type: 'composite_address_uk', is_required: true },
          { label: 'Site Type', item_type: 'dropdown', is_required: true, options: ['Residential', 'Commercial Office', 'Hotel', 'Hospital/Healthcare', 'Care Home', 'School/College', 'Industrial', 'Sports/Leisure', 'Other'] },
          { label: 'Responsible Person', item_type: 'text', is_required: true },
          { label: 'Duty Holder', item_type: 'text', is_required: true },
          { label: 'Assessment Date', item_type: 'date', is_required: true },
          { label: 'Assessor Name', item_type: 'text', is_required: true },
          { label: 'Assessor Company', item_type: 'text' },
          { label: 'Previous Assessment Date', item_type: 'date' },
        ],
      },
      {
        name: 'People at Risk',
        items: [
          { label: 'Number of Building Users', item_type: 'number' },
          { label: 'Vulnerable Groups Present', item_type: 'multi_select', options: ['Elderly (50+)', 'Immunocompromised', 'Smokers', 'Chronic Respiratory Disease', 'Diabetics', 'None Identified'] },
          { label: 'Workers Potentially Exposed', item_type: 'yes_no' },
          { label: 'Public Potentially Exposed', item_type: 'yes_no' },
          { label: 'People at Risk Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Cold Water Systems',
        items: [
          { label: 'Cold Water Storage Present', item_type: 'yes_no', is_required: true },
          { label: 'Tank Location', item_type: 'text' },
          { label: 'Tank Material', item_type: 'dropdown', options: ['Plastic (GRP)', 'Galvanised Steel', 'Copper', 'Other'] },
          { label: 'Tank Capacity (Litres)', item_type: 'number' },
          { label: 'Tank Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Tank Photo', item_type: 'photo' },
          { label: 'Lid Fitted and Secure', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Insulated Adequately', item_type: 'pass_fail' },
          { label: 'Overflow Screened', item_type: 'pass_fail' },
          { label: 'Temperature at Tank Outlet (°C)', item_type: 'temperature' },
          { label: 'Cold Water Stored Below 20°C', item_type: 'pass_fail', is_required: true },
          { label: 'Dead Legs Identified', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Cold Water Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Hot Water Systems',
        items: [
          { label: 'Hot Water System Type', item_type: 'dropdown', is_required: true, options: ['Stored (Calorifier)', 'Combi Boiler', 'Point of Use', 'Centralised', 'Mixed'] },
          { label: 'Calorifier Present', item_type: 'yes_no' },
          { label: 'Calorifier Capacity (Litres)', item_type: 'number' },
          { label: 'Calorifier Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Calorifier Photo', item_type: 'photo' },
          { label: 'Stored Hot Water Temperature (°C)', item_type: 'temperature' },
          { label: 'Hot Water Stored at 60°C or Above', item_type: 'pass_fail', is_required: true },
          { label: 'Distribution Temperature at Outlet (°C)', item_type: 'temperature' },
          { label: 'Hot Water at Outlets Within 1 Min at 50°C', item_type: 'pass_fail' },
          { label: 'TMVs Present', item_type: 'yes_no' },
          { label: 'TMV Locations', item_type: 'text' },
          { label: 'Hot Water Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Showers and Spray Outlets',
        items: [
          { label: 'Showers Present', item_type: 'yes_no', is_required: true },
          { label: 'Number of Showers', item_type: 'number' },
          { label: 'Shower Head Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Shower Hose Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Descaling Required', item_type: 'yes_no' },
          { label: 'Infrequently Used Outlets', item_type: 'yes_no' },
          { label: 'Flushing Regime in Place', item_type: 'yes_no' },
          { label: 'Spray Taps Present', item_type: 'yes_no' },
          { label: 'Showers Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Other Water Systems',
        items: [
          { label: 'Cooling Towers Present', item_type: 'yes_no' },
          { label: 'Evaporative Condensers Present', item_type: 'yes_no' },
          { label: 'Spa Pool/Hot Tub Present', item_type: 'yes_no' },
          { label: 'Water Features/Fountains Present', item_type: 'yes_no' },
          { label: 'Fire Sprinkler System Present', item_type: 'yes_no' },
          { label: 'Emergency Showers/Eyewash', item_type: 'yes_no' },
          { label: 'Humidifiers Present', item_type: 'yes_no' },
          { label: 'Other Systems Details', item_type: 'textarea' },
        ],
      },
      {
        name: 'Water Treatment',
        items: [
          { label: 'Water Treatment in Place', item_type: 'yes_no' },
          { label: 'Treatment Type', item_type: 'multi_select', options: ['None', 'Chemical Dosing', 'Chlorine Dioxide', 'Copper/Silver Ionisation', 'UV Treatment', 'Filtration'] },
          { label: 'Treatment Provider', item_type: 'text' },
          { label: 'Monitoring in Place', item_type: 'yes_no' },
          { label: 'Temperature Monitoring Records', item_type: 'yes_no' },
          { label: 'Treatment Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Risk Evaluation',
        items: [
          { label: 'Risk Level', item_type: 'dropdown', is_required: true, options: ['Low', 'Medium', 'High'] },
          { label: 'Priority Actions Required', item_type: 'textarea' },
          { label: 'Recommended Control Measures', item_type: 'textarea', is_required: true },
          { label: 'Monitoring Frequency Recommended', item_type: 'dropdown', options: ['Weekly', 'Monthly', 'Quarterly', 'Six-Monthly', 'Annually'] },
          { label: 'Review Date', item_type: 'date', is_required: true },
          { label: 'Assessor Signature', item_type: 'signature', is_required: true },
          { label: 'Duty Holder Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 5. PAT TESTING (Electricity at Work Regulations 1989)
  // ============================================
  {
    id: 'compliance-uk-pat',
    name: 'UK PAT Testing Record',
    description: 'Portable Appliance Testing record compliant with IET Code of Practice',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Test Details',
        items: [
          { label: 'Location/Site Name', item_type: 'text', is_required: true },
          { label: 'Location Address', item_type: 'composite_address_uk', is_required: true },
          { label: 'Test Date', item_type: 'date', is_required: true },
          { label: 'Tester Name', item_type: 'text', is_required: true },
          { label: 'Tester Qualification', item_type: 'text' },
          { label: 'Test Equipment Used', item_type: 'text', is_required: true },
          { label: 'Test Equipment Calibration Date', item_type: 'date' },
        ],
      },
      {
        name: 'Appliance Details',
        items: [
          { label: 'Asset Number', item_type: 'text', is_required: true },
          { label: 'Appliance Description', item_type: 'text', is_required: true },
          { label: 'Appliance Make', item_type: 'text' },
          { label: 'Appliance Model', item_type: 'text' },
          { label: 'Serial Number', item_type: 'text' },
          { label: 'Location/Department', item_type: 'text', is_required: true },
          { label: 'Appliance Class', item_type: 'dropdown', is_required: true, options: ['Class I', 'Class II', 'Class III'] },
          { label: 'Appliance Photo', item_type: 'photo' },
        ],
      },
      {
        name: 'Visual Inspection',
        items: [
          { label: 'Plug Condition', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Correct Fuse Fitted', item_type: 'pass_fail', is_required: true },
          { label: 'Fuse Rating (A)', item_type: 'dropdown', options: ['3A', '5A', '13A', 'Other'] },
          { label: 'Cord Grip Secure', item_type: 'pass_fail', is_required: true },
          { label: 'Flex Condition', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Flex Length Appropriate', item_type: 'pass_fail' },
          { label: 'Appliance Condition', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Damage or Modifications', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Suitable for Environment', item_type: 'pass_fail' },
          { label: 'Visual Inspection Result', item_type: 'pass_fail', is_required: true },
        ],
      },
      {
        name: 'Electrical Tests',
        items: [
          { label: 'Earth Continuity (Ω)', item_type: 'number' },
          { label: 'Earth Continuity Limit (Ω)', item_type: 'number' },
          { label: 'Earth Continuity Result', item_type: 'pass_fail' },
          { label: 'Insulation Resistance (MΩ)', item_type: 'number' },
          { label: 'Insulation Resistance Limit (MΩ)', item_type: 'number' },
          { label: 'Insulation Resistance Result', item_type: 'pass_fail' },
          { label: 'Earth Leakage (mA)', item_type: 'number' },
          { label: 'Earth Leakage Limit (mA)', item_type: 'number' },
          { label: 'Earth Leakage Result', item_type: 'pass_fail' },
          { label: 'Polarity Correct', item_type: 'pass_fail' },
          { label: 'Functional Test', item_type: 'pass_fail' },
        ],
      },
      {
        name: 'Test Result',
        items: [
          { label: 'Overall Result', item_type: 'dropdown', is_required: true, options: ['Pass', 'Fail', 'Repairs Required'] },
          { label: 'Pass Label Applied', item_type: 'yes_no' },
          { label: 'Label Number', item_type: 'text' },
          { label: 'Fail Label Applied', item_type: 'yes_no' },
          { label: 'Removed from Service', item_type: 'yes_no' },
          { label: 'Defects Found', item_type: 'textarea' },
          { label: 'Repairs Required', item_type: 'textarea' },
          { label: 'Next Test Due', item_type: 'date' },
          { label: 'Tester Signature', item_type: 'signature', is_required: true },
        ],
      },
    ],
  },

  // ============================================
  // 6. ASBESTOS SURVEY (Control of Asbestos Regulations 2012)
  // ============================================
  {
    id: 'compliance-uk-asbestos',
    name: 'UK Asbestos Management Survey',
    description: 'Asbestos management survey compliant with Control of Asbestos Regulations 2012',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Survey Information',
        items: [
          { label: 'Site Name', item_type: 'text', is_required: true },
          { label: 'Site Address', item_type: 'composite_address_uk', is_required: true },
          { label: 'Client Name', item_type: 'text', is_required: true },
          { label: 'Survey Type', item_type: 'dropdown', is_required: true, options: ['Management Survey', 'Refurbishment/Demolition Survey', 'Re-inspection'] },
          { label: 'Survey Date', item_type: 'date', is_required: true },
          { label: 'Surveyor Name', item_type: 'text', is_required: true },
          { label: 'Surveyor BOHS P402 Certificate', item_type: 'text' },
          { label: 'Survey Company', item_type: 'text' },
          { label: 'UKAS Accreditation Number', item_type: 'text' },
          { label: 'Building Age', item_type: 'text' },
          { label: 'Building Type', item_type: 'text' },
        ],
      },
      {
        name: 'Survey Methodology',
        items: [
          { label: 'Areas Surveyed', item_type: 'textarea', is_required: true },
          { label: 'Areas Not Accessed', item_type: 'textarea' },
          { label: 'Reason for Limitation', item_type: 'textarea' },
          { label: 'Sampling Strategy', item_type: 'dropdown', options: ['Representative Sampling', 'Full Sampling', 'No Sampling (Visual Only)'] },
          { label: 'Number of Samples Taken', item_type: 'number' },
          { label: 'Laboratory Used', item_type: 'text' },
          { label: 'Laboratory UKAS Number', item_type: 'text' },
        ],
      },
      {
        name: 'ACM Finding 1',
        items: [
          { label: 'ACM Reference Number', item_type: 'text', is_required: true },
          { label: 'Location', item_type: 'text', is_required: true },
          { label: 'ACM Type', item_type: 'dropdown', is_required: true, options: ['Asbestos Insulating Board (AIB)', 'Asbestos Cement', 'Lagging', 'Sprayed Coating', 'Floor Tiles', 'Textiles', 'Gaskets', 'Rope/Yarn', 'Paper/Cardboard', 'Bitumen Products', 'Other'] },
          { label: 'Asbestos Type', item_type: 'dropdown', options: ['Chrysotile (White)', 'Amosite (Brown)', 'Crocidolite (Blue)', 'Mixed', 'Presumed', 'No Asbestos Detected'] },
          { label: 'Quantity/Extent', item_type: 'text' },
          { label: 'ACM Photo', item_type: 'photo', is_required: true },
          { label: 'Surface Treatment', item_type: 'dropdown', options: ['Unsealed', 'Painted', 'Encapsulated', 'Enclosed', 'Other'] },
          { label: 'Condition', item_type: 'dropdown', is_required: true, options: ['Good', 'Low Damage', 'Medium Damage', 'High Damage'] },
          { label: 'Accessibility', item_type: 'dropdown', options: ['Easily Accessible', 'Occasionally Accessed', 'Rarely Accessed', 'Not Accessed'] },
          { label: 'Material Assessment Score', item_type: 'number' },
          { label: 'Priority Assessment Score', item_type: 'number' },
          { label: 'Total Risk Score', item_type: 'number' },
        ],
      },
      {
        name: 'ACM Finding 2',
        items: [
          { label: 'ACM 2 Present', item_type: 'yes_no' },
          { label: 'ACM Reference Number', item_type: 'text' },
          { label: 'Location', item_type: 'text' },
          { label: 'ACM Type', item_type: 'dropdown', options: ['Asbestos Insulating Board (AIB)', 'Asbestos Cement', 'Lagging', 'Sprayed Coating', 'Floor Tiles', 'Textiles', 'Gaskets', 'Other'] },
          { label: 'Asbestos Type', item_type: 'dropdown', options: ['Chrysotile (White)', 'Amosite (Brown)', 'Crocidolite (Blue)', 'Mixed', 'Presumed', 'No Asbestos Detected'] },
          { label: 'ACM Photo', item_type: 'photo' },
          { label: 'Condition', item_type: 'dropdown', options: ['Good', 'Low Damage', 'Medium Damage', 'High Damage'] },
          { label: 'Total Risk Score', item_type: 'number' },
        ],
      },
      {
        name: 'Recommendations',
        items: [
          { label: 'Immediate Action Required', item_type: 'yes_no' },
          { label: 'Immediate Action Details', item_type: 'textarea' },
          { label: 'Management Recommendations', item_type: 'textarea', is_required: true },
          { label: 'Remediation Recommendations', item_type: 'textarea' },
          { label: 'Re-inspection Interval', item_type: 'dropdown', options: ['6 Months', '12 Months', '2 Years', 'As Condition Dictates'] },
          { label: 'Asbestos Register Required', item_type: 'yes_no' },
          { label: 'Management Plan Required', item_type: 'yes_no' },
        ],
      },
      {
        name: 'Summary',
        items: [
          { label: 'Total ACMs Identified', item_type: 'number', is_required: true },
          { label: 'ACMs Requiring Immediate Action', item_type: 'number' },
          { label: 'Overall Site Risk', item_type: 'dropdown', is_required: true, options: ['Low', 'Medium', 'High'] },
          { label: 'Survey Limitations', item_type: 'textarea' },
          { label: 'General Comments', item_type: 'textarea' },
          { label: 'Surveyor Signature', item_type: 'signature', is_required: true },
          { label: 'Report Date', item_type: 'date', is_required: true },
        ],
      },
    ],
  },

  // ============================================
  // 7. FOOD HYGIENE (Food Safety Act 1990 / EU 852/2004)
  // ============================================
  {
    id: 'compliance-uk-food-hygiene',
    name: 'UK Food Hygiene Inspection',
    description: 'Food hygiene inspection for Food Hygiene Rating Scheme compliance',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Business Details',
        items: [
          { label: 'Business Name', item_type: 'text', is_required: true },
          { label: 'Business Address', item_type: 'composite_address_uk', is_required: true },
          { label: 'Business Type', item_type: 'dropdown', is_required: true, options: ['Restaurant', 'Takeaway', 'Cafe', 'Pub', 'Hotel', 'School/Hospital Catering', 'Food Manufacturer', 'Retailer', 'Mobile Caterer', 'Other'] },
          { label: 'Registered with Local Authority', item_type: 'yes_no', is_required: true },
          { label: 'Food Business Operator Name', item_type: 'text', is_required: true },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
        ],
      },
      {
        name: 'Hygienic Food Handling',
        items: [
          { label: 'Hygienic Handling Practices', item_type: 'condition', is_required: true },
          { label: 'Temperature Control (Cooking)', item_type: 'pass_fail', is_required: true },
          { label: 'Cooking Temperature Recorded', item_type: 'temperature' },
          { label: 'Temperature Control (Chilling)', item_type: 'pass_fail', is_required: true },
          { label: 'Fridge Temperature (°C)', item_type: 'temperature' },
          { label: 'Freezer Temperature (°C)', item_type: 'temperature' },
          { label: 'Cross-Contamination Prevention', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Raw/Cooked Separation', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Allergen Management', item_type: 'pass_fail' },
          { label: 'Allergen Information Available', item_type: 'yes_no' },
          { label: 'Food Handling Score (0-25)', item_type: 'number', is_required: true },
          { label: 'Food Handling Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Cleanliness and Condition',
        items: [
          { label: 'Overall Cleanliness', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Kitchen Cleanliness Photo', item_type: 'photo' },
          { label: 'Equipment Cleanliness', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Structure Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Floors Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Walls Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Ceilings Clean', item_type: 'pass_fail' },
          { label: 'Pest Proofing Adequate', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Evidence of Pests', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Hand Washing Facilities', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Soap and Towels Available', item_type: 'pass_fail' },
          { label: 'Cleanliness Score (0-25)', item_type: 'number', is_required: true },
          { label: 'Cleanliness Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Management of Food Safety',
        items: [
          { label: 'Food Safety Management System', item_type: 'dropdown', is_required: true, options: ['HACCP', 'Safer Food Better Business', 'Other Documented System', 'None'] },
          { label: 'FSMS Documentation Available', item_type: 'yes_no' },
          { label: 'FSMS Being Followed', item_type: 'pass_fail', is_required: true },
          { label: 'Temperature Records Maintained', item_type: 'pass_fail' },
          { label: 'Staff Training Records', item_type: 'pass_fail' },
          { label: 'Supplier Records', item_type: 'pass_fail' },
          { label: 'Cleaning Schedule', item_type: 'pass_fail' },
          { label: 'Stock Rotation (FIFO)', item_type: 'pass_fail' },
          { label: 'Management Score (0-30)', item_type: 'number', is_required: true },
          { label: 'Management Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Confidence in Management',
        items: [
          { label: 'Track Record', item_type: 'condition' },
          { label: 'Attitude to Compliance', item_type: 'condition', is_required: true },
          { label: 'Previous Inspection Issues Addressed', item_type: 'pass_fail' },
          { label: 'Willingness to Comply', item_type: 'pass_fail' },
          { label: 'Confidence Score (0-30)', item_type: 'number', is_required: true },
        ],
      },
      {
        name: 'Food Hygiene Rating',
        items: [
          { label: 'Total Score', item_type: 'number', is_required: true },
          { label: 'Food Hygiene Rating', item_type: 'dropdown', is_required: true, options: ['5 - Very Good', '4 - Good', '3 - Generally Satisfactory', '2 - Improvement Necessary', '1 - Major Improvement Necessary', '0 - Urgent Improvement Necessary'] },
          { label: 'Rating Sticker Issued', item_type: 'yes_no' },
          { label: 'Enforcement Action Required', item_type: 'yes_no' },
          { label: 'Enforcement Action Type', item_type: 'multi_select', options: ['Verbal Warning', 'Written Warning', 'Improvement Notice', 'Prohibition Notice', 'Prosecution'] },
          { label: 'Re-visit Required', item_type: 'yes_no' },
          { label: 'Re-visit Date', item_type: 'date' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
        ],
      },
    ],
  },

  // ============================================
  // 8. COSHH ASSESSMENT (Control of Substances Hazardous to Health 2002)
  // ============================================
  {
    id: 'compliance-uk-coshh',
    name: 'UK COSHH Assessment',
    description: 'COSHH risk assessment for hazardous substances in the workplace',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Assessment Details',
        items: [
          { label: 'Assessment Reference', item_type: 'text', is_required: true },
          { label: 'Location/Department', item_type: 'text', is_required: true },
          { label: 'Task/Activity', item_type: 'text', is_required: true },
          { label: 'Assessment Date', item_type: 'date', is_required: true },
          { label: 'Assessor Name', item_type: 'text', is_required: true },
          { label: 'Review Date', item_type: 'date', is_required: true },
        ],
      },
      {
        name: 'Substance Details',
        items: [
          { label: 'Substance Name', item_type: 'text', is_required: true },
          { label: 'Manufacturer/Supplier', item_type: 'text' },
          { label: 'Substance Photo', item_type: 'photo' },
          { label: 'Safety Data Sheet Available', item_type: 'yes_no', is_required: true },
          { label: 'SDS Date', item_type: 'date' },
          { label: 'Physical Form', item_type: 'dropdown', is_required: true, options: ['Solid', 'Liquid', 'Gas', 'Dust/Powder', 'Fume', 'Mist', 'Vapour'] },
          { label: 'Hazard Classification', item_type: 'multi_select', is_required: true, options: ['Toxic', 'Harmful', 'Corrosive', 'Irritant', 'Sensitiser', 'Carcinogen', 'Mutagen', 'Reproductive Toxin', 'Flammable', 'Oxidising', 'Environmental Hazard'] },
          { label: 'GHS Pictograms', item_type: 'multi_select', options: ['Skull & Crossbones', 'Exclamation Mark', 'Corrosion', 'Health Hazard', 'Flame', 'Oxidiser', 'Gas Cylinder', 'Environment', 'Explosive'] },
          { label: 'WEL/OEL (if applicable)', item_type: 'text' },
        ],
      },
      {
        name: 'Exposure Assessment',
        items: [
          { label: 'Who is Exposed', item_type: 'multi_select', is_required: true, options: ['Employees', 'Contractors', 'Visitors', 'Public', 'Young Workers', 'Pregnant Workers'] },
          { label: 'Number of People Exposed', item_type: 'number' },
          { label: 'Route of Exposure', item_type: 'multi_select', is_required: true, options: ['Inhalation', 'Skin Contact', 'Eye Contact', 'Ingestion', 'Injection'] },
          { label: 'Frequency of Use', item_type: 'dropdown', options: ['Daily', 'Weekly', 'Monthly', 'Occasionally'] },
          { label: 'Duration of Exposure', item_type: 'text' },
          { label: 'Quantity Used', item_type: 'text' },
          { label: 'Current Controls in Place', item_type: 'textarea' },
        ],
      },
      {
        name: 'Risk Evaluation',
        items: [
          { label: 'Likelihood of Harm', item_type: 'dropdown', is_required: true, options: ['Unlikely', 'Possible', 'Likely', 'Very Likely'] },
          { label: 'Severity of Harm', item_type: 'dropdown', is_required: true, options: ['Minor', 'Moderate', 'Serious', 'Fatal/Major'] },
          { label: 'Risk Level', item_type: 'dropdown', is_required: true, options: ['Low', 'Medium', 'High', 'Very High'] },
          { label: 'Current Controls Adequate', item_type: 'yes_no', is_required: true },
        ],
      },
      {
        name: 'Control Measures',
        items: [
          { label: 'Elimination Possible', item_type: 'yes_no' },
          { label: 'Substitution Possible', item_type: 'yes_no' },
          { label: 'Substitute Product Details', item_type: 'textarea' },
          { label: 'Engineering Controls Required', item_type: 'multi_select', options: ['LEV (Local Exhaust Ventilation)', 'Enclosure', 'Automation', 'Dilution Ventilation', 'None'] },
          { label: 'Administrative Controls', item_type: 'multi_select', options: ['Procedures', 'Training', 'Supervision', 'Signage', 'Permits', 'Health Surveillance', 'Rotation'] },
          { label: 'PPE Required', item_type: 'multi_select', options: ['Gloves', 'Safety Glasses', 'Face Shield', 'Respirator', 'Apron', 'Coveralls', 'Safety Footwear'] },
          { label: 'PPE Specification', item_type: 'textarea' },
          { label: 'Storage Requirements', item_type: 'textarea' },
          { label: 'Disposal Requirements', item_type: 'textarea' },
        ],
      },
      {
        name: 'Emergency Procedures',
        items: [
          { label: 'First Aid Measures', item_type: 'textarea', is_required: true },
          { label: 'Spill Procedure', item_type: 'textarea' },
          { label: 'Fire Fighting Measures', item_type: 'textarea' },
          { label: 'Emergency Contact', item_type: 'text' },
        ],
      },
      {
        name: 'Actions and Sign-off',
        items: [
          { label: 'Additional Actions Required', item_type: 'textarea' },
          { label: 'Action Owner', item_type: 'text' },
          { label: 'Action Due Date', item_type: 'date' },
          { label: 'Residual Risk After Controls', item_type: 'dropdown', options: ['Low', 'Medium', 'High'] },
          { label: 'Assessment Approved By', item_type: 'text' },
          { label: 'Assessor Signature', item_type: 'signature', is_required: true },
          { label: 'Manager Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 9. WORK AT HEIGHT (Work at Height Regulations 2005)
  // ============================================
  {
    id: 'compliance-uk-work-at-height',
    name: 'UK Work at Height Risk Assessment',
    description: 'Risk assessment for work at height activities per Work at Height Regulations 2005',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Assessment Details',
        items: [
          { label: 'Site/Project Name', item_type: 'text', is_required: true },
          { label: 'Site Address', item_type: 'composite_address_uk', is_required: true },
          { label: 'Task Description', item_type: 'textarea', is_required: true },
          { label: 'Assessment Date', item_type: 'date', is_required: true },
          { label: 'Assessor Name', item_type: 'text', is_required: true },
          { label: 'Principal Contractor', item_type: 'text' },
          { label: 'Work Duration', item_type: 'text' },
        ],
      },
      {
        name: 'Work Location',
        items: [
          { label: 'Maximum Working Height (m)', item_type: 'number', is_required: true },
          { label: 'Work Area Description', item_type: 'textarea', is_required: true },
          { label: 'Work Area Photo', item_type: 'photo' },
          { label: 'Internal or External', item_type: 'dropdown', is_required: true, options: ['Internal', 'External', 'Both'] },
          { label: 'Working Surface Type', item_type: 'dropdown', options: ['Roof', 'Scaffold', 'Ladder', 'MEWP', 'Fixed Platform', 'Mobile Tower', 'Other'] },
          { label: 'Surface Condition', item_type: 'condition' },
          { label: 'Fragile Surfaces Present', item_type: 'yes_no', is_required: true },
          { label: 'Fragile Surface Details', item_type: 'textarea' },
          { label: 'Edge Protection Required', item_type: 'yes_no', is_required: true },
        ],
      },
      {
        name: 'Hazard Identification',
        items: [
          { label: 'Fall Hazards Identified', item_type: 'multi_select', is_required: true, options: ['Unprotected Edge', 'Opening/Void', 'Fragile Surface', 'Sloping Surface', 'Unstable Surface', 'Moving Platform', 'Weather Conditions', 'Other'] },
          { label: 'Falling Object Risk', item_type: 'yes_no' },
          { label: 'Overhead Hazards', item_type: 'yes_no' },
          { label: 'Electrical Hazards', item_type: 'yes_no' },
          { label: 'Traffic/Pedestrians Below', item_type: 'yes_no' },
          { label: 'Other Hazards', item_type: 'textarea' },
        ],
      },
      {
        name: 'Hierarchy of Control',
        items: [
          { label: 'Can Work be Avoided at Height', item_type: 'yes_no', is_required: true },
          { label: 'Avoidance Details', item_type: 'textarea' },
          { label: 'Can Fall be Prevented', item_type: 'yes_no', is_required: true },
          { label: 'Prevention Measures', item_type: 'multi_select', options: ['Guardrails', 'Scaffold', 'MEWP', 'Podium Steps', 'Working Platform', 'None'] },
          { label: 'Fall Distance Minimisation', item_type: 'yes_no' },
          { label: 'Collective Protection Required', item_type: 'yes_no' },
          { label: 'Personal Fall Protection Required', item_type: 'yes_no' },
        ],
      },
      {
        name: 'Equipment Selection',
        items: [
          { label: 'Equipment Type Selected', item_type: 'dropdown', is_required: true, options: ['Scaffold', 'Mobile Scaffold Tower', 'MEWP/Cherry Picker', 'Ladder', 'Stepladder', 'Podium Steps', 'Harness/Fall Arrest', 'Safety Net', 'Airbag', 'Other'] },
          { label: 'Equipment Justification', item_type: 'textarea' },
          { label: 'Equipment Inspection Required', item_type: 'yes_no' },
          { label: 'Last Inspection Date', item_type: 'date' },
          { label: 'Equipment Photo', item_type: 'photo' },
          { label: 'Competent Person Required', item_type: 'yes_no' },
          { label: 'PASMA/IPAF Trained', item_type: 'pass_fail' },
        ],
      },
      {
        name: 'Control Measures',
        items: [
          { label: 'Work Area Secured', item_type: 'pass_fail', is_required: true },
          { label: 'Barriers/Exclusion Zone', item_type: 'pass_fail' },
          { label: 'Warning Signs Posted', item_type: 'pass_fail' },
          { label: 'Tool Tethering Required', item_type: 'yes_no' },
          { label: 'Toe Boards/Kick Boards', item_type: 'pass_fail' },
          { label: 'Netting Required', item_type: 'yes_no' },
          { label: 'Weather Restrictions', item_type: 'textarea' },
          { label: 'Maximum Wind Speed (mph)', item_type: 'number' },
          { label: 'Emergency Rescue Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Rescue Equipment Available', item_type: 'pass_fail' },
        ],
      },
      {
        name: 'Risk Rating',
        items: [
          { label: 'Likelihood', item_type: 'dropdown', is_required: true, options: ['Very Unlikely', 'Unlikely', 'Possible', 'Likely', 'Very Likely'] },
          { label: 'Severity', item_type: 'dropdown', is_required: true, options: ['Minor Injury', 'Moderate Injury', 'Major Injury', 'Fatality'] },
          { label: 'Residual Risk Level', item_type: 'dropdown', is_required: true, options: ['Low', 'Medium', 'High', 'Very High'] },
          { label: 'Risk Acceptable', item_type: 'yes_no', is_required: true },
        ],
      },
      {
        name: 'Sign-off',
        items: [
          { label: 'Briefing Required', item_type: 'yes_no' },
          { label: 'Permit to Work Required', item_type: 'yes_no' },
          { label: 'Method Statement Reference', item_type: 'text' },
          { label: 'Review Required Before Work', item_type: 'yes_no' },
          { label: 'Assessor Signature', item_type: 'signature', is_required: true },
          { label: 'Site Manager Signature', item_type: 'signature' },
          { label: 'Assessment Valid Until', item_type: 'date' },
        ],
      },
    ],
  },

  // ============================================
  // 10. DISPLAY SCREEN EQUIPMENT (Health & Safety Display Screen Equipment Regulations 1992)
  // ============================================
  {
    id: 'compliance-uk-dse',
    name: 'UK DSE Workstation Assessment',
    description: 'Display Screen Equipment workstation assessment for VDU users',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'User Details',
        items: [
          { label: 'Employee Name', item_type: 'text', is_required: true },
          { label: 'Department', item_type: 'text', is_required: true },
          { label: 'Job Title', item_type: 'text' },
          { label: 'Workstation Location', item_type: 'text', is_required: true },
          { label: 'Assessment Date', item_type: 'date', is_required: true },
          { label: 'Assessor Name', item_type: 'text', is_required: true },
          { label: 'Hours per Day at DSE', item_type: 'number' },
          { label: 'DSE User Classification', item_type: 'dropdown', is_required: true, options: ['DSE User (Habitual)', 'Occasional User', 'Not a DSE User'] },
        ],
      },
      {
        name: 'Display Screen',
        items: [
          { label: 'Screen Type', item_type: 'dropdown', options: ['LCD Monitor', 'Laptop', 'Dual Monitors', 'Multiple Monitors', 'All-in-One'] },
          { label: 'Workstation Photo', item_type: 'photo' },
          { label: 'Characters Clear and Readable', item_type: 'pass_fail', is_required: true },
          { label: 'Image Stable (No Flicker)', item_type: 'pass_fail' },
          { label: 'Brightness Adjustable', item_type: 'pass_fail' },
          { label: 'Contrast Adjustable', item_type: 'pass_fail' },
          { label: 'Screen Tilt/Swivel Adjustable', item_type: 'pass_fail' },
          { label: 'Screen Height Appropriate', item_type: 'pass_fail', is_required: true },
          { label: 'Screen Distance Appropriate', item_type: 'pass_fail' },
          { label: 'Screen Clean', item_type: 'pass_fail' },
          { label: 'Screen Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Keyboard and Mouse',
        items: [
          { label: 'Keyboard Separate from Screen', item_type: 'pass_fail', is_required: true },
          { label: 'Keyboard Tiltable', item_type: 'pass_fail' },
          { label: 'Space in Front for Wrists', item_type: 'pass_fail', is_required: true },
          { label: 'Keyboard Surface Matt', item_type: 'pass_fail' },
          { label: 'Mouse Easy to Use', item_type: 'pass_fail' },
          { label: 'Mouse at Same Level as Keyboard', item_type: 'pass_fail' },
          { label: 'Adequate Space for Mouse', item_type: 'pass_fail' },
          { label: 'Wrist Rest Available (if needed)', item_type: 'yes_no' },
          { label: 'Keyboard/Mouse Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Work Surface',
        items: [
          { label: 'Desk Size Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Desk Surface Reflective', item_type: 'yes_no' },
          { label: 'Document Holder Available', item_type: 'yes_no' },
          { label: 'Document Holder Needed', item_type: 'yes_no' },
          { label: 'Adequate Leg Room', item_type: 'pass_fail', is_required: true },
          { label: 'Desk Clutter Free', item_type: 'pass_fail' },
          { label: 'Work Surface Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Chair',
        items: [
          { label: 'Chair Stable', item_type: 'pass_fail', is_required: true },
          { label: 'Seat Height Adjustable', item_type: 'pass_fail', is_required: true },
          { label: 'Seat Back Adjustable', item_type: 'pass_fail', is_required: true },
          { label: 'Seat Back Tilt Adjustable', item_type: 'pass_fail' },
          { label: 'Lumbar Support Adequate', item_type: 'pass_fail' },
          { label: 'Arm Rests (if fitted) Adjustable', item_type: 'pass_fail' },
          { label: 'Footrest Required', item_type: 'yes_no' },
          { label: 'Footrest Provided', item_type: 'yes_no' },
          { label: 'Chair Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Chair Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Environment',
        items: [
          { label: 'Lighting Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Glare or Reflections on Screen', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Window Blinds Available', item_type: 'yes_no' },
          { label: 'Temperature Comfortable', item_type: 'pass_fail' },
          { label: 'Ventilation Adequate', item_type: 'pass_fail' },
          { label: 'Noise Levels Acceptable', item_type: 'pass_fail' },
          { label: 'Humidity Acceptable', item_type: 'pass_fail' },
          { label: 'Environment Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Software and Training',
        items: [
          { label: 'Software Appropriate for Task', item_type: 'pass_fail' },
          { label: 'Training Provided', item_type: 'pass_fail' },
          { label: 'User Knows How to Adjust Equipment', item_type: 'pass_fail' },
          { label: 'User Takes Regular Breaks', item_type: 'pass_fail' },
          { label: 'Eye Test Offered', item_type: 'yes_no' },
          { label: 'Eye Test Date', item_type: 'date' },
        ],
      },
      {
        name: 'User Discomfort',
        items: [
          { label: 'User Reports Discomfort', item_type: 'yes_no' },
          { label: 'Discomfort Areas', item_type: 'multi_select', options: ['Neck', 'Shoulders', 'Upper Back', 'Lower Back', 'Arms', 'Wrists', 'Hands', 'Eyes', 'Headaches'] },
          { label: 'Discomfort Frequency', item_type: 'dropdown', options: ['Rarely', 'Sometimes', 'Frequently', 'Constantly'] },
          { label: 'Discomfort Details', item_type: 'textarea' },
        ],
      },
      {
        name: 'Actions and Sign-off',
        items: [
          { label: 'Actions Required', item_type: 'textarea' },
          { label: 'Equipment Required', item_type: 'multi_select', options: ['Monitor Arm', 'Laptop Stand', 'External Keyboard', 'External Mouse', 'Document Holder', 'Footrest', 'Wrist Rest', 'New Chair', 'Monitor Raiser', 'Anti-Glare Screen'] },
          { label: 'Target Completion Date', item_type: 'date' },
          { label: 'Review Date', item_type: 'date' },
          { label: 'User Signature', item_type: 'signature', is_required: true },
          { label: 'Assessor Signature', item_type: 'signature', is_required: true },
        ],
      },
    ],
  },

  // ============================================
  // 11. MANUAL HANDLING (Manual Handling Operations Regulations 1992)
  // ============================================
  {
    id: 'compliance-uk-manual-handling',
    name: 'UK Manual Handling Assessment',
    description: 'Manual handling risk assessment per Manual Handling Operations Regulations 1992',
    record_type_id: 'compliance-uk',
    sections: [
      {
        name: 'Assessment Details',
        items: [
          { label: 'Assessment Reference', item_type: 'text', is_required: true },
          { label: 'Location/Department', item_type: 'text', is_required: true },
          { label: 'Task Description', item_type: 'textarea', is_required: true },
          { label: 'Assessment Date', item_type: 'date', is_required: true },
          { label: 'Assessor Name', item_type: 'text', is_required: true },
          { label: 'Number of Workers Involved', item_type: 'number' },
          { label: 'Frequency of Task', item_type: 'dropdown', options: ['Occasional', 'Regular', 'Frequent', 'Continuous'] },
        ],
      },
      {
        name: 'The Load',
        items: [
          { label: 'Load Description', item_type: 'text', is_required: true },
          { label: 'Load Photo', item_type: 'photo' },
          { label: 'Load Weight (kg)', item_type: 'number', is_required: true },
          { label: 'Load Heavy', item_type: 'yes_no' },
          { label: 'Load Bulky or Unwieldy', item_type: 'yes_no' },
          { label: 'Load Difficult to Grasp', item_type: 'yes_no' },
          { label: 'Load Unstable or Contents Moving', item_type: 'yes_no' },
          { label: 'Load Sharp or Hot', item_type: 'yes_no' },
          { label: 'Load Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'The Task',
        items: [
          { label: 'Task Involves Holding Away from Body', item_type: 'yes_no' },
          { label: 'Task Involves Twisting', item_type: 'yes_no' },
          { label: 'Task Involves Stooping', item_type: 'yes_no' },
          { label: 'Task Involves Reaching', item_type: 'yes_no' },
          { label: 'Task Involves Large Vertical Movement', item_type: 'yes_no' },
          { label: 'Task Involves Long Carrying Distance', item_type: 'number', help_text: 'Distance in metres' },
          { label: 'Task Involves Pushing/Pulling', item_type: 'yes_no' },
          { label: 'Task Involves Repetitive Handling', item_type: 'yes_no' },
          { label: 'Insufficient Rest/Recovery', item_type: 'yes_no' },
          { label: 'Imposed Work Rate', item_type: 'yes_no' },
          { label: 'Task Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'The Working Environment',
        items: [
          { label: 'Space Constraints', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Uneven/Slippery/Unstable Floors', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Variations in Floor Level', item_type: 'yes_no' },
          { label: 'Hot/Cold/Humid Conditions', item_type: 'yes_no' },
          { label: 'Poor Lighting', item_type: 'yes_no' },
          { label: 'Poor Ventilation', item_type: 'yes_no' },
          { label: 'Environment Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Individual Capability',
        items: [
          { label: 'Unusual Strength/Height Required', item_type: 'yes_no' },
          { label: 'Hazard to Pregnant Workers', item_type: 'yes_no' },
          { label: 'Hazard to Workers with Health Problems', item_type: 'yes_no' },
          { label: 'Special Training Required', item_type: 'yes_no' },
          { label: 'Protective Clothing Hinders Movement', item_type: 'yes_no' },
          { label: 'Individual Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Risk Evaluation',
        items: [
          { label: 'Overall Risk Level', item_type: 'dropdown', is_required: true, options: ['Low', 'Medium', 'High', 'Very High'] },
          { label: 'MAC Score (if applicable)', item_type: 'number' },
          { label: 'RAPP Score (if applicable)', item_type: 'number' },
        ],
      },
      {
        name: 'Control Measures',
        items: [
          { label: 'Can Task be Eliminated', item_type: 'yes_no' },
          { label: 'Can Task be Mechanised', item_type: 'yes_no' },
          { label: 'Mechanical Aids Required', item_type: 'multi_select', options: ['Trolley', 'Pallet Truck', 'Hoist', 'Conveyor', 'Lift Table', 'Vacuum Lifter', 'None'] },
          { label: 'Team Lifting Required', item_type: 'yes_no' },
          { label: 'Load Redesign Required', item_type: 'yes_no' },
          { label: 'Workplace Modifications', item_type: 'textarea' },
          { label: 'Training Required', item_type: 'yes_no' },
          { label: 'PPE Required', item_type: 'multi_select', options: ['Gloves', 'Safety Footwear', 'Back Support Belt', 'None'] },
          { label: 'Other Control Measures', item_type: 'textarea' },
        ],
      },
      {
        name: 'Sign-off',
        items: [
          { label: 'Residual Risk Level', item_type: 'dropdown', is_required: true, options: ['Low', 'Medium', 'High'] },
          { label: 'Actions Required', item_type: 'textarea' },
          { label: 'Action Owner', item_type: 'text' },
          { label: 'Target Date', item_type: 'date' },
          { label: 'Review Date', item_type: 'date', is_required: true },
          { label: 'Assessor Signature', item_type: 'signature', is_required: true },
          { label: 'Manager Signature', item_type: 'signature' },
        ],
      },
    ],
  },
];
