/**
 * International Regulatory Compliance Templates
 * 4 templates for international standards (ISO, GDPR, etc.)
 */

import { TemplateDefinition } from './types';

export const COMPLIANCE_INTL_TEMPLATES: TemplateDefinition[] = [
  // ============================================
  // 1. ISO 9001 QUALITY MANAGEMENT AUDIT
  // ============================================
  {
    id: 'compliance-intl-iso9001',
    name: 'ISO 9001 Quality Management Audit',
    description: 'Internal audit checklist for ISO 9001:2015 Quality Management System',
    record_type_id: 'compliance-intl',
    sections: [
      {
        name: 'Audit Information',
        items: [
          { label: 'Organization Name', item_type: 'text', is_required: true },
          { label: 'Department/Process', item_type: 'text', is_required: true },
          { label: 'Audit Date', item_type: 'date', is_required: true },
          { label: 'Lead Auditor', item_type: 'text', is_required: true },
          { label: 'Audit Team Members', item_type: 'text' },
          { label: 'Auditee Representative', item_type: 'text' },
          { label: 'Audit Scope', item_type: 'text', is_required: true },
          { label: 'Audit Criteria', item_type: 'text' },
          { label: 'Previous Audit Date', item_type: 'date' },
        ],
      },
      {
        name: 'Context of Organization (Clause 4)',
        items: [
          { label: 'Internal/External Issues Identified', item_type: 'pass_fail' },
          { label: 'Interested Parties Identified', item_type: 'pass_fail' },
          { label: 'QMS Scope Defined', item_type: 'pass_fail', is_required: true },
          { label: 'QMS Scope Documented', item_type: 'pass_fail' },
          { label: 'Processes Identified', item_type: 'pass_fail', is_required: true },
          { label: 'Process Interactions Defined', item_type: 'pass_fail' },
          { label: 'Clause 4 Evidence', item_type: 'text' },
          { label: 'Clause 4 Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Leadership (Clause 5)',
        items: [
          { label: 'Top Management Commitment', item_type: 'pass_fail', is_required: true },
          { label: 'Quality Policy Established', item_type: 'pass_fail', is_required: true },
          { label: 'Quality Policy Communicated', item_type: 'pass_fail' },
          { label: 'Quality Policy Available', item_type: 'pass_fail' },
          { label: 'Customer Focus Demonstrated', item_type: 'pass_fail' },
          { label: 'Roles and Responsibilities Defined', item_type: 'pass_fail', is_required: true },
          { label: 'Authorities Assigned', item_type: 'pass_fail' },
          { label: 'Clause 5 Evidence', item_type: 'text' },
          { label: 'Clause 5 Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Planning (Clause 6)',
        items: [
          { label: 'Risks and Opportunities Addressed', item_type: 'pass_fail', is_required: true },
          { label: 'Actions to Address Risks', item_type: 'pass_fail' },
          { label: 'Quality Objectives Established', item_type: 'pass_fail', is_required: true },
          { label: 'Objectives Measurable', item_type: 'pass_fail' },
          { label: 'Objectives Monitored', item_type: 'pass_fail' },
          { label: 'Change Planning Process', item_type: 'pass_fail' },
          { label: 'Clause 6 Evidence', item_type: 'text' },
          { label: 'Clause 6 Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Support (Clause 7)',
        items: [
          { label: 'Resources Determined and Provided', item_type: 'pass_fail', is_required: true },
          { label: 'Personnel Competence', item_type: 'pass_fail', is_required: true },
          { label: 'Training Records Maintained', item_type: 'pass_fail' },
          { label: 'Infrastructure Adequate', item_type: 'pass_fail' },
          { label: 'Work Environment Controlled', item_type: 'pass_fail' },
          { label: 'Monitoring/Measuring Resources', item_type: 'pass_fail' },
          { label: 'Calibration Records', item_type: 'pass_fail' },
          { label: 'Organizational Knowledge Managed', item_type: 'pass_fail' },
          { label: 'Awareness of QMS', item_type: 'pass_fail' },
          { label: 'Internal Communication', item_type: 'pass_fail' },
          { label: 'External Communication', item_type: 'pass_fail' },
          { label: 'Documented Information Controlled', item_type: 'pass_fail', is_required: true },
          { label: 'Document Approval Process', item_type: 'pass_fail' },
          { label: 'Clause 7 Evidence', item_type: 'text' },
          { label: 'Clause 7 Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Operation (Clause 8)',
        items: [
          { label: 'Operational Planning and Control', item_type: 'pass_fail', is_required: true },
          { label: 'Customer Requirements Determined', item_type: 'pass_fail', is_required: true },
          { label: 'Customer Communication', item_type: 'pass_fail' },
          { label: 'Design and Development Process', item_type: 'pass_fail' },
          { label: 'Design Inputs Defined', item_type: 'pass_fail' },
          { label: 'Design Reviews Conducted', item_type: 'pass_fail' },
          { label: 'Design Verification', item_type: 'pass_fail' },
          { label: 'Design Validation', item_type: 'pass_fail' },
          { label: 'Supplier Evaluation', item_type: 'pass_fail' },
          { label: 'Supplier Performance Monitoring', item_type: 'pass_fail' },
          { label: 'Production Control', item_type: 'pass_fail', is_required: true },
          { label: 'Product Identification', item_type: 'pass_fail' },
          { label: 'Traceability', item_type: 'pass_fail' },
          { label: 'Customer Property Control', item_type: 'pass_fail' },
          { label: 'Preservation of Product', item_type: 'pass_fail' },
          { label: 'Release of Products', item_type: 'pass_fail' },
          { label: 'Nonconforming Output Control', item_type: 'pass_fail', is_required: true },
          { label: 'Clause 8 Evidence', item_type: 'text' },
          { label: 'Clause 8 Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Performance Evaluation (Clause 9)',
        items: [
          { label: 'Monitoring and Measurement', item_type: 'pass_fail', is_required: true },
          { label: 'Customer Satisfaction Monitored', item_type: 'pass_fail', is_required: true },
          { label: 'Analysis and Evaluation', item_type: 'pass_fail' },
          { label: 'Internal Audit Program', item_type: 'pass_fail', is_required: true },
          { label: 'Audit Criteria/Scope Defined', item_type: 'pass_fail' },
          { label: 'Auditor Impartiality', item_type: 'pass_fail' },
          { label: 'Audit Results Reported', item_type: 'pass_fail' },
          { label: 'Management Review Conducted', item_type: 'pass_fail', is_required: true },
          { label: 'Review Inputs Addressed', item_type: 'pass_fail' },
          { label: 'Review Outputs Documented', item_type: 'pass_fail' },
          { label: 'Clause 9 Evidence', item_type: 'text' },
          { label: 'Clause 9 Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Improvement (Clause 10)',
        items: [
          { label: 'Improvement Opportunities Identified', item_type: 'pass_fail', is_required: true },
          { label: 'Nonconformity Handling', item_type: 'pass_fail', is_required: true },
          { label: 'Corrective Actions Taken', item_type: 'pass_fail', is_required: true },
          { label: 'Root Cause Analysis', item_type: 'pass_fail' },
          { label: 'Corrective Action Effectiveness', item_type: 'pass_fail' },
          { label: 'Continual Improvement', item_type: 'pass_fail' },
          { label: 'Clause 10 Evidence', item_type: 'text' },
          { label: 'Clause 10 Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Audit Summary',
        items: [
          { label: 'Total Conformities', item_type: 'number' },
          { label: 'Major Nonconformities', item_type: 'number', is_required: true },
          { label: 'Minor Nonconformities', item_type: 'number', is_required: true },
          { label: 'Observations', item_type: 'number' },
          { label: 'Opportunities for Improvement', item_type: 'number' },
          { label: 'Nonconformity Details', item_type: 'text' },
          { label: 'Audit Conclusion', item_type: 'select', is_required: true, options: ['QMS Effective', 'QMS Effective with Minor Issues', 'QMS Requires Significant Improvement', 'QMS Not Effective'] },
          { label: 'Follow-up Audit Required', item_type: 'yes_no' },
          { label: 'Follow-up Date', item_type: 'date' },
          { label: 'Lead Auditor Signature', item_type: 'signature', is_required: true },
          { label: 'Auditee Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 2. ISO 45001 OCCUPATIONAL HEALTH & SAFETY AUDIT
  // ============================================
  {
    id: 'compliance-intl-iso45001',
    name: 'ISO 45001 OH&S Management Audit',
    description: 'Internal audit checklist for ISO 45001:2018 Occupational Health and Safety',
    record_type_id: 'compliance-intl',
    sections: [
      {
        name: 'Audit Information',
        items: [
          { label: 'Organization Name', item_type: 'text', is_required: true },
          { label: 'Site/Location', item_type: 'text', is_required: true },
          { label: 'Audit Date', item_type: 'date', is_required: true },
          { label: 'Lead Auditor', item_type: 'text', is_required: true },
          { label: 'Audit Scope', item_type: 'text', is_required: true },
          { label: 'Auditee(s)', item_type: 'text' },
        ],
      },
      {
        name: 'Context and Leadership (Clauses 4-5)',
        items: [
          { label: 'OH&S Context Defined', item_type: 'pass_fail' },
          { label: 'Worker Needs/Expectations Considered', item_type: 'pass_fail' },
          { label: 'OH&S Scope Established', item_type: 'pass_fail', is_required: true },
          { label: 'Top Management Commitment', item_type: 'pass_fail', is_required: true },
          { label: 'OH&S Policy Established', item_type: 'pass_fail', is_required: true },
          { label: 'Policy Includes Commitment to Prevention', item_type: 'pass_fail' },
          { label: 'Policy Communicated to Workers', item_type: 'pass_fail' },
          { label: 'Roles/Responsibilities Assigned', item_type: 'pass_fail', is_required: true },
          { label: 'Worker Consultation Mechanisms', item_type: 'pass_fail', is_required: true },
          { label: 'Worker Participation', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Planning (Clause 6)',
        items: [
          { label: 'Hazard Identification Process', item_type: 'pass_fail', is_required: true },
          { label: 'Hazards Continually Identified', item_type: 'pass_fail' },
          { label: 'Risk Assessment Process', item_type: 'pass_fail', is_required: true },
          { label: 'Risks Prioritized', item_type: 'pass_fail' },
          { label: 'Opportunities Identified', item_type: 'pass_fail' },
          { label: 'Legal Requirements Determined', item_type: 'pass_fail', is_required: true },
          { label: 'Legal Compliance Evaluated', item_type: 'pass_fail' },
          { label: 'OH&S Objectives Established', item_type: 'pass_fail', is_required: true },
          { label: 'Objectives Measurable', item_type: 'pass_fail' },
          { label: 'Planning to Achieve Objectives', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Support (Clause 7)',
        items: [
          { label: 'Resources Provided', item_type: 'pass_fail', is_required: true },
          { label: 'Worker Competence Ensured', item_type: 'pass_fail', is_required: true },
          { label: 'Training Records Maintained', item_type: 'pass_fail' },
          { label: 'OH&S Awareness', item_type: 'pass_fail' },
          { label: 'Internal Communication', item_type: 'pass_fail' },
          { label: 'External Communication', item_type: 'pass_fail' },
          { label: 'Documented Information Controlled', item_type: 'pass_fail', is_required: true },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Operation (Clause 8)',
        items: [
          { label: 'Operational Planning', item_type: 'pass_fail', is_required: true },
          { label: 'Hierarchy of Controls Applied', item_type: 'pass_fail', is_required: true },
          { label: 'Elimination/Substitution Considered', item_type: 'pass_fail' },
          { label: 'Engineering Controls', item_type: 'pass_fail' },
          { label: 'Administrative Controls', item_type: 'pass_fail' },
          { label: 'PPE Provided', item_type: 'pass_fail' },
          { label: 'Management of Change', item_type: 'pass_fail', is_required: true },
          { label: 'Procurement Controls', item_type: 'pass_fail' },
          { label: 'Contractor Controls', item_type: 'pass_fail' },
          { label: 'Outsourcing Controls', item_type: 'pass_fail' },
          { label: 'Emergency Preparedness', item_type: 'pass_fail', is_required: true },
          { label: 'Emergency Response Tested', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Performance Evaluation (Clause 9)',
        items: [
          { label: 'OH&S Performance Monitored', item_type: 'pass_fail', is_required: true },
          { label: 'Legal Compliance Evaluated', item_type: 'pass_fail', is_required: true },
          { label: 'Internal Audits Conducted', item_type: 'pass_fail', is_required: true },
          { label: 'Management Review Conducted', item_type: 'pass_fail', is_required: true },
          { label: 'Worker Participation in Review', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Improvement (Clause 10)',
        items: [
          { label: 'Incident Investigation Process', item_type: 'pass_fail', is_required: true },
          { label: 'Root Cause Determined', item_type: 'pass_fail' },
          { label: 'Corrective Actions Implemented', item_type: 'pass_fail', is_required: true },
          { label: 'Effectiveness Evaluated', item_type: 'pass_fail' },
          { label: 'Continual Improvement', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Audit Summary',
        items: [
          { label: 'Major Nonconformities', item_type: 'number', is_required: true },
          { label: 'Minor Nonconformities', item_type: 'number', is_required: true },
          { label: 'Observations', item_type: 'number' },
          { label: 'Nonconformity Details', item_type: 'text' },
          { label: 'Positive Findings', item_type: 'text' },
          { label: 'Audit Conclusion', item_type: 'select', is_required: true, options: ['OH&S MS Effective', 'OH&S MS Effective with Minor Issues', 'OH&S MS Requires Improvement', 'OH&S MS Not Effective'] },
          { label: 'Lead Auditor Signature', item_type: 'signature', is_required: true },
          { label: 'Auditee Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 3. ISO 14001 ENVIRONMENTAL MANAGEMENT AUDIT
  // ============================================
  {
    id: 'compliance-intl-iso14001',
    name: 'ISO 14001 Environmental Management Audit',
    description: 'Internal audit checklist for ISO 14001:2015 Environmental Management System',
    record_type_id: 'compliance-intl',
    sections: [
      {
        name: 'Audit Information',
        items: [
          { label: 'Organization Name', item_type: 'text', is_required: true },
          { label: 'Site/Location', item_type: 'text', is_required: true },
          { label: 'Audit Date', item_type: 'date', is_required: true },
          { label: 'Lead Auditor', item_type: 'text', is_required: true },
          { label: 'Audit Scope', item_type: 'text', is_required: true },
        ],
      },
      {
        name: 'Context and Leadership (Clauses 4-5)',
        items: [
          { label: 'Internal/External Issues Identified', item_type: 'pass_fail' },
          { label: 'Interested Parties Identified', item_type: 'pass_fail' },
          { label: 'EMS Scope Defined', item_type: 'pass_fail', is_required: true },
          { label: 'Top Management Commitment', item_type: 'pass_fail', is_required: true },
          { label: 'Environmental Policy Established', item_type: 'pass_fail', is_required: true },
          { label: 'Policy Includes Prevention of Pollution', item_type: 'pass_fail' },
          { label: 'Policy Includes Compliance Commitment', item_type: 'pass_fail' },
          { label: 'Policy Includes Continual Improvement', item_type: 'pass_fail' },
          { label: 'Policy Communicated', item_type: 'pass_fail' },
          { label: 'Roles/Responsibilities Assigned', item_type: 'pass_fail', is_required: true },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Planning (Clause 6)',
        items: [
          { label: 'Environmental Aspects Identified', item_type: 'pass_fail', is_required: true },
          { label: 'Lifecycle Perspective Considered', item_type: 'pass_fail' },
          { label: 'Significant Aspects Determined', item_type: 'pass_fail', is_required: true },
          { label: 'Environmental Impacts Evaluated', item_type: 'pass_fail' },
          { label: 'Compliance Obligations Identified', item_type: 'pass_fail', is_required: true },
          { label: 'Risks/Opportunities Addressed', item_type: 'pass_fail' },
          { label: 'Environmental Objectives Established', item_type: 'pass_fail', is_required: true },
          { label: 'Objectives Consistent with Policy', item_type: 'pass_fail' },
          { label: 'Objectives Measurable', item_type: 'pass_fail' },
          { label: 'Action Plans Developed', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Support and Operation (Clauses 7-8)',
        items: [
          { label: 'Resources Provided', item_type: 'pass_fail', is_required: true },
          { label: 'Competence Ensured', item_type: 'pass_fail' },
          { label: 'Environmental Awareness', item_type: 'pass_fail' },
          { label: 'Communication Processes', item_type: 'pass_fail' },
          { label: 'Documented Information Controlled', item_type: 'pass_fail', is_required: true },
          { label: 'Operational Planning/Control', item_type: 'pass_fail', is_required: true },
          { label: 'Significant Aspects Controlled', item_type: 'pass_fail' },
          { label: 'Procurement Controls', item_type: 'pass_fail' },
          { label: 'Design Considers Environment', item_type: 'pass_fail' },
          { label: 'Emergency Preparedness', item_type: 'pass_fail', is_required: true },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Performance Evaluation (Clause 9)',
        items: [
          { label: 'Environmental Performance Monitored', item_type: 'pass_fail', is_required: true },
          { label: 'Compliance Evaluated', item_type: 'pass_fail', is_required: true },
          { label: 'Internal Audits Conducted', item_type: 'pass_fail', is_required: true },
          { label: 'Management Review Conducted', item_type: 'pass_fail', is_required: true },
          { label: 'Review Outputs Documented', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Improvement (Clause 10)',
        items: [
          { label: 'Nonconformities Addressed', item_type: 'pass_fail', is_required: true },
          { label: 'Corrective Actions Implemented', item_type: 'pass_fail', is_required: true },
          { label: 'Continual Improvement', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Audit Summary',
        items: [
          { label: 'Major Nonconformities', item_type: 'number', is_required: true },
          { label: 'Minor Nonconformities', item_type: 'number', is_required: true },
          { label: 'Observations', item_type: 'number' },
          { label: 'Nonconformity Details', item_type: 'text' },
          { label: 'Audit Conclusion', item_type: 'select', is_required: true, options: ['EMS Effective', 'EMS Effective with Minor Issues', 'EMS Requires Improvement', 'EMS Not Effective'] },
          { label: 'Lead Auditor Signature', item_type: 'signature', is_required: true },
          { label: 'Auditee Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 4. GDPR DATA PROTECTION AUDIT
  // ============================================
  {
    id: 'compliance-intl-gdpr',
    name: 'GDPR Data Protection Audit',
    description: 'Data protection compliance audit for EU General Data Protection Regulation',
    record_type_id: 'compliance-intl',
    sections: [
      {
        name: 'Audit Information',
        items: [
          { label: 'Organization Name', item_type: 'text', is_required: true },
          { label: 'Data Controller/Processor', item_type: 'select', is_required: true, options: ['Data Controller', 'Data Processor', 'Joint Controller', 'Both'] },
          { label: 'Business Unit/Department', item_type: 'text' },
          { label: 'Audit Date', item_type: 'date', is_required: true },
          { label: 'Auditor Name', item_type: 'text', is_required: true },
          { label: 'DPO Name', item_type: 'text' },
          { label: 'DPO Contact', item_type: 'text' },
        ],
      },
      {
        name: 'Lawfulness of Processing (Articles 5-6)',
        items: [
          { label: 'Lawful Basis Identified', item_type: 'pass_fail', is_required: true },
          { label: 'Legal Bases Documented', item_type: 'pass_fail', is_required: true },
          { label: 'Consent Obtained Where Required', item_type: 'pass_fail' },
          { label: 'Consent Freely Given', item_type: 'pass_fail' },
          { label: 'Consent Specific', item_type: 'pass_fail' },
          { label: 'Consent Informed', item_type: 'pass_fail' },
          { label: 'Consent Unambiguous', item_type: 'pass_fail' },
          { label: 'Consent Withdrawable', item_type: 'pass_fail' },
          { label: 'Legitimate Interest Assessment', item_type: 'pass_fail' },
          { label: 'Special Category Conditions Met', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Data Subject Rights (Articles 12-22)',
        items: [
          { label: 'Right to Information Process', item_type: 'pass_fail', is_required: true },
          { label: 'Privacy Notice Available', item_type: 'pass_fail', is_required: true },
          { label: 'Notice Clear and Accessible', item_type: 'pass_fail' },
          { label: 'Right of Access Process', item_type: 'pass_fail', is_required: true },
          { label: 'Subject Access Request Handling', item_type: 'pass_fail' },
          { label: 'Response Within 1 Month', item_type: 'pass_fail' },
          { label: 'Right to Rectification', item_type: 'pass_fail' },
          { label: 'Right to Erasure Process', item_type: 'pass_fail' },
          { label: 'Right to Restriction', item_type: 'pass_fail' },
          { label: 'Data Portability Process', item_type: 'pass_fail' },
          { label: 'Right to Object Process', item_type: 'pass_fail' },
          { label: 'Automated Decision Making Controls', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Security of Processing (Article 32)',
        items: [
          { label: 'Security Measures Appropriate', item_type: 'pass_fail', is_required: true },
          { label: 'Pseudonymisation Used', item_type: 'pass_fail' },
          { label: 'Encryption Implemented', item_type: 'pass_fail' },
          { label: 'Confidentiality Ensured', item_type: 'pass_fail', is_required: true },
          { label: 'Integrity Ensured', item_type: 'pass_fail' },
          { label: 'Availability Ensured', item_type: 'pass_fail' },
          { label: 'Resilience of Systems', item_type: 'pass_fail' },
          { label: 'Regular Testing of Measures', item_type: 'pass_fail' },
          { label: 'Access Controls Implemented', item_type: 'pass_fail', is_required: true },
          { label: 'Staff Training on Security', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Data Breach Notification (Articles 33-34)',
        items: [
          { label: 'Breach Detection Procedures', item_type: 'pass_fail', is_required: true },
          { label: 'Breach Notification Process', item_type: 'pass_fail', is_required: true },
          { label: '72-Hour Notification Capability', item_type: 'pass_fail' },
          { label: 'Data Subject Notification Process', item_type: 'pass_fail' },
          { label: 'Breach Register Maintained', item_type: 'pass_fail', is_required: true },
          { label: 'Incident Response Plan', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Data Protection by Design (Article 25)',
        items: [
          { label: 'Privacy by Design Implemented', item_type: 'pass_fail', is_required: true },
          { label: 'Privacy by Default', item_type: 'pass_fail', is_required: true },
          { label: 'Data Minimisation', item_type: 'pass_fail', is_required: true },
          { label: 'Purpose Limitation', item_type: 'pass_fail' },
          { label: 'Storage Limitation', item_type: 'pass_fail' },
          { label: 'DPIA Process Established', item_type: 'pass_fail' },
          { label: 'DPIAs Conducted Where Required', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Accountability (Article 5(2))',
        items: [
          { label: 'Records of Processing Activities', item_type: 'pass_fail', is_required: true },
          { label: 'ROPA Complete and Accurate', item_type: 'pass_fail' },
          { label: 'Data Processing Agreements', item_type: 'pass_fail', is_required: true },
          { label: 'Processor Compliance Verified', item_type: 'pass_fail' },
          { label: 'International Transfer Safeguards', item_type: 'pass_fail' },
          { label: 'DPO Appointed (if required)', item_type: 'pass_fail' },
          { label: 'DPO Independence Ensured', item_type: 'pass_fail' },
          { label: 'Data Protection Policy', item_type: 'pass_fail' },
          { label: 'Staff Training Records', item_type: 'pass_fail' },
          { label: 'Evidence', item_type: 'text' },
          { label: 'Findings', item_type: 'text' },
        ],
      },
      {
        name: 'Audit Summary',
        items: [
          { label: 'High Risk Findings', item_type: 'number', is_required: true },
          { label: 'Medium Risk Findings', item_type: 'number' },
          { label: 'Low Risk Findings', item_type: 'number' },
          { label: 'Finding Details', item_type: 'text' },
          { label: 'Recommendations', item_type: 'text' },
          { label: 'Overall Compliance Status', item_type: 'select', is_required: true, options: ['Compliant', 'Substantially Compliant', 'Partial Compliance', 'Non-Compliant'] },
          { label: 'Next Audit Date', item_type: 'date' },
          { label: 'Auditor Signature', item_type: 'signature', is_required: true },
          { label: 'DPO/Management Signature', item_type: 'signature' },
        ],
      },
    ],
  },
];
