/**
 * Events and Entertainment Industry Templates
 * 3 templates for event venue and production inspections
 */

import { TemplateDefinition, SAFETY_CHECKLIST_ITEMS } from './types';

export const EVENTS_TEMPLATES: TemplateDefinition[] = [
  // ============================================
  // 1. EVENT VENUE SAFETY INSPECTION
  // ============================================
  {
    id: 'events-venue-safety',
    name: 'Event Venue Safety Inspection',
    description: 'Pre-event safety inspection for venues hosting public events',
    record_type_id: 'events',
    sections: [
      {
        name: 'Event Information',
        items: [
          { label: 'Event Name', item_type: 'text', is_required: true },
          { label: 'Venue Name', item_type: 'text', is_required: true },
          { label: 'Venue Address', item_type: 'text', is_required: true },
          { label: 'Event Date', item_type: 'date', is_required: true },
          { label: 'Event Type', item_type: 'dropdown', is_required: true, options: ['Concert', 'Festival', 'Conference', 'Exhibition', 'Sports Event', 'Wedding', 'Corporate Event', 'Private Party', 'Other'] },
          { label: 'Expected Attendance', item_type: 'number', is_required: true },
          { label: 'Venue Capacity', item_type: 'number' },
          { label: 'Event Organizer', item_type: 'text' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Event Safety Officer', item_type: 'text' },
        ],
      },
      {
        name: 'Venue Access and Egress',
        items: [
          { label: 'Venue Entrance Photo', item_type: 'photo' },
          { label: 'Entry Points Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Number of Entry Points', item_type: 'number' },
          { label: 'Exit Points Adequate for Capacity', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Number of Exit Points', item_type: 'number' },
          { label: 'Emergency Exits Clearly Marked', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Emergency Exits Unobstructed', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Exit Doors Open Outward', item_type: 'pass_fail' },
          { label: 'Crush Barriers Where Needed', item_type: 'pass_fail' },
          { label: 'Disabled Access Available', item_type: 'pass_fail' },
          { label: 'Evacuation Routes Clear', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Assembly Points Identified', item_type: 'pass_fail' },
          { label: 'Access Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Crowd Management',
        items: [
          { label: 'Crowd Management Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Security Personnel Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Number of Security Staff', item_type: 'number' },
          { label: 'Crowd Barriers in Place', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Barrier Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Queuing System Adequate', item_type: 'pass_fail' },
          { label: 'Viewing Areas Safe', item_type: 'pass_fail' },
          { label: 'Stage Barrier Adequate', item_type: 'pass_fail' },
          { label: 'Pit Area Supervised', item_type: 'pass_fail' },
          { label: 'Crowd Density Monitoring', item_type: 'pass_fail' },
          { label: 'Crowd Management Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Fire Safety',
        items: [
          { label: 'Fire Risk Assessment Completed', item_type: 'pass_fail', is_required: true },
          { label: 'Fire Extinguishers Adequate', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Extinguisher Locations Known', item_type: 'pass_fail' },
          { label: 'Fire Alarm System Working', item_type: 'pass_fail', is_required: true },
          { label: 'Emergency Lighting Working', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Exit Signs Illuminated', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Pyrotechnics Planned', item_type: 'yes_no' },
          { label: 'Pyrotechnics Permits Obtained', item_type: 'pass_fail' },
          { label: 'Fire Warden Designated', item_type: 'pass_fail' },
          { label: 'Evacuation Plan in Place', item_type: 'pass_fail', is_required: true },
          { label: 'Fire Brigade Notified', item_type: 'yes_no' },
          { label: 'Fire Safety Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Electrical Safety',
        items: [
          { label: 'Electrical Installation Inspected', item_type: 'pass_fail', is_required: true },
          { label: 'Temporary Power Supply Safe', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Generators Positioned Safely', item_type: 'pass_fail' },
          { label: 'Cables Protected from Trips', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'RCDs Installed', item_type: 'pass_fail', is_required: true },
          { label: 'No Overloaded Circuits', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Outdoor Equipment Weatherproof', item_type: 'pass_fail' },
          { label: 'Qualified Electrician On-site', item_type: 'yes_no' },
          { label: 'Electrical Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Structures and Staging',
        items: [
          { label: 'Stage Structure Photo', item_type: 'photo' },
          { label: 'Stage Structural Integrity', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Stage Certification Available', item_type: 'pass_fail' },
          { label: 'Stage Edge Protection', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Rigging Points Certified', item_type: 'pass_fail' },
          { label: 'Lighting Rigs Secure', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Speaker Stacks Stable', item_type: 'pass_fail' },
          { label: 'Temporary Structures Safe', item_type: 'pass_fail' },
          { label: 'Marquees/Tents Anchored', item_type: 'pass_fail' },
          { label: 'Scaffolding Inspected', item_type: 'pass_fail' },
          { label: 'Wind Speed Limits Set', item_type: 'yes_no' },
          { label: 'Structures Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Medical and First Aid',
        items: [
          { label: 'Medical Plan in Place', item_type: 'pass_fail', is_required: true },
          { label: 'First Aid Facilities', item_type: 'pass_fail', is_required: true },
          { label: 'First Aid Post Photo', item_type: 'photo' },
          { label: 'Number of First Aiders', item_type: 'number' },
          { label: 'First Aiders Adequate for Size', item_type: 'pass_fail' },
          { label: 'Ambulance Access Available', item_type: 'pass_fail', is_required: true },
          { label: 'Hospital Route Planned', item_type: 'pass_fail' },
          { label: 'AED Available', item_type: 'pass_fail' },
          { label: 'Stretcher Access Routes', item_type: 'pass_fail' },
          { label: 'Medical Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Welfare Facilities',
        items: [
          { label: 'Toilet Facilities Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Number of Toilets', item_type: 'number' },
          { label: 'Accessible Toilets', item_type: 'pass_fail' },
          { label: 'Hand Washing Facilities', item_type: 'pass_fail' },
          { label: 'Drinking Water Available', item_type: 'pass_fail', is_required: true },
          { label: 'Food Vendors Registered', item_type: 'pass_fail' },
          { label: 'Shaded/Shelter Areas', item_type: 'pass_fail' },
          { label: 'Lost Property/Information Point', item_type: 'pass_fail' },
          { label: 'Welfare Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Communications',
        items: [
          { label: 'Communication Plan', item_type: 'pass_fail', is_required: true },
          { label: 'PA System Working', item_type: 'pass_fail', is_required: true },
          { label: 'Radio Communications', item_type: 'pass_fail' },
          { label: 'Emergency Announcements Planned', item_type: 'pass_fail' },
          { label: 'Control Room/Point', item_type: 'pass_fail' },
          { label: 'Communication Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Overall Venue Ready', item_type: 'dropdown', is_required: true, options: ['Approved', 'Approved with Conditions', 'Not Approved - Action Required'] },
          { label: 'Critical Issues Found', item_type: 'number' },
          { label: 'Issues Requiring Attention', item_type: 'textarea' },
          { label: 'Conditions of Approval', item_type: 'textarea' },
          { label: 'Pre-Event Briefing Required', item_type: 'yes_no' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Event Organizer Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 2. OUTDOOR FESTIVAL SITE INSPECTION
  // ============================================
  {
    id: 'events-festival-site',
    name: 'Outdoor Festival Site Inspection',
    description: 'Comprehensive site inspection for outdoor festivals and multi-day events',
    record_type_id: 'events',
    sections: [
      {
        name: 'Event Details',
        items: [
          { label: 'Festival Name', item_type: 'text', is_required: true },
          { label: 'Site Location', item_type: 'text', is_required: true },
          { label: 'Event Dates', item_type: 'text', is_required: true },
          { label: 'Expected Daily Attendance', item_type: 'number', is_required: true },
          { label: 'Camping On-site', item_type: 'yes_no' },
          { label: 'Site Capacity', item_type: 'number' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Weather Forecast', item_type: 'text' },
        ],
      },
      {
        name: 'Site Layout and Ground Conditions',
        items: [
          { label: 'Site Overview Photo', item_type: 'photo', is_required: true },
          { label: 'Site Plan Available', item_type: 'pass_fail', is_required: true },
          { label: 'Ground Conditions', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Drainage Adequate', item_type: 'pass_fail' },
          { label: 'Slopes Safe for Activities', item_type: 'pass_fail' },
          { label: 'Trip Hazards Identified', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Trackway Laid Where Needed', item_type: 'pass_fail' },
          { label: 'Vehicle Routes Defined', item_type: 'pass_fail' },
          { label: 'Pedestrian Routes Clear', item_type: 'pass_fail' },
          { label: 'Site Layout Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Vehicle and Traffic Management',
        items: [
          { label: 'Traffic Management Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Car Parking Adequate', item_type: 'pass_fail' },
          { label: 'Parking Photo', item_type: 'photo' },
          { label: 'Disabled Parking', item_type: 'pass_fail' },
          { label: 'Vehicle/Pedestrian Separation', item_type: 'pass_fail', is_required: true },
          { label: 'Emergency Vehicle Access', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Drop-off Points Safe', item_type: 'pass_fail' },
          { label: 'Traffic Marshals', item_type: 'pass_fail' },
          { label: 'Traffic Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Camping Area',
        items: [
          { label: 'Camping Area Photo', item_type: 'photo' },
          { label: 'Camping Layout Clear', item_type: 'pass_fail' },
          { label: 'Fire Lanes Marked (6m)', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Fire Points Established', item_type: 'pass_fail' },
          { label: 'No Naked Flames Policy', item_type: 'pass_fail' },
          { label: 'BBQ Designated Areas', item_type: 'pass_fail' },
          { label: 'Camping Toilets Adequate', item_type: 'pass_fail' },
          { label: 'Shower Facilities', item_type: 'pass_fail' },
          { label: 'Lighting Adequate', item_type: 'pass_fail' },
          { label: 'Security Patrols', item_type: 'pass_fail' },
          { label: 'Camping Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Water and Sanitation',
        items: [
          { label: 'Drinking Water Points', item_type: 'pass_fail', is_required: true },
          { label: 'Water Point Photo', item_type: 'photo' },
          { label: 'Water Supply Tested', item_type: 'pass_fail' },
          { label: 'Toilet Ratio Adequate', item_type: 'pass_fail', is_required: true },
          { label: 'Total Toilets', item_type: 'number' },
          { label: 'Accessible Toilets', item_type: 'number' },
          { label: 'Toilet Servicing Schedule', item_type: 'pass_fail' },
          { label: 'Hand Wash Stations', item_type: 'pass_fail' },
          { label: 'Grey Water Disposal', item_type: 'pass_fail' },
          { label: 'Sanitation Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Waste Management',
        items: [
          { label: 'Waste Management Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Bins Adequate', item_type: 'pass_fail' },
          { label: 'Recycling Facilities', item_type: 'pass_fail' },
          { label: 'Bin Collection Schedule', item_type: 'pass_fail' },
          { label: 'Litter Picking Team', item_type: 'pass_fail' },
          { label: 'Hazardous Waste Disposal', item_type: 'pass_fail' },
          { label: 'Waste Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Food and Drink Vendors',
        items: [
          { label: 'Vendor Layout Photo', item_type: 'photo' },
          { label: 'All Vendors Registered', item_type: 'pass_fail', is_required: true },
          { label: 'Food Hygiene Certificates', item_type: 'pass_fail', is_required: true },
          { label: 'LPG Storage Safe', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Fire Extinguishers at Vendors', item_type: 'pass_fail' },
          { label: 'Electrical Connections Safe', item_type: 'pass_fail' },
          { label: 'Adequate Spacing', item_type: 'pass_fail' },
          { label: 'Food Vendor Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Weather Contingency',
        items: [
          { label: 'Weather Monitoring Plan', item_type: 'pass_fail', is_required: true },
          { label: 'Adverse Weather Procedures', item_type: 'pass_fail', is_required: true },
          { label: 'Wind Speed Triggers Set', item_type: 'pass_fail' },
          { label: 'Lightning Procedure', item_type: 'pass_fail' },
          { label: 'Flood Risk Assessed', item_type: 'pass_fail' },
          { label: 'Heat/Cold Weather Plan', item_type: 'pass_fail' },
          { label: 'Weather Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Site Approval Status', item_type: 'dropdown', is_required: true, options: ['Approved', 'Approved with Conditions', 'Conditional - Re-inspection Required', 'Not Approved'] },
          { label: 'Critical Issues', item_type: 'number' },
          { label: 'Outstanding Actions', item_type: 'textarea' },
          { label: 'Conditions of Approval', item_type: 'textarea' },
          { label: 'Re-inspection Date', item_type: 'date' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Event Manager Signature', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 3. PRODUCTION EQUIPMENT INSPECTION
  // ============================================
  {
    id: 'events-production-equipment',
    name: 'Production Equipment Inspection',
    description: 'Technical inspection for audio, lighting, and staging equipment',
    record_type_id: 'events',
    sections: [
      {
        name: 'Production Details',
        items: [
          { label: 'Event/Production Name', item_type: 'text', is_required: true },
          { label: 'Venue', item_type: 'text', is_required: true },
          { label: 'Production Company', item_type: 'text' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Production Manager', item_type: 'text' },
        ],
      },
      {
        name: 'Rigging and Flying',
        items: [
          { label: 'Rigging Plot Available', item_type: 'pass_fail', is_required: true },
          { label: 'Rigging Photo', item_type: 'photo' },
          { label: 'Load Calculations Verified', item_type: 'pass_fail', is_required: true },
          { label: 'Points Within SWL', item_type: 'pass_fail', is_required: true },
          { label: 'Motors Certified', item_type: 'pass_fail' },
          { label: 'Motor Certificate Dates Valid', item_type: 'pass_fail' },
          { label: 'Secondary Safety Steel', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Shackles Rated', item_type: 'pass_fail' },
          { label: 'Slings Inspected', item_type: 'pass_fail' },
          { label: 'Bridle Angles Correct', item_type: 'pass_fail' },
          { label: 'Control System Working', item_type: 'pass_fail' },
          { label: 'Emergency Stop Working', item_type: 'pass_fail', is_required: true },
          { label: 'Qualified Rigger On-site', item_type: 'pass_fail', is_required: true },
          { label: 'Rigging Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Trussing and Ground Support',
        items: [
          { label: 'Truss System Photo', item_type: 'photo' },
          { label: 'Truss Certification', item_type: 'pass_fail', is_required: true },
          { label: 'Truss Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Pin/Bolt Connections Secure', item_type: 'pass_fail', is_required: true },
          { label: 'Ground Support Base Plates', item_type: 'pass_fail' },
          { label: 'Ballast/Weights Adequate', item_type: 'pass_fail' },
          { label: 'Outriggers Extended', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Level and Plumb', item_type: 'pass_fail' },
          { label: 'Barriers Around Bases', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Truss Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Lighting Equipment',
        items: [
          { label: 'Lighting Rig Photo', item_type: 'photo' },
          { label: 'Fixtures Secured', item_type: 'pass_fail', is_required: true },
          { label: 'Safety Bonds on All Fixtures', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Barn Doors/Accessories Secure', item_type: 'pass_fail' },
          { label: 'Moving Heads Locked Off', item_type: 'pass_fail' },
          { label: 'Follow Spots Safe Position', item_type: 'pass_fail' },
          { label: 'Cables Managed', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'DMX Chain Working', item_type: 'pass_fail' },
          { label: 'Lighting Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Audio Equipment',
        items: [
          { label: 'PA System Photo', item_type: 'photo' },
          { label: 'Speaker Stacks Stable', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Line Array Flown Safely', item_type: 'pass_fail' },
          { label: 'Splay Angles Correct', item_type: 'pass_fail' },
          { label: 'Delay Towers Stable', item_type: 'pass_fail' },
          { label: 'Sub Stacks Secure', item_type: 'pass_fail' },
          { label: 'FOH Position Safe', item_type: 'pass_fail' },
          { label: 'Monitor Position Safe', item_type: 'pass_fail' },
          { label: 'Cable Runs Protected', item_type: 'pass_fail' },
          { label: 'Audio Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Video and LED',
        items: [
          { label: 'LED Screen Present', item_type: 'yes_no' },
          { label: 'LED Screen Photo', item_type: 'photo' },
          { label: 'Screen Structure Stable', item_type: 'pass_fail' },
          { label: 'Screen Secured', item_type: 'pass_fail' },
          { label: 'Wind Loading Considered', item_type: 'pass_fail' },
          { label: 'Projection Equipment Secure', item_type: 'pass_fail' },
          { label: 'Camera Positions Safe', item_type: 'pass_fail' },
          { label: 'Video Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Power Distribution',
        items: [
          { label: 'Power Distro Photo', item_type: 'photo' },
          { label: 'Power Assessment Completed', item_type: 'pass_fail', is_required: true },
          { label: 'Main Distro Board Safe', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'RCD Protection', item_type: 'pass_fail', is_required: true },
          { label: 'Phase Balance Checked', item_type: 'pass_fail' },
          { label: 'Cables Not Overloaded', item_type: 'pass_fail' },
          { label: 'Cables Protected from Damage', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Earth Bonding Correct', item_type: 'pass_fail' },
          { label: 'Backup Power Available', item_type: 'yes_no' },
          { label: 'Qualified Electrician Signed Off', item_type: 'pass_fail', is_required: true },
          { label: 'Power Notes', item_type: 'textarea' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Production Ready', item_type: 'dropdown', is_required: true, options: ['Approved for Show', 'Approved with Notes', 'Requires Rectification', 'Not Approved'] },
          { label: 'Issues Found', item_type: 'number' },
          { label: 'Issue Details', item_type: 'textarea' },
          { label: 'Rectification Required', item_type: 'textarea' },
          { label: 'Sign-off for Performance', item_type: 'pass_fail' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Production Manager Signature', item_type: 'signature' },
        ],
      },
    ],
  },
];
