/**
 * Facilities Management Templates
 * 6 templates for building and facility maintenance
 */

import { TemplateDefinition, SAFETY_CHECKLIST_ITEMS, SIGN_OFF_ITEMS } from './types';

export const FACILITIES_TEMPLATES: TemplateDefinition[] = [
  // ============================================
  // 1. BUILDING CONDITION SURVEY
  // ============================================
  {
    id: 'facilities-building-condition',
    name: 'Building Condition Survey',
    description: 'Comprehensive building condition assessment for facilities management',
    record_type_id: 'facilities',
    sections: [
      {
        name: 'Building Information',
        items: [
          { label: 'Building Name', item_type: 'text', is_required: true },
          { label: 'Building Address', item_type: 'composite_address_uk', is_required: true },
          { label: 'Building Type', item_type: 'select', is_required: true, options: ['Office', 'Industrial', 'Retail', 'Residential', 'Mixed Use', 'Warehouse', 'Educational', 'Healthcare', 'Other'] },
          { label: 'Year Built', item_type: 'number' },
          { label: 'Total Square Footage', item_type: 'number' },
          { label: 'Number of Floors', item_type: 'number' },
          { label: 'Survey Date', item_type: 'date', is_required: true },
          { label: 'Surveyor Name', item_type: 'text', is_required: true },
          { label: 'Weather Conditions', item_type: 'select', options: ['Clear', 'Cloudy', 'Rainy', 'Snowy', 'Windy'] },
        ],
      },
      {
        name: 'Exterior - Structure',
        items: [
          { label: 'Foundation Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Foundation Cracks', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Exterior Walls Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Wall Cracks or Damage', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Building Photo - Front', item_type: 'photo', is_required: true },
          { label: 'Building Photo - Rear', item_type: 'photo' },
          { label: 'Cladding/Siding Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Pointing/Mortar Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Structural Movement Signs', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Exterior Structure Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Exterior - Roof',
        items: [
          { label: 'Roof Type', item_type: 'select', options: ['Flat', 'Pitched - Tile', 'Pitched - Slate', 'Pitched - Metal', 'Green Roof', 'Other'] },
          { label: 'Roof Covering Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Roof Photo', item_type: 'photo' },
          { label: 'Missing/Damaged Tiles or Shingles', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Flashing Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Gutters Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Downspouts Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Signs of Ponding', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Skylights Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Roof Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Exterior - Grounds',
        items: [
          { label: 'Parking Area Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Sidewalks Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Trip Hazards Present', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Landscaping Condition', item_type: 'condition' },
          { label: 'Drainage Adequate', item_type: 'yes_no' },
          { label: 'Exterior Lighting Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Fencing Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Signage Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Grounds Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Interior - Common Areas',
        items: [
          { label: 'Lobby/Reception Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Corridors Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Stairwells Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Handrails Secure', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Elevators Working', item_type: 'pass_fail' },
          { label: 'Interior Photo', item_type: 'photo' },
          { label: 'Floor Coverings Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Ceiling Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Water Stains Present', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Interior Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Mechanical Systems',
        items: [
          { label: 'HVAC System Type', item_type: 'text' },
          { label: 'HVAC Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Heating System Working', item_type: 'pass_fail' },
          { label: 'Cooling System Working', item_type: 'pass_fail' },
          { label: 'Ventilation Adequate', item_type: 'yes_no' },
          { label: 'Plumbing System Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Leaks Detected', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Water Pressure Adequate', item_type: 'yes_no' },
          { label: 'Hot Water Working', item_type: 'pass_fail' },
          { label: 'Mechanical Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Electrical Systems',
        items: [
          { label: 'Electrical Panel Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Panel Accessible', item_type: 'yes_no' },
          { label: 'Circuits Labeled', item_type: 'yes_no' },
          { label: 'Outlets Working', item_type: 'pass_fail' },
          { label: 'Light Fixtures Working', item_type: 'pass_fail' },
          { label: 'Emergency Lighting Working', item_type: 'pass_fail', is_required: true },
          { label: 'Exit Signs Illuminated', item_type: 'pass_fail', is_required: true },
          { label: 'Exposed Wiring', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Electrical Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Fire and Life Safety',
        items: [
          { label: 'Fire Alarm System Working', item_type: 'pass_fail', is_required: true },
          { label: 'Last Fire Alarm Test Date', item_type: 'date' },
          { label: 'Sprinkler System Condition', item_type: 'condition' },
          { label: 'Fire Extinguishers Present', item_type: 'yes_no', is_required: true },
          { label: 'Fire Extinguishers Current', item_type: 'pass_fail' },
          { label: 'Emergency Exits Clear', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Fire Doors Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Evacuation Plans Posted', item_type: 'yes_no' },
          { label: 'Fire Safety Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Accessibility',
        items: [
          { label: 'Accessible Entrance Available', item_type: 'yes_no' },
          { label: 'Ramps Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Accessible Parking Spaces', item_type: 'yes_no' },
          { label: 'Accessible Restrooms', item_type: 'yes_no' },
          { label: 'Elevator Accessible', item_type: 'yes_no' },
          { label: 'Braille Signage', item_type: 'yes_no' },
          { label: 'Accessibility Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Survey Summary',
        items: [
          { label: 'Overall Building Condition', item_type: 'condition', is_required: true },
          { label: 'Immediate Repairs Required', item_type: 'yes_no' },
          { label: 'Immediate Repair Details', item_type: 'text' },
          { label: 'Short-term Repairs (1-2 years)', item_type: 'text' },
          { label: 'Long-term Repairs (3-5 years)', item_type: 'text' },
          { label: 'Estimated Repair Costs', item_type: 'text' },
          { label: 'Surveyor Comments', item_type: 'text' },
          { label: 'Surveyor Signature', item_type: 'signature', is_required: true },
        ],
      },
    ],
  },

  // ============================================
  // 2. HVAC INSPECTION
  // ============================================
  {
    id: 'facilities-hvac-inspection',
    name: 'HVAC Inspection',
    description: 'Heating, ventilation, and air conditioning system inspection',
    record_type_id: 'facilities',
    sections: [
      {
        name: 'System Information',
        items: [
          { label: 'Building/Location', item_type: 'text', is_required: true },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Unit ID/Name', item_type: 'text', is_required: true },
          { label: 'System Type', item_type: 'select', is_required: true, options: ['Split System', 'Package Unit', 'Rooftop Unit', 'Chiller', 'Boiler', 'Heat Pump', 'VRF/VRV', 'Mini-Split', 'Other'] },
          { label: 'Manufacturer', item_type: 'text' },
          { label: 'Model Number', item_type: 'text' },
          { label: 'Serial Number', item_type: 'text' },
          { label: 'Installation Date', item_type: 'date' },
          { label: 'Last Service Date', item_type: 'date' },
          { label: 'Tonnage/Capacity', item_type: 'text' },
        ],
      },
      {
        name: 'Air Handler / Indoor Unit',
        items: [
          { label: 'Unit Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Unit Photo', item_type: 'photo' },
          { label: 'Air Filter Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Filter Replaced', item_type: 'yes_no' },
          { label: 'Filter Size', item_type: 'text' },
          { label: 'Blower Motor Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Belt Condition (if applicable)', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Evaporator Coil Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Coil Cleaned', item_type: 'yes_no' },
          { label: 'Drain Pan Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Drain Line Clear', item_type: 'pass_fail' },
          { label: 'Indoor Unit Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Condenser / Outdoor Unit',
        items: [
          { label: 'Unit Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Outdoor Unit Photo', item_type: 'photo' },
          { label: 'Condenser Coil Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Coil Cleaned', item_type: 'yes_no' },
          { label: 'Fan Blade Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Fan Motor Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Compressor Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Unusual Noise from Compressor', item_type: 'yes_no' },
          { label: 'Refrigerant Lines Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Insulation Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Clearance Around Unit Adequate', item_type: 'yes_no' },
          { label: 'Outdoor Unit Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Electrical Components',
        items: [
          { label: 'Electrical Connections Tight', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Contactor Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Capacitor Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Relay Condition', item_type: 'condition' },
          { label: 'Wiring Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Voltage Reading (V)', item_type: 'number' },
          { label: 'Amperage Reading (A)', item_type: 'number' },
          { label: 'Electrical Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Refrigerant System',
        items: [
          { label: 'Refrigerant Type', item_type: 'select', options: ['R-22', 'R-410A', 'R-32', 'R-134a', 'R-407C', 'Other'] },
          { label: 'Suction Pressure (PSI)', item_type: 'number' },
          { label: 'Discharge Pressure (PSI)', item_type: 'number' },
          { label: 'Superheat (°F)', item_type: 'number' },
          { label: 'Subcooling (°F)', item_type: 'number' },
          { label: 'Refrigerant Charge OK', item_type: 'pass_fail' },
          { label: 'Refrigerant Added (oz)', item_type: 'number' },
          { label: 'Leak Detected', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Leak Location', item_type: 'text' },
          { label: 'Refrigerant Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Thermostat / Controls',
        items: [
          { label: 'Thermostat Type', item_type: 'select', options: ['Digital Programmable', 'Smart/WiFi', 'Mechanical', 'Building Automation'] },
          { label: 'Thermostat Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Set Temperature (°F)', item_type: 'number' },
          { label: 'Actual Temperature (°F)', item_type: 'number' },
          { label: 'Temperature Differential', item_type: 'number' },
          { label: 'Thermostat Calibrated', item_type: 'pass_fail' },
          { label: 'Controls Responsive', item_type: 'pass_fail' },
          { label: 'Controls Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Performance Testing',
        items: [
          { label: 'System Cycles Properly', item_type: 'pass_fail', is_required: true },
          { label: 'Heating Output Adequate', item_type: 'pass_fail' },
          { label: 'Cooling Output Adequate', item_type: 'pass_fail' },
          { label: 'Airflow Adequate', item_type: 'pass_fail' },
          { label: 'Supply Air Temperature (°F)', item_type: 'temperature' },
          { label: 'Return Air Temperature (°F)', item_type: 'temperature' },
          { label: 'Temperature Split (°F)', item_type: 'number' },
          { label: 'Unusual Odors', item_type: 'yes_no' },
          { label: 'Unusual Noises', item_type: 'yes_no' },
          { label: 'Performance Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Service Summary',
        items: [
          { label: 'Overall System Status', item_type: 'select', is_required: true, options: ['Operational', 'Operational - Needs Service', 'Reduced Capacity', 'Not Operational'] },
          { label: 'Repairs Performed', item_type: 'text' },
          { label: 'Parts Used', item_type: 'text' },
          { label: 'Recommended Repairs', item_type: 'text' },
          { label: 'Priority Level', item_type: 'select', options: ['Emergency', 'Urgent', 'Normal', 'Low'] },
          { label: 'Next Service Due', item_type: 'date' },
          { label: 'Technician Name', item_type: 'text', is_required: true },
          { label: 'Technician Signature', item_type: 'signature', is_required: true },
          { label: 'Time On Site (hours)', item_type: 'number' },
        ],
      },
    ],
  },

  // ============================================
  // 3. CLEANING AUDIT
  // ============================================
  {
    id: 'facilities-cleaning-audit',
    name: 'Cleaning Audit',
    description: 'Janitorial and cleaning quality inspection for commercial facilities',
    record_type_id: 'facilities',
    sections: [
      {
        name: 'Audit Details',
        items: [
          { label: 'Building/Location', item_type: 'text', is_required: true },
          { label: 'Audit Date', item_type: 'date', is_required: true },
          { label: 'Audit Time', item_type: 'time', is_required: true },
          { label: 'Auditor Name', item_type: 'text', is_required: true },
          { label: 'Floor/Area Inspected', item_type: 'text', is_required: true },
          { label: 'Cleaning Shift', item_type: 'select', options: ['Day', 'Evening', 'Night', 'Weekend'] },
          { label: 'Cleaning Contractor', item_type: 'text' },
        ],
      },
      {
        name: 'Entrance and Lobby',
        items: [
          { label: 'Entry Doors Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Glass Clean and Smudge-Free', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Entry Mats Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Floor Clean and Polished', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Furniture Dusted', item_type: 'pass_fail' },
          { label: 'Reception Desk Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Plants Maintained', item_type: 'pass_fail' },
          { label: 'Lobby Photo', item_type: 'photo' },
          { label: 'Lobby Score (1-10)', item_type: 'number' },
          { label: 'Lobby Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Restrooms',
        items: [
          { label: 'Restroom Location', item_type: 'text' },
          { label: 'Toilets Clean', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Urinals Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Sinks Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Mirrors Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Counters Clean', item_type: 'pass_fail' },
          { label: 'Floors Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Trash Emptied', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Paper Products Stocked', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Soap Dispensers Filled', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Air Freshener Working', item_type: 'pass_fail' },
          { label: 'Odor Present', item_type: 'yes_no' },
          { label: 'Restroom Photo', item_type: 'photo' },
          { label: 'Restroom Score (1-10)', item_type: 'number', is_required: true },
          { label: 'Restroom Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Offices and Workspaces',
        items: [
          { label: 'Desks Dusted', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Chairs Clean', item_type: 'pass_fail' },
          { label: 'Computer Screens Dusted', item_type: 'pass_fail' },
          { label: 'Floors Vacuumed/Mopped', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Trash Emptied', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Recycling Emptied', item_type: 'pass_fail' },
          { label: 'Windows/Glass Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Light Fixtures Dusted', item_type: 'pass_fail' },
          { label: 'Vents Dusted', item_type: 'pass_fail' },
          { label: 'Office Score (1-10)', item_type: 'number' },
          { label: 'Office Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Break Room / Kitchen',
        items: [
          { label: 'Counters Clean and Sanitized', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Sink Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Appliances Clean (exterior)', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Microwave Interior Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Refrigerator Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Tables and Chairs Clean', item_type: 'pass_fail' },
          { label: 'Floor Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Trash Emptied', item_type: 'pass_fail' },
          { label: 'Break Room Photo', item_type: 'photo' },
          { label: 'Break Room Score (1-10)', item_type: 'number' },
          { label: 'Break Room Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Corridors and Common Areas',
        items: [
          { label: 'Floors Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Baseboards Clean', item_type: 'pass_fail' },
          { label: 'Walls Free of Marks', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Elevator Interior Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Stairwell Clean', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Handrails Clean', item_type: 'pass_fail' },
          { label: 'Water Fountains Clean', item_type: 'pass_fail' },
          { label: 'Common Area Score (1-10)', item_type: 'number' },
          { label: 'Common Area Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Audit Summary',
        items: [
          { label: 'Overall Cleaning Score (1-100)', item_type: 'number', is_required: true },
          { label: 'Cleaning Rating', item_type: 'select', is_required: true, options: ['Excellent (90-100)', 'Good (80-89)', 'Satisfactory (70-79)', 'Needs Improvement (60-69)', 'Unsatisfactory (<60)'] },
          { label: 'Priority Issues Identified', item_type: 'text' },
          { label: 'Corrective Actions Required', item_type: 'text' },
          { label: 'Contractor Notified', item_type: 'yes_no' },
          { label: 'Follow-up Required', item_type: 'yes_no' },
          { label: 'Auditor Signature', item_type: 'signature', is_required: true },
          { label: 'Contractor Representative', item_type: 'signature' },
        ],
      },
    ],
  },

  // ============================================
  // 4. FIRE EXTINGUISHER INSPECTION
  // ============================================
  {
    id: 'facilities-fire-extinguisher',
    name: 'Fire Extinguisher Inspection',
    description: 'Monthly fire extinguisher inspection and compliance check',
    record_type_id: 'facilities',
    sections: [
      {
        name: 'Inspection Details',
        items: [
          { label: 'Building/Location', item_type: 'text', is_required: true },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Inspection Type', item_type: 'select', is_required: true, options: ['Monthly Visual', 'Annual Professional', 'Six-Year Maintenance', '12-Year Hydrostatic'] },
        ],
      },
      {
        name: 'Extinguisher Details',
        items: [
          { label: 'Extinguisher Number/ID', item_type: 'text', is_required: true },
          { label: 'Location Description', item_type: 'text', is_required: true },
          { label: 'Extinguisher Type', item_type: 'select', is_required: true, options: ['ABC Dry Chemical', 'BC Dry Chemical', 'CO2', 'Water', 'Wet Chemical (Class K)', 'Clean Agent', 'Other'] },
          { label: 'Size/Capacity', item_type: 'select', is_required: true, options: ['2.5 lb', '5 lb', '10 lb', '20 lb', '2.5 gal', 'Other'] },
          { label: 'Manufacturer', item_type: 'text' },
          { label: 'Model Number', item_type: 'text' },
          { label: 'Serial Number', item_type: 'text' },
          { label: 'Manufacture Date', item_type: 'date' },
          { label: 'Last Service Date', item_type: 'date' },
        ],
      },
      {
        name: 'Visual Inspection',
        items: [
          { label: 'Extinguisher Photo', item_type: 'photo', is_required: true },
          { label: 'Location Accessible', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Visible and Not Obstructed', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Mounting Bracket Secure', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Mounting Height Correct', item_type: 'pass_fail' },
          { label: 'Location Sign Present', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Operating Instructions Visible', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Inspection Tag Present', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
        ],
      },
      {
        name: 'Physical Condition',
        items: [
          { label: 'Cylinder Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Corrosion Present', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Dents or Damage', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Handle Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Hose Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Hose Connected Properly', item_type: 'pass_fail' },
          { label: 'Nozzle Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Nozzle Clear of Obstruction', item_type: 'pass_fail' },
        ],
      },
      {
        name: 'Safety Mechanisms',
        items: [
          { label: 'Safety Pin Present', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Safety Pin Sealed', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Tamper Seal Intact', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Pressure Gauge in Green Zone', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Pressure Reading', item_type: 'select', options: ['Undercharged (Red)', 'Normal (Green)', 'Overcharged (Red)'] },
          { label: 'Gauge Readable', item_type: 'pass_fail' },
        ],
      },
      {
        name: 'Weight Check (if applicable)',
        items: [
          { label: 'Weight Check Performed', item_type: 'yes_no' },
          { label: 'Current Weight (lbs)', item_type: 'number' },
          { label: 'Required Minimum Weight (lbs)', item_type: 'number' },
          { label: 'Weight Acceptable', item_type: 'pass_fail' },
        ],
      },
      {
        name: 'Inspection Result',
        items: [
          { label: 'Overall Status', item_type: 'select', is_required: true, options: ['Pass', 'Fail - Needs Repair', 'Fail - Replace', 'Fail - Recharge'] },
          { label: 'Deficiencies Found', item_type: 'text' },
          { label: 'Action Required', item_type: 'select', options: ['None', 'Recharge', 'Repair', 'Replace', 'Relocate', 'Add Signage'] },
          { label: 'Work Order Created', item_type: 'yes_no' },
          { label: 'Work Order Number', item_type: 'text' },
          { label: 'Inspector Initials', item_type: 'text', is_required: true },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
        ],
      },
    ],
  },

  // ============================================
  // 5. ELEVATOR SAFETY INSPECTION
  // ============================================
  {
    id: 'facilities-elevator-safety',
    name: 'Elevator Safety Inspection',
    description: 'Routine elevator safety and maintenance inspection',
    record_type_id: 'facilities',
    sections: [
      {
        name: 'Elevator Information',
        items: [
          { label: 'Building Name', item_type: 'text', is_required: true },
          { label: 'Elevator Number/ID', item_type: 'text', is_required: true },
          { label: 'Elevator Type', item_type: 'select', is_required: true, options: ['Passenger', 'Freight', 'Service', 'Dumbwaiter', 'Escalator', 'Platform Lift'] },
          { label: 'Manufacturer', item_type: 'text' },
          { label: 'Model', item_type: 'text' },
          { label: 'Capacity (lbs)', item_type: 'number' },
          { label: 'Number of Floors Served', item_type: 'number' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Last Professional Inspection', item_type: 'date' },
          { label: 'Certificate Posted', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Certificate Expiry Date', item_type: 'date' },
        ],
      },
      {
        name: 'Car Interior',
        items: [
          { label: 'Interior Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Interior Photo', item_type: 'photo', is_required: true },
          { label: 'Floor Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Walls and Panels Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Ceiling Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Lighting Working', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Emergency Light Working', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Handrails Secure', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Mirror Condition (if present)', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Interior Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Controls and Buttons',
        items: [
          { label: 'Floor Buttons Working', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Door Open Button Working', item_type: 'pass_fail', is_required: true },
          { label: 'Door Close Button Working', item_type: 'pass_fail' },
          { label: 'Emergency Stop Button Working', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Alarm Button Working', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Emergency Phone Working', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Phone Instructions Visible', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Floor Indicator Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Braille/Tactile Markings Present', item_type: 'pass_fail' },
          { label: 'Audible Floor Announcements', item_type: 'pass_fail' },
          { label: 'Control Panel Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Door Operation',
        items: [
          { label: 'Car Doors Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Doors Open/Close Smoothly', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Door Speed Appropriate', item_type: 'pass_fail' },
          { label: 'Door Reopens on Obstruction', item_type: 'pass_fail', is_required: true },
          { label: 'Photo Sensor/Safety Edge Working', item_type: 'pass_fail', is_required: true },
          { label: 'Door Tracks Clean', item_type: 'pass_fail' },
          { label: 'Unusual Door Noises', item_type: 'yes_no' },
          { label: 'Gap Between Car and Landing', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Door Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Ride Quality',
        items: [
          { label: 'Car Levels Properly at Floors', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Smooth Start/Stop', item_type: 'pass_fail' },
          { label: 'Excessive Vibration', item_type: 'yes_no' },
          { label: 'Unusual Noises During Operation', item_type: 'yes_no' },
          { label: 'Approximate Travel Time (seconds)', item_type: 'number' },
          { label: 'Ride Quality Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Landing Doors and Halls',
        items: [
          { label: 'Landing Doors Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Hall Buttons Working', item_type: 'pass_fail', is_required: true },
          { label: 'Indicator Lights Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Hall Stations Clean', item_type: 'pass_fail' },
          { label: 'Fire Service Key Box Present', item_type: 'pass_fail' },
          { label: 'Landing Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Safety Features',
        items: [
          { label: 'Capacity Sign Posted', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Emergency Instructions Posted', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Fire Service Mode Operational', item_type: 'pass_fail' },
          { label: 'ADA Compliant', item_type: 'pass_fail' },
          { label: 'Pit Lighting (if accessible)', item_type: 'pass_fail' },
          { label: 'Machine Room Access Secured', item_type: 'pass_fail' },
          { label: 'Safety Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Overall Condition', item_type: 'condition', is_required: true },
          { label: 'Elevator Status', item_type: 'select', is_required: true, options: ['Operational', 'Operational - Minor Issues', 'Out of Service - Repairs Needed', 'Out of Service - Safety Hazard'] },
          { label: 'Issues Identified', item_type: 'text' },
          { label: 'Maintenance Required', item_type: 'yes_no' },
          { label: 'Maintenance Details', item_type: 'text' },
          { label: 'Service Company Notified', item_type: 'yes_no' },
          { label: 'Follow-up Date', item_type: 'date' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
        ],
      },
    ],
  },

  // ============================================
  // 6. RESTROOM MAINTENANCE CHECK
  // ============================================
  {
    id: 'facilities-restroom-check',
    name: 'Restroom Maintenance Check',
    description: 'Regular restroom cleaning and supply check log',
    record_type_id: 'facilities',
    sections: [
      {
        name: 'Check Information',
        items: [
          { label: 'Building/Location', item_type: 'text', is_required: true },
          { label: 'Restroom Location', item_type: 'text', is_required: true },
          { label: 'Restroom Type', item_type: 'select', is_required: true, options: ['Men', 'Women', 'Unisex', 'Family', 'Accessible'] },
          { label: 'Date', item_type: 'date', is_required: true },
          { label: 'Time', item_type: 'time', is_required: true },
          { label: 'Attendant Name', item_type: 'text', is_required: true },
        ],
      },
      {
        name: 'Cleaning Status',
        items: [
          { label: 'Toilets Cleaned', item_type: 'pass_fail' },
          { label: 'Urinals Cleaned', item_type: 'pass_fail' },
          { label: 'Sinks Cleaned', item_type: 'pass_fail' },
          { label: 'Mirrors Cleaned', item_type: 'pass_fail' },
          { label: 'Counters Wiped', item_type: 'pass_fail' },
          { label: 'Floors Mopped', item_type: 'pass_fail' },
          { label: 'Trash Emptied', item_type: 'pass_fail' },
          { label: 'Sanitary Bins Emptied', item_type: 'pass_fail' },
          { label: 'Walls Spot Cleaned', item_type: 'pass_fail' },
          { label: 'Partitions Wiped', item_type: 'pass_fail' },
        ],
      },
      {
        name: 'Supplies Checked',
        items: [
          { label: 'Toilet Paper Stocked', item_type: 'pass_fail', is_required: true },
          { label: 'Paper Towels Stocked', item_type: 'pass_fail' },
          { label: 'Hand Soap Filled', item_type: 'pass_fail', is_required: true },
          { label: 'Seat Covers Stocked', item_type: 'pass_fail' },
          { label: 'Air Freshener Working', item_type: 'pass_fail' },
          { label: 'Sanitary Products Stocked', item_type: 'pass_fail' },
          { label: 'Supplies Needed', item_type: 'text' },
        ],
      },
      {
        name: 'Fixtures Check',
        items: [
          { label: 'Toilets Flushing Properly', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Urinals Flushing Properly', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Sinks Draining Properly', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Faucets Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Hot Water Available', item_type: 'pass_fail' },
          { label: 'Hand Dryers Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Dispensers Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Lights Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Exhaust Fan Working', item_type: 'pass_fail' },
          { label: 'Door Locks Working', item_type: 'pass_fail', photo_rule: 'on_fail' },
        ],
      },
      {
        name: 'Issues and Notes',
        items: [
          { label: 'Maintenance Issues Found', item_type: 'yes_no' },
          { label: 'Issue Description', item_type: 'text' },
          { label: 'Issue Photo', item_type: 'photo' },
          { label: 'Work Order Submitted', item_type: 'yes_no' },
          { label: 'Work Order Number', item_type: 'text' },
          { label: 'Odor Issues', item_type: 'yes_no' },
          { label: 'Additional Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Sign-Off',
        items: [
          { label: 'Overall Cleanliness Rating', item_type: 'select', is_required: true, options: ['Excellent', 'Good', 'Satisfactory', 'Needs Attention', 'Poor'] },
          { label: 'Attendant Initials', item_type: 'text', is_required: true },
          { label: 'Supervisor Check (if applicable)', item_type: 'text' },
          { label: 'Next Check Time', item_type: 'time' },
        ],
      },
    ],
  },
];
