/**
 * Marine Industry Templates
 * 1 template for vessel and marine inspections
 */

import { TemplateDefinition, SAFETY_CHECKLIST_ITEMS } from './types';

export const MARINE_TEMPLATES: TemplateDefinition[] = [
  // ============================================
  // 1. VESSEL SAFETY INSPECTION
  // ============================================
  {
    id: 'marine-vessel-safety',
    name: 'Vessel Safety Inspection',
    description: 'Comprehensive safety inspection for commercial and recreational vessels',
    record_type_id: 'marine',
    sections: [
      {
        name: 'Vessel Information',
        items: [
          { label: 'Vessel Name', item_type: 'text', is_required: true },
          { label: 'Vessel Type', item_type: 'select', is_required: true, options: ['Motor Yacht', 'Sailing Yacht', 'Fishing Vessel', 'Passenger Vessel', 'Cargo Vessel', 'Workboat', 'RIB', 'Other'] },
          { label: 'Registration Number', item_type: 'text', is_required: true },
          { label: 'Port of Registry', item_type: 'text' },
          { label: 'Length Overall (m)', item_type: 'number' },
          { label: 'Gross Tonnage', item_type: 'number' },
          { label: 'Year Built', item_type: 'number' },
          { label: 'Hull Material', item_type: 'select', options: ['GRP/Fibreglass', 'Steel', 'Aluminium', 'Wood', 'Composite'] },
          { label: 'Owner Name', item_type: 'text', is_required: true },
          { label: 'Current Location', item_type: 'text' },
          { label: 'Inspection Date', item_type: 'date', is_required: true },
          { label: 'Inspector Name', item_type: 'text', is_required: true },
          { label: 'Vessel Photo', item_type: 'photo', is_required: true },
        ],
      },
      {
        name: 'Hull and Structure',
        items: [
          { label: 'Hull Condition (Above Waterline)', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Hull Photo', item_type: 'photo' },
          { label: 'Hull Condition (Below Waterline)', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Osmosis/Blistering', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Corrosion/Rust', item_type: 'yes_no', photo_rule: 'on_yes' },
          { label: 'Antifoul Condition', item_type: 'condition' },
          { label: 'Anodes Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Propeller Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Rudder Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Keel Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Through-Hull Fittings', item_type: 'pass_fail', is_required: true },
          { label: 'Seacocks Operational', item_type: 'pass_fail', is_required: true },
          { label: 'Hull Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Deck and Superstructure',
        items: [
          { label: 'Deck Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Deck Photo', item_type: 'photo' },
          { label: 'Non-Slip Surfaces', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Hatches Watertight', item_type: 'pass_fail', is_required: true },
          { label: 'Portholes/Windows Secure', item_type: 'pass_fail' },
          { label: 'Handrails Secure', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Stanchions and Lifelines', item_type: 'pass_fail', is_required: true, photo_rule: 'on_fail' },
          { label: 'Pushpit and Pulpit', item_type: 'pass_fail' },
          { label: 'Boarding Ladder', item_type: 'pass_fail' },
          { label: 'Anchor Windlass', item_type: 'pass_fail' },
          { label: 'Cleats and Fairleads', item_type: 'pass_fail' },
          { label: 'Deck Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Engine and Mechanical',
        items: [
          { label: 'Engine Room Photo', item_type: 'photo' },
          { label: 'Engine Make/Model', item_type: 'text' },
          { label: 'Engine Hours', item_type: 'number' },
          { label: 'Engine Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Engine Starts and Runs', item_type: 'pass_fail', is_required: true },
          { label: 'Oil Level OK', item_type: 'pass_fail' },
          { label: 'Coolant Level OK', item_type: 'pass_fail' },
          { label: 'No Oil Leaks', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'No Water Leaks', item_type: 'pass_fail', photo_rule: 'on_fail' },
          { label: 'Belts Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Exhaust System', item_type: 'pass_fail' },
          { label: 'Raw Water Strainer', item_type: 'pass_fail' },
          { label: 'Impeller Last Changed', item_type: 'date' },
          { label: 'Fuel System Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Fuel Filters', item_type: 'pass_fail' },
          { label: 'Steering System', item_type: 'pass_fail', is_required: true },
          { label: 'Gearbox/Transmission', item_type: 'pass_fail' },
          { label: 'Propeller Shaft', item_type: 'pass_fail' },
          { label: 'Engine Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Electrical Systems',
        items: [
          { label: 'Battery Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Battery Photo', item_type: 'photo' },
          { label: 'Battery Secured', item_type: 'pass_fail' },
          { label: 'Battery Terminals Clean', item_type: 'pass_fail' },
          { label: 'Battery Ventilation', item_type: 'pass_fail' },
          { label: 'Shore Power System', item_type: 'pass_fail' },
          { label: 'Isolation Switch', item_type: 'pass_fail' },
          { label: 'Wiring Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Circuit Breakers/Fuses', item_type: 'pass_fail' },
          { label: 'Navigation Lights Working', item_type: 'pass_fail', is_required: true },
          { label: 'Interior Lights Working', item_type: 'pass_fail' },
          { label: 'Bilge Pump Working', item_type: 'pass_fail', is_required: true },
          { label: 'Bilge Pump Float Switch', item_type: 'pass_fail' },
          { label: 'Electrical Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Navigation Equipment',
        items: [
          { label: 'Chart Plotter/GPS', item_type: 'pass_fail' },
          { label: 'Radar (if fitted)', item_type: 'pass_fail' },
          { label: 'VHF Radio Working', item_type: 'pass_fail', is_required: true },
          { label: 'Radio Licence Current', item_type: 'pass_fail' },
          { label: 'Depth Sounder', item_type: 'pass_fail' },
          { label: 'Speed/Log', item_type: 'pass_fail' },
          { label: 'Compass', item_type: 'pass_fail' },
          { label: 'AIS (if fitted)', item_type: 'pass_fail' },
          { label: 'Paper Charts Available', item_type: 'pass_fail' },
          { label: 'Navigation Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Safety Equipment',
        items: [
          { label: 'Safety Equipment Photo', item_type: 'photo' },
          { label: 'Lifejackets (Quantity)', item_type: 'number', is_required: true },
          { label: 'Lifejackets Condition', item_type: 'condition', is_required: true, photo_rule: 'on_fail' },
          { label: 'Lifejackets Serviced', item_type: 'pass_fail' },
          { label: 'Lifebuoy/Ring', item_type: 'pass_fail', is_required: true },
          { label: 'Liferaft (if fitted)', item_type: 'pass_fail' },
          { label: 'Liferaft Service Date', item_type: 'date' },
          { label: 'Flares Present', item_type: 'pass_fail', is_required: true },
          { label: 'Flares In Date', item_type: 'pass_fail', is_required: true },
          { label: 'EPIRB (if fitted)', item_type: 'pass_fail' },
          { label: 'EPIRB Registered', item_type: 'pass_fail' },
          { label: 'Fire Extinguishers', item_type: 'pass_fail', is_required: true },
          { label: 'Fire Extinguisher Service Date', item_type: 'date' },
          { label: 'Fire Blanket', item_type: 'pass_fail' },
          { label: 'First Aid Kit', item_type: 'pass_fail', is_required: true },
          { label: 'First Aid Kit Stocked', item_type: 'pass_fail' },
          { label: 'Foghorn/Sound Signal', item_type: 'pass_fail' },
          { label: 'Safety Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Anchoring and Mooring',
        items: [
          { label: 'Primary Anchor', item_type: 'pass_fail', is_required: true },
          { label: 'Anchor Size Appropriate', item_type: 'pass_fail' },
          { label: 'Anchor Chain/Rode Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Chain/Rode Length Adequate', item_type: 'pass_fail' },
          { label: 'Secondary Anchor', item_type: 'pass_fail' },
          { label: 'Mooring Lines', item_type: 'pass_fail', is_required: true },
          { label: 'Mooring Lines Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Fenders Adequate', item_type: 'pass_fail' },
          { label: 'Anchor Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Rigging and Sails (Sailing Vessels)',
        items: [
          { label: 'Sailing Vessel', item_type: 'yes_no' },
          { label: 'Mast Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Rigging Photo', item_type: 'photo' },
          { label: 'Standing Rigging Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Shrouds and Stays', item_type: 'pass_fail' },
          { label: 'Chainplates', item_type: 'pass_fail' },
          { label: 'Turnbuckles/Rigging Screws', item_type: 'pass_fail' },
          { label: 'Running Rigging Condition', item_type: 'condition', photo_rule: 'on_fail' },
          { label: 'Halyards', item_type: 'pass_fail' },
          { label: 'Sheets', item_type: 'pass_fail' },
          { label: 'Winches Working', item_type: 'pass_fail' },
          { label: 'Sails Condition', item_type: 'condition' },
          { label: 'Furling Systems', item_type: 'pass_fail' },
          { label: 'Rigging Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Documentation',
        items: [
          { label: 'Registration Certificate', item_type: 'pass_fail', is_required: true },
          { label: 'Insurance Valid', item_type: 'pass_fail', is_required: true },
          { label: 'Safety Certificate (if required)', item_type: 'pass_fail' },
          { label: 'Radio Licence', item_type: 'pass_fail' },
          { label: "Skipper's Qualifications", item_type: 'pass_fail' },
          { label: 'Engine Service Records', item_type: 'pass_fail' },
          { label: 'Documentation Notes', item_type: 'text' },
        ],
      },
      {
        name: 'Inspection Summary',
        items: [
          { label: 'Overall Vessel Condition', item_type: 'select', is_required: true, options: ['Excellent', 'Good', 'Satisfactory', 'Needs Attention', 'Poor'] },
          { label: 'Seaworthy', item_type: 'select', is_required: true, options: ['Yes - Fully Seaworthy', 'Yes - With Conditions', 'No - Repairs Required', 'No - Unsafe'] },
          { label: 'Critical Defects', item_type: 'number' },
          { label: 'Defect Details', item_type: 'text' },
          { label: 'Recommended Actions', item_type: 'text' },
          { label: 'Urgent Repairs Required', item_type: 'text' },
          { label: 'Next Survey Due', item_type: 'date' },
          { label: 'Inspector Signature', item_type: 'signature', is_required: true },
          { label: 'Owner/Master Signature', item_type: 'signature' },
        ],
      },
    ],
  },
];
