import React from 'react';
import { ViewStyle } from 'react-native';
import {
  Check,
  X,
  CheckCircle,
  XCircle,
  AlertTriangle,
  AlertCircle,
  Circle,
  Calendar,
  Clock,
  Camera,
  PenTool,
  Video,
  Mic,
  MapPin,
  Home,
  FileText,
  LayoutTemplate,
  Layout,
  Layers,
  Users,
  Settings,
  Plus,
  Minus,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronsUp,
  ChevronsDown,
  ChevronsUpDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Trash2,
  Edit,
  Copy,
  Save,
  LogIn,
  LogOut,
  Building,
  Building2,
  Clipboard,
  ClipboardCheck,
  Inbox,
  Loader2,
  Search,
  Filter,
  MoreVertical,
  MoreHorizontal,
  Eye,
  EyeOff,
  Mail,
  Lock,
  User,
  Shield,
  Tag,
  CloudSun,
  Scan,
  Star,
  Info,
  HelpCircle,
  RefreshCw,
  Download,
  Upload,
  Share,
  ExternalLink,
  Menu,
  Grid,
  List,
  Lightbulb,
  Ruler,
  Thermometer,
  Gauge,
  Hash,
  ClipboardList,
  CircleDollarSign,
  Truck,
  Car,
  Wrench,
  Heart,
  DoorOpen,
  FolderKanban,
  Folder,
  FolderPlus,
  Twitter,
  Linkedin,
  Globe,
  CreditCard,
  Bell,
  BookOpen,
  MessageCircle,
  Contact,
  Phone,
  Square,
  CheckSquare,
  MinusSquare,
  Palette,
  Image,
  TrendingUp,
  TrendingDown,
  PauseCircle,
  PlayCircle,
  Activity,
  Crown,
  ArrowUpRight,
  GripVertical,
  type LucideIcon,
} from 'lucide-react-native';
import { colors } from '../../constants/theme';

const iconMap = {
  'check': Check,
  'x': X,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  'circle': Circle,
  'calendar': Calendar,
  'clock': Clock,
  'camera': Camera,
  'pen-tool': PenTool,
  'video': Video,
  'mic': Mic,
  'map-pin': MapPin,
  'home': Home,
  'file-text': FileText,
  'layout-template': LayoutTemplate,
  'users': Users,
  'settings': Settings,
  'plus': Plus,
  'minus': Minus,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevrons-up': ChevronsUp,
  'chevrons-down': ChevronsDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'trash-2': Trash2,
  'edit': Edit,
  'copy': Copy,
  'save': Save,
  'log-in': LogIn,
  'log-out': LogOut,
  'building': Building,
  'clipboard': Clipboard,
  'inbox': Inbox,
  'loader-2': Loader2,
  'search': Search,
  'filter': Filter,
  'more-vertical': MoreVertical,
  'more-horizontal': MoreHorizontal,
  'eye': Eye,
  'eye-off': EyeOff,
  'mail': Mail,
  'lock': Lock,
  'user': User,
  'shield': Shield,
  'tag': Tag,
  'cloud-sun': CloudSun,
  'scan': Scan,
  'star': Star,
  'info': Info,
  'help-circle': HelpCircle,
  'refresh-cw': RefreshCw,
  'download': Download,
  'upload': Upload,
  'share': Share,
  'external-link': ExternalLink,
  'menu': Menu,
  'grid': Grid,
  'list': List,
  'lightbulb': Lightbulb,
  'ruler': Ruler,
  'thermometer': Thermometer,
  'gauge': Gauge,
  'hash': Hash,
  'clipboard-list': ClipboardList,
  'circle-dollar-sign': CircleDollarSign,
  'truck': Truck,
  'wrench': Wrench,
  'heart': Heart,
  'door-open': DoorOpen,
  'folder-kanban': FolderKanban,
  'folder': Folder,
  'folder-plus': FolderPlus,
  'building-2': Building2,
  'twitter': Twitter,
  'linkedin': Linkedin,
  'globe': Globe,
  'credit-card': CreditCard,
  'bell': Bell,
  'book-open': BookOpen,
  'message-circle': MessageCircle,
  'square': Square,
  'check-square': CheckSquare,
  'minus-square': MinusSquare,
  'chevrons-up-down': ChevronsUpDown,
  'clipboard-check': ClipboardCheck,
  'palette': Palette,
  'image': Image,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'pause-circle': PauseCircle,
  'play-circle': PlayCircle,
  'activity': Activity,
  'layout': Layout,
  'layers': Layers,
  'crown': Crown,
  'arrow-up-right': ArrowUpRight,
  'car': Car,
  'contact': Contact,
  'phone': Phone,
  'grip-vertical': GripVertical,
} as const;

export type IconName = keyof typeof iconMap;

interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: ViewStyle;
}

export function Icon({
  name,
  size = 24,
  color = colors.text.primary,
  strokeWidth = 2,
  style,
}: IconProps) {
  const IconComponent = iconMap[name] as LucideIcon;

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return (
    <IconComponent
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      style={style}
    />
  );
}

// Export icon map for external use (e.g., dynamic icon rendering)
export { iconMap };
