/**
 * TypeScript types for AI Template Builder chat
 */

import type { PhotoRule, FieldType } from '../constants/fieldTypes';

/** A single message in the chat conversation */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

/** Conversation stages for the progressive wizard */
export type ConversationStep = 'intent' | 'context' | 'refinement' | 'generation';

/** Request payload sent to the Edge Function */
export interface TemplateBuilderChatRequest {
  messages: {
    role: 'user' | 'assistant';
    content: string;
  }[];
  currentStep: ConversationStep;
}

/** A generated template item from AI */
export interface GeneratedTemplateItem {
  label: string;
  item_type: string;
  is_required: boolean;
  photo_rule: 'never' | 'on_fail' | 'always';
  options?: string[] | null;
}

/** A generated template section from AI */
export interface GeneratedTemplateSection {
  name: string;
  sort_order: number;
  items: GeneratedTemplateItem[];
}

/** Complete template generated by AI */
export interface GeneratedTemplate {
  name: string;
  description: string;
  sections: GeneratedTemplateSection[];
}

/** Response from the Edge Function */
export interface TemplateBuilderChatResponse {
  message: string;
  quickReplies: string[];
  suggestedStep: ConversationStep;
  generatedTemplate: GeneratedTemplate | null;
}

/** Error response from the Edge Function */
export interface TemplateBuilderChatError {
  error: string;
}

/** Chat state for the UI */
export interface ChatState {
  messages: ChatMessage[];
  currentStep: ConversationStep;
  isLoading: boolean;
  error: string | null;
  generatedTemplate: GeneratedTemplate | null;
  quickReplies: string[];
}

/** Initial chat state */
export const initialChatState: ChatState = {
  messages: [],
  currentStep: 'intent',
  isLoading: false,
  error: null,
  generatedTemplate: null,
  quickReplies: [],
};

/** Initial AI greeting message */
export const INITIAL_AI_MESSAGE: Omit<ChatMessage, 'id' | 'timestamp'> = {
  role: 'assistant',
  content:
    "Hi! I'll help you create an inspection template.\n\nWhat type of property or asset are you inspecting?",
};

/** Initial quick reply suggestions */
export const INITIAL_QUICK_REPLIES = [
  'Shopping Centre',
  'Retail Store',
  'Car Park',
  'Vehicle',
  'Equipment',
  'Other...',
];
